In [ ]:
from google.colab import drive

drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [ ]:
!ls "/content/gdrive/My Drive/WWCode Python Workshop"

 2_spark_maps_and_lazy_evaluation.ipynb
'3_data_inputs_and_outputs (1).ipynb'
 3_data_inputs_and_outputs.ipynb
 4_data_wrangling.ipynb
 6_dataframe_quiz_solution.ipynb
'7_data_wrangling-sql (1).ipynb'
 7_data_wrangling-sql.ipynb
 9_spark_sql_quiz_solution.ipynb
'all_conditions 2.csv'
 all_conditions.csv
 archive.zip
'bzone.csv - Sheet1.csv'
 California_Building_Climate_Zones.csv
 California_Building_Climate_Zones.geojson
 climate_data.csv
 climate_data_per_state.csv
 crime_data.csv
 data_analysis.ipynb
 data_engineering_spark.ipynb
'DE Workshop.gdoc'
 ER_diagram.drawio
 GlobalLandTemperatures_GlobalLandTemperaturesByCountry.csv
 GlobalLandTemperatures_GlobalLandTemperaturesByState.csv
 hci_crime_752_pl_co_re_ca_2000-2013_21oct15-ada.xlsx
 housing_data.csv
 Metro_zhvi_bdrmcnt_1_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv
 Metro_zhvi_uc_sfrcondo_tier_0.0_0.33_sm_sa_month.csv
 Metro_zhvi_uc_sfrcondo_tier_0.33_0.67_month.csv
 Metro_zhvi_uc_sfrcondo_tier_0.67_1.0_sm_sa_month.csv
'Notes for workshop.gdoc'
 violentcrimedatadictionary.xlsx
 violent_crimes.xlsx

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
!pip install geopandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting geopandas
  Downloading geopandas-0.10.2-py2.py3-none-any.whl (1.0 MB)
     |████████████████████████████████| 1.0 MB 7.4 MB/s
Collecting pyproj>=2.2.0
  Downloading pyproj-3.2.1-cp37-cp37m-manylinux2010_x86_64.whl (6.3 MB)
     |████████████████████████████████| 6.3 MB 39.8 MB/s
Collecting fiona>=1.8
  Downloading Fiona-1.8.21-cp37-cp37m-manylinux2014_x86_64.whl (16.7 MB)
     |████████████████████████████████| 16.7 MB 41.5 MB/s
Requirement already satisfied: pandas>=0.25.0 in /usr/local/lib/python3.7/dist-packages (from geopandas) (1.3.5)
Requirement already satisfied: shapely>=1.6 in /usr/local/lib/python3.7/dist-packages (from geopandas) (1.8.2)
Collecting munch
  Downloading munch-2.5.0-py2.py3-none-any.whl (10 kB)
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (2022.6.15)
Requirement already satisfied: attrs>=17 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (22.1.0)
Collecting cligj>=0.5
  Downloading cligj-0.7.2-py3-none-any.whl (7.1 kB)
Requirement already satisfied: six>=1.7 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (1.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (57.4.0)
Requirement already satisfied: click>=4.0 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (7.1.2)
Collecting click-plugins>=1.0
  Downloading click_plugins-1.1.1-py2.py3-none-any.whl (7.5 kB)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25.0->geopandas) (2.8.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25.0->geopandas) (1.21.6)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25.0->geopandas) (2022.1)
Installing collected packages: munch, cligj, click-plugins, pyproj, fiona, geopandas
Successfully installed click-plugins-1.1.1 cligj-0.7.2 fiona-1.8.21 geopandas-0.10.2 munch-2.5.0 pyproj-3.2.1

# **Analysis of Climate Data per state**

In [ ]:
climate_csv_path = '/content/gdrive/My Drive/WWCode Python Workshop/GlobalLandTemperatures_GlobalLandTemperaturesByState.csv'
data_climate_per_state = pd.read_csv(climate_csv_path, sep=",", header='infer' )
data_climate_per_state.tail(10)

,dt,AverageTemperature,AverageTemperatureUncertainty,State,Country
645665,2012-12-01,6.633,0.437,Zhejiang,China
645666,2013-01-01,5.120,0.393,Zhejiang,China
645667,2013-02-01,7.867,0.490,Zhejiang,China
645668,2013-03-01,12.116,0.345,Zhejiang,China
645669,2013-04-01,15.710,0.461,Zhejiang,China
645670,2013-05-01,21.634,0.578,Zhejiang,China
645671,2013-06-01,24.679,0.596,Zhejiang,China
645672,2013-07-01,29.272,1.340,Zhejiang,China
645673,2013-08-01,29.202,0.869,Zhejiang,China
645674,2013-09-01,NaN,NaN,Zhejiang,China

In [ ]:
data_climate_per_state.shape

(645675, 7)

In [ ]:
data_climate_per_state = data_climate_per_state[data_climate_per_state['Country'] == 'United States']

In [ ]:
data_climate_per_state = data_climate_per_state.drop(['Brazil','Russia'], axis=1)

In [ ]:
data_climate_per_state.head()

,index,dt,day,month,year,State,AverageTemperature,AverageTemperatureUncertainty
0,7458,1743-11-01,1,11,1743,Alabama,10.722,2.898
1,7459,1743-12-01,1,12,1743,Alabama,NaN,NaN
2,7460,1744-01-01,1,1,1744,Alabama,NaN,NaN
3,7461,1744-02-01,1,2,1744,Alabama,NaN,NaN
4,7462,1744-03-01,1,3,1744,Alabama,NaN,NaN

In [ ]:
data_climate_per_state = data_climate_per_state.drop('Country', axis=1)

In [ ]:
data_climate_per_state = data_climate_per_state.reindex(columns=['index', 'dt', 'day', 'month', 'year','State','AverageTemperature','AverageTemperatureUncertainty'])

In [ ]:
data_climate_per_state["dt"] = pd.to_datetime(data_climate_per_state["dt"])
data_climate_per_state.reset_index(inplace=True)
data_climate_per_state['day'] = data_climate_per_state["dt"].dt.day
data_climate_per_state['month'] = data_climate_per_state["dt"].dt.month
data_climate_per_state['year'] = data_climate_per_state["dt"].dt.year
data_climate_per_state.head()

,index,dt,AverageTemperature,AverageTemperatureUncertainty,State,Country,day,month,year
0,7458,1743-11-01,10.722,2.898,Alabama,United States,1,11,1743
1,7459,1743-12-01,NaN,NaN,Alabama,United States,1,12,1743
2,7460,1744-01-01,NaN,NaN,Alabama,United States,1,1,1744
3,7461,1744-02-01,NaN,NaN,Alabama,United States,1,2,1744
4,7462,1744-03-01,NaN,NaN,Alabama,United States,1,3,1744

In [ ]:
data_climate_per_state.rename(columns={'index': 'unique_key'}, inplace=True)
data_climate_per_state.head()

,unique_key,dt,day,month,year,State,AverageTemperature,AverageTemperatureUncertainty
0,7458,1743-11-01,1,11,1743,Alabama,10.722,2.898
1,7459,1743-12-01,1,12,1743,Alabama,NaN,NaN
2,7460,1744-01-01,1,1,1744,Alabama,NaN,NaN
3,7461,1744-02-01,1,2,1744,Alabama,NaN,NaN
4,7462,1744-03-01,1,3,1744,Alabama,NaN,NaN

In [ ]:
data_climate_per_state.tail()

,unique_key,dt,day,month,year,State,AverageTemperature,AverageTemperatureUncertainty
149740,626435,2013-05-01,1,5,2013,Wyoming,10.607,0.208
149741,626436,2013-06-01,1,6,2013,Wyoming,16.267,0.276
149742,626437,2013-07-01,1,7,2013,Wyoming,20.222,0.133
149743,626438,2013-08-01,1,8,2013,Wyoming,19.621,0.217
149744,626439,2013-09-01,1,9,2013,Wyoming,15.811,1.101

In [ ]:
data_climate_per_state[data_climate_per_state['year']==2000]

,unique_key,dt,day,month,year,State,AverageTemperature,AverageTemperatureUncertainty
3074,10532,2000-01-01,1,1,2000,Alabama,8.274,0.092
3075,10533,2000-02-01,1,2,2000,Alabama,11.476,0.181
3076,10534,2000-03-01,1,3,2000,Alabama,15.244,0.136
3077,10535,2000-04-01,1,4,2000,Alabama,16.032,0.110
3078,10536,2000-05-01,1,5,2000,Alabama,23.743,0.113
...,...,...,...,...,...,...,...,...
149587,626282,2000-08-01,1,8,2000,Wyoming,19.866,0.213
149588,626283,2000-09-01,1,9,2000,Wyoming,12.602,0.167
149589,626284,2000-10-01,1,10,2000,Wyoming,6.301,0.201
149590,626285,2000-11-01,1,11,2000,Wyoming,-6.123,0.182
149591,626286,2000-12-01,1,12,2000,Wyoming,-6.959,0.318

In [ ]:
climate_data_per_state_csv = "/content/gdrive/My Drive/WWCode Python Workshop/climate_data_per_state.csv"
data_climate_per_state.to_csv(climate_data_per_state_csv)

In [ ]:
excel_crime = "/content/gdrive/My Drive/WWCode Python Workshop/hci_crime_752_pl_co_re_ca_2000-2013_21oct15-ada.xlsx"
data_excel_crime = pd.read_excel(excel_crime, sheet_name='ViolentCrime')
data_excel_crime.tail(10)

,ind_id,ind_definition,reportyear,race_eth_code,race_eth_name,geotype,geotypevalue,geoname,county_fips,county_name,region_code,region_name,strata_name_code,strata_name,strata_level_name_code,strata_level_name,numerator,denominator,rate,ll_95ci,ul_95ci,se,rse,ca_decile,ca_rr,dof_population,version
49217,752,"Number of Violent Crimes per 1,000 Population",2013.0,9.0,Total,RE,13.0,Shasta,NaN,NaN,13.0,Shasta,1.0,Type of violent crime,2.0,Forcible rape,84.0,179250.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,178591.0,2015-10-21 11:57:42
49218,752,"Number of Violent Crimes per 1,000 Population",2013.0,9.0,Total,RE,13.0,Shasta,NaN,NaN,13.0,Shasta,1.0,Type of violent crime,3.0,Murder and non-negligent manslaughter,10.0,179250.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,178591.0,2015-10-21 11:57:42
49219,752,"Number of Violent Crimes per 1,000 Population",2013.0,9.0,Total,RE,13.0,Shasta,NaN,NaN,13.0,Shasta,1.0,Type of violent crime,4.0,Robbery,184.0,179250.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,178591.0,2015-10-21 11:57:42
49220,752,"Number of Violent Crimes per 1,000 Population",2013.0,9.0,Total,RE,13.0,Shasta,NaN,NaN,13.0,Shasta,1.0,Type of violent crime,5.0,Violent crime total,1150.0,179250.0,6.415621,6.044815,6.786426,0.189186,2.948839,NaN,1.620500,178591.0,2015-10-21 11:57:42
49221,752,"Number of Violent Crimes per 1,000 Population",2013.0,9.0,Total,RE,14.0,Southern California,NaN,NaN,14.0,Southern California,1.0,Type of violent crime,1.0,Aggravated assault,35091.0,18543759.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18482091.0,2015-10-21 11:57:42
49222,752,"Number of Violent Crimes per 1,000 Population",2013.0,9.0,Total,RE,14.0,Southern California,NaN,NaN,14.0,Southern California,1.0,Type of violent crime,2.0,Forcible rape,3048.0,18543759.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18482091.0,2015-10-21 11:57:42
49223,752,"Number of Violent Crimes per 1,000 Population",2013.0,9.0,Total,RE,14.0,Southern California,NaN,NaN,14.0,Southern California,1.0,Type of violent crime,3.0,Murder and non-negligent manslaughter,849.0,18543759.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18482091.0,2015-10-21 11:57:42
49224,752,"Number of Violent Crimes per 1,000 Population",2013.0,9.0,Total,RE,14.0,Southern California,NaN,NaN,14.0,Southern California,1.0,Type of violent crime,4.0,Robbery,24221.0,18543759.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18482091.0,2015-10-21 11:57:42
49225,752,"Number of Violent Crimes per 1,000 Population",2013.0,9.0,Total,RE,14.0,Southern California,NaN,NaN,14.0,Southern California,1.0,Type of violent crime,5.0,Violent crime total,63209.0,18543759.0,3.408640,3.382067,3.435214,0.013558,0.397750,NaN,0.860977,18482091.0,2015-10-21 11:57:42
49226,END OF TABLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT

Number of Violent Crimes per 1,000 Population

In [ ]:
data_excel_crime.shape

(49227, 27)

In [ ]:
data_excel_crime = data_excel_crime.drop(['ind_definition', 'strata_name','version'	], axis=1)

In [ ]:
data_excel_crime.head()

,ind_id,reportyear,race_eth_code,race_eth_name,geotype,geotypevalue,geoname,county_fips,county_name,region_code,region_name,strata_name_code,strata_level_name_code,strata_level_name,numerator,denominator,rate,ll_95ci,ul_95ci,se,rse,ca_decile,ca_rr,dof_population
0,752,2000.0,9.0,Total,CA,6.0,California,NaN,NaN,NaN,NaN,1.0,1.0,Aggravated assault,138325.0,33847694.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33873086.0
1,752,2000.0,9.0,Total,CA,6.0,California,NaN,NaN,NaN,NaN,1.0,2.0,Forcible rape,9784.0,33847694.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33873086.0
2,752,2000.0,9.0,Total,CA,6.0,California,NaN,NaN,NaN,NaN,1.0,3.0,Murder and non-negligent manslaughter,2079.0,33847694.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33873086.0
3,752,2000.0,9.0,Total,CA,6.0,California,NaN,NaN,NaN,NaN,1.0,4.0,Robbery,60237.0,33847694.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33873086.0
4,752,2000.0,9.0,Total,CA,6.0,California,NaN,NaN,NaN,NaN,1.0,5.0,Violent crime total,210448.0,33847694.0,6.217499,6.190935,6.244063,0.013553,0.217985,NaN,1.0,33873086.0

In [ ]:
data_excel_crime.isnull().sum()

ind_id                        0
reportyear                    1
race_eth_code                 1
race_eth_name                 1
geotype                       1
geotypevalue                  1
geoname                       1
county_fips                1051
county_name                1051
region_code                  71
region_name                  71
strata_name_code              1
strata_level_name_code        1
strata_level_name             1
numerator                 16934
denominator               12137
rate                      41904
ll_95ci                   41904
ul_95ci                   41904
se                        41904
rse                       41904
ca_decile                 42926
ca_rr                     41904
dof_population            10567
dtype: int64

In [ ]:
data_excel_crime.dtypes

ind_id                     object
reportyear                float64
race_eth_code             float64
race_eth_name              object
geotype                    object
geotypevalue              float64
geoname                    object
county_fips               float64
county_name                object
region_code               float64
region_name                object
strata_name_code          float64
strata_level_name_code    float64
strata_level_name          object
numerator                 float64
denominator               float64
rate                      float64
ll_95ci                   float64
ul_95ci                   float64
se                        float64
rse                       float64
ca_decile                 float64
ca_rr                     float64
dof_population            float64
dtype: object

In [ ]:
data_excel_crime.reset_index(inplace=True)
data_excel_crime.head()

,index,ind_id,reportyear,race_eth_code,race_eth_name,geotype,geotypevalue,geoname,county_fips,county_name,region_code,region_name,strata_name_code,strata_level_name_code,strata_level_name,numerator,denominator,rate,ll_95ci,ul_95ci,se,rse,ca_decile,ca_rr,dof_population
0,0,752,2000.0,9.0,Total,CA,6.0,California,NaN,NaN,NaN,NaN,1.0,1.0,Aggravated assault,138325.0,33847694.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33873086.0
1,1,752,2000.0,9.0,Total,CA,6.0,California,NaN,NaN,NaN,NaN,1.0,2.0,Forcible rape,9784.0,33847694.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33873086.0
2,2,752,2000.0,9.0,Total,CA,6.0,California,NaN,NaN,NaN,NaN,1.0,3.0,Murder and non-negligent manslaughter,2079.0,33847694.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33873086.0
3,3,752,2000.0,9.0,Total,CA,6.0,California,NaN,NaN,NaN,NaN,1.0,4.0,Robbery,60237.0,33847694.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33873086.0
4,4,752,2000.0,9.0,Total,CA,6.0,California,NaN,NaN,NaN,NaN,1.0,5.0,Violent crime total,210448.0,33847694.0,6.217499,6.190935,6.244063,0.013553,0.217985,NaN,1.0,33873086.0

In [ ]:
#data_excel_crime['_ID'] = data_excel_crime['reportyear'].astype(str) + data_excel_crime['geoname']
#pd.factorize(data_excel_crime['_ID'])[0]

In [ ]:
data_excel_crime.rename(columns={'index': 'unique_key'}, inplace=True)
data_excel_crime.head()

,unique_key,ind_id,reportyear,race_eth_code,race_eth_name,geotype,geotypevalue,geoname,county_fips,county_name,region_code,region_name,strata_name_code,strata_level_name_code,strata_level_name,numerator,denominator,rate,ll_95ci,ul_95ci,se,rse,ca_decile,ca_rr,dof_population
0,0,752,2000.0,9.0,Total,CA,6.0,California,NaN,NaN,NaN,NaN,1.0,1.0,Aggravated assault,138325.0,33847694.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33873086.0
1,1,752,2000.0,9.0,Total,CA,6.0,California,NaN,NaN,NaN,NaN,1.0,2.0,Forcible rape,9784.0,33847694.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33873086.0
2,2,752,2000.0,9.0,Total,CA,6.0,California,NaN,NaN,NaN,NaN,1.0,3.0,Murder and non-negligent manslaughter,2079.0,33847694.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33873086.0
3,3,752,2000.0,9.0,Total,CA,6.0,California,NaN,NaN,NaN,NaN,1.0,4.0,Robbery,60237.0,33847694.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33873086.0
4,4,752,2000.0,9.0,Total,CA,6.0,California,NaN,NaN,NaN,NaN,1.0,5.0,Violent crime total,210448.0,33847694.0,6.217499,6.190935,6.244063,0.013553,0.217985,NaN,1.0,33873086.0

In [ ]:
excel_to_crime = "/content/gdrive/My Drive/WWCode Python Workshop/violent_crimes.xlsx"
data_excel_crime.to_excel(excel_to_crime, sheet_name='ViolentCrimes')

In [ ]:
#finding duplictes in index
data_excel_crime.ind_id.duplicated().sum()

49225

In [ ]:
crime_data_csv = "/content/gdrive/My Drive/WWCode Python Workshop/crime_data.csv"
data_excel_crime.to_csv(crime_data_csv)

In [ ]:
geo_jason_file = "/content/gdrive/My Drive/WWCode Python Workshop/California_Building_Climate_Zones.geojson"

In [ ]:
import geopandas as gpd
data = gpd.read_file(geo_jason_file)
print(data.head())

   OBJECTID BZone      BAcerage  SHAPE_Length  SHAPE_Area  \
0         1     1  2.263098e+06     13.164776    0.969484
1         2    10  2.008073e+06      6.270269    0.788794
2         3    11  5.852273e+06     11.391989    2.488994
3         4    12  7.639111e+06     12.667741    3.168116
4         5    13  8.154006e+06     10.594912    3.304840

                                            geometry
0  MULTIPOLYGON Z (((-124.09750 41.96808 0.00000,...
1  MULTIPOLYGON Z (((-117.37140 34.20782 1.00000,...
2  MULTIPOLYGON Z (((-121.91380 40.95895 0.00000,...
3  MULTIPOLYGON Z (((-120.89250 38.94104 0.00000,...
4  MULTIPOLYGON Z (((-119.62390 37.37152 0.00000,...

In [ ]:
csv_building_climate = "/content/gdrive/My Drive/WWCode Python Workshop/California_Building_Climate_Zones.csv"
data_building_climate = pd.read_csv(csv_building_climate, sep=",", header='infer' )
data_building_climate.tail(10)

    OBJECTID  BZone      BAcerage  SHAPE_Length    SHAPE_Area
6          7     15  7.372182e+06  1.775625e+06  2.983416e+10
7          8     16  3.458417e+07  5.194097e+06  1.399571e+11
8          9      2  5.027297e+06  1.221183e+06  2.034475e+10
9         10      3  2.041871e+06  1.788472e+06  8.263156e+09
10        11      4  4.580379e+06  1.311706e+06  1.853613e+10
11        12      5  1.965020e+06  7.951484e+05  7.952152e+09
12        13      6  6.275005e+05  1.018327e+06  2.539404e+09
13        14      7  4.556979e+05  4.890031e+05  1.844144e+09
14        15      8  5.234582e+05  2.874851e+05  2.118360e+09
15        16      9  1.036771e+06  5.397988e+05  4.195661e+09

In [ ]:
csv_bzone_climate = "/content/gdrive/My Drive/WWCode Python Workshop/bzone.csv - Sheet1.csv"
data_bzone_climate = pd.read_csv(csv_bzone_climate, sep=",", header='infer' )
data_bzone_climate.tail(10)

    BZone                   City
6       7  San Diego-LindberghCZ
7       8            FullertonCZ
8       9     Burbank-GlendaleCZ
9      10            RiversideCZ
10     11            Red BluffCZ
11     12           SacramentoCZ
12     13               FresnoCZ
13     14             PalmdaleCZ
14     15     Palm Spring-IntlCZ
15     16            Blue Canyon

# Analysis of **Climate** Data

In [ ]:
global_temp_csv_climate = "/content/gdrive/My Drive/WWCode Python Workshop/GlobalLandTemperatures_GlobalLandTemperaturesByCountry.csv"
data_global_climate = pd.read_csv(global_temp_csv_climate, sep=",", header='infer' )
data_global_climate.tail(10)

,dt,AverageTemperature,AverageTemperatureUncertainty,Country
577452,2012-12-01,24.111,0.846,Zimbabwe
577453,2013-01-01,23.812,1.218,Zimbabwe
577454,2013-02-01,24.075,1.286,Zimbabwe
577455,2013-03-01,23.226,0.564,Zimbabwe
577456,2013-04-01,21.142,0.495,Zimbabwe
577457,2013-05-01,19.059,1.022,Zimbabwe
577458,2013-06-01,17.613,0.473,Zimbabwe
577459,2013-07-01,17.000,0.453,Zimbabwe
577460,2013-08-01,19.759,0.717,Zimbabwe
577461,2013-09-01,NaN,NaN,Zimbabwe

In [ ]:
data_global_climate[data_global_climate['Country'].str.contains("United States")]

,dt,AverageTemperature,AverageTemperatureUncertainty,Country
554880,1768-09-01,15.420,2.880,United States
554881,1768-10-01,8.162,3.386,United States
554882,1768-11-01,1.591,3.783,United States
554883,1768-12-01,-2.882,4.979,United States
554884,1769-01-01,-3.952,4.856,United States
...,...,...,...,...
557816,2013-05-01,14.073,0.178,United States
557817,2013-06-01,20.198,0.236,United States
557818,2013-07-01,22.074,0.152,United States
557819,2013-08-01,21.168,0.249,United States
557820,2013-09-01,18.273,1.210,United States

In [ ]:
data_global_climate.groupby(['Country'])['Country'].count()

Country
Afghanistan       2106
Africa            1965
Albania           3239
Algeria           2721
American Samoa    1761
                  ...
Western Sahara    2721
Yemen             1653
Zambia            1965
Zimbabwe          1965
Åland             3239
Name: Country, Length: 243, dtype: int64

In [ ]:
data_global_climate = data_global_climate[data_global_climate['Country']=='United States']

In [ ]:
data_global_climate.tail()

,dt,AverageTemperature,AverageTemperatureUncertainty,Country
557816,2013-05-01,14.073,0.178,United States
557817,2013-06-01,20.198,0.236,United States
557818,2013-07-01,22.074,0.152,United States
557819,2013-08-01,21.168,0.249,United States
557820,2013-09-01,18.273,1.210,United States

In [ ]:
data_global_climate.shape

(2941, 4)

In [ ]:
data_global_climate["dt"] = pd.to_datetime(data_global_climate["dt"])
data_global_climate.reset_index(inplace=True)
data_global_climate['day'] = data_global_climate["dt"].dt.day
data_global_climate['month'] = data_global_climate["dt"].dt.month
data_global_climate['year'] = data_global_climate["dt"].dt.year
data_global_climate.head()

,level_0,index,dt,AverageTemperature,AverageTemperatureUncertainty,Country,day,month,year
0,0,554880,1768-09-01,15.420,2.880,United States,1,9,1768
1,1,554881,1768-10-01,8.162,3.386,United States,1,10,1768
2,2,554882,1768-11-01,1.591,3.783,United States,1,11,1768
3,3,554883,1768-12-01,-2.882,4.979,United States,1,12,1768
4,4,554884,1769-01-01,-3.952,4.856,United States,1,1,1769

In [ ]:
#finding duplictes in index
data_global_climate.index.duplicated().sum()

0

In [ ]:
data_global_climate = data_global_climate.drop(['Country', 'level_0'], axis=1)

In [ ]:
climate_data_csv = "/content/gdrive/My Drive/WWCode Python Workshop/climate_data.csv"
data_global_climate.to_csv(climate_data_csv)

In [ ]:
csv_climate = "/content/gdrive/My Drive/WWCode Python Workshop/all_conditions.csv"
data_climate = pd.read_csv(csv_climate, sep=",", header='infer' )
data_climate.tail(10)

,Stn Id,Stn Name,CIMIS Region,Date,ETo (in),Precip (in),Sol Rad (Ly/day),Avg Vap Pres (mBars),Max Air Temp (F),Min Air Temp (F),Avg Air Temp (F),Max Rel Hum (%),Min Rel Hum (%),Avg Rel Hum (%),Dew Point (F),Avg Wind Speed (mph),Wind Run (miles),Avg Soil Temp (F),Target
128115,261,Gazelle,Northeast Plateau,9/16/2020,0.22,0.0,418.0,7.5,83.9,41.0,63.6,69.0,20.0,37.0,37.1,7.4,176.9,65.4,0
128116,261,Gazelle,Northeast Plateau,9/17/2020,0.21,0.0,452.0,9.3,81.3,42.5,63.3,77.0,26.0,47.0,42.8,6.8,163.3,65.4,0
128117,261,Gazelle,Northeast Plateau,9/18/2020,0.10,0.0,277.0,11.1,72.0,48.8,61.6,82.0,43.0,59.0,47.3,4.6,111.5,65.6,0
128118,262,Linden,San Joaquin Valley,9/12/2020,0.10,0.0,338.0,16.7,83.2,50.6,65.0,97.0,46.0,79.0,58.4,1.6,38.8,69.2,0
128119,262,Linden,San Joaquin Valley,9/13/2020,0.13,0.0,388.0,15.7,86.2,51.7,66.5,97.0,38.0,71.0,56.7,2.4,58.6,70.3,1
128120,262,Linden,San Joaquin Valley,9/14/2020,0.14,0.0,420.0,15.4,84.3,53.7,66.3,95.0,39.0,70.0,56.2,3.4,81.7,69.4,1
128121,262,Linden,San Joaquin Valley,9/15/2020,0.15,0.0,430.0,15.1,86.8,49.6,66.0,96.0,31.0,69.0,55.7,2.7,64.2,69.0,1
128122,262,Linden,San Joaquin Valley,9/16/2020,0.15,0.0,445.0,16.2,89.0,53.6,68.0,97.0,30.0,69.0,57.6,3.3,78.2,69.0,1
128123,262,Linden,San Joaquin Valley,9/17/2020,0.16,0.0,447.0,16.6,88.1,53.3,70.4,97.0,35.0,65.0,58.3,3.3,78.1,69.5,1
128124,262,Linden,San Joaquin Valley,9/18/2020,0.14,0.0,395.0,16.1,81.6,54.7,68.4,95.0,36.0,68.0,57.4,4.0,96.7,70.5,1

In [ ]:
data_climate.dtypes

Stn Id                    int64
Stn Name                 object
CIMIS Region             object
Date                     object
ETo (in)                float64
Precip (in)             float64
Sol Rad (Ly/day)        float64
Avg Vap Pres (mBars)    float64
Max Air Temp (F)        float64
Min Air Temp (F)        float64
Avg Air Temp (F)        float64
Max Rel Hum (%)         float64
Min Rel Hum (%)         float64
Avg Rel Hum (%)         float64
Dew Point (F)           float64
Avg Wind Speed (mph)    float64
Wind Run (miles)        float64
Avg Soil Temp (F)       float64
Target                    int64
dtype: object

In [ ]:
data_climate["Date"] = pd.to_datetime(data_climate["Date"])
data_climate.reset_index(inplace=True)
data_climate['day'] = data_climate["Date"].dt.day
data_climate['month'] = data_climate["Date"].dt.month
data_climate['year'] = data_climate["Date"].dt.year

In [ ]:
data_climate.columns

Index(['index', 'Stn Id', 'Stn Name', 'CIMIS Region', 'Date', 'ETo (in)',
       'Precip (in)', 'Sol Rad (Ly/day)', 'Avg Vap Pres (mBars)',
       'Max Air Temp (F)', 'Min Air Temp (F)', 'Avg Air Temp (F)',
       'Max Rel Hum (%)', 'Min Rel Hum (%)', 'Avg Rel Hum (%)',
       'Dew Point (F)', 'Avg Wind Speed (mph)', 'Wind Run (miles)',
       'Avg Soil Temp (F)', 'Target', 'day', 'month', 'year'],
      dtype='object')

In [ ]:
data_climate.shape

(128125, 23)

In [ ]:
data_climate.tail(10)

,index,Stn Id,Stn Name,CIMIS Region,Date,ETo (in),Precip (in),Sol Rad (Ly/day),Avg Vap Pres (mBars),Max Air Temp (F),Min Air Temp (F),Avg Air Temp (F),Max Rel Hum (%),Min Rel Hum (%),Avg Rel Hum (%),Dew Point (F),Avg Wind Speed (mph),Wind Run (miles),Avg Soil Temp (F),Target,day,month,year
128115,128115,261,Gazelle,Northeast Plateau,2020-09-16,0.22,0.0,418.0,7.5,83.9,41.0,63.6,69.0,20.0,37.0,37.1,7.4,176.9,65.4,0,16,9,2020
128116,128116,261,Gazelle,Northeast Plateau,2020-09-17,0.21,0.0,452.0,9.3,81.3,42.5,63.3,77.0,26.0,47.0,42.8,6.8,163.3,65.4,0,17,9,2020
128117,128117,261,Gazelle,Northeast Plateau,2020-09-18,0.10,0.0,277.0,11.1,72.0,48.8,61.6,82.0,43.0,59.0,47.3,4.6,111.5,65.6,0,18,9,2020
128118,128118,262,Linden,San Joaquin Valley,2020-09-12,0.10,0.0,338.0,16.7,83.2,50.6,65.0,97.0,46.0,79.0,58.4,1.6,38.8,69.2,0,12,9,2020
128119,128119,262,Linden,San Joaquin Valley,2020-09-13,0.13,0.0,388.0,15.7,86.2,51.7,66.5,97.0,38.0,71.0,56.7,2.4,58.6,70.3,1,13,9,2020
128120,128120,262,Linden,San Joaquin Valley,2020-09-14,0.14,0.0,420.0,15.4,84.3,53.7,66.3,95.0,39.0,70.0,56.2,3.4,81.7,69.4,1,14,9,2020
128121,128121,262,Linden,San Joaquin Valley,2020-09-15,0.15,0.0,430.0,15.1,86.8,49.6,66.0,96.0,31.0,69.0,55.7,2.7,64.2,69.0,1,15,9,2020
128122,128122,262,Linden,San Joaquin Valley,2020-09-16,0.15,0.0,445.0,16.2,89.0,53.6,68.0,97.0,30.0,69.0,57.6,3.3,78.2,69.0,1,16,9,2020
128123,128123,262,Linden,San Joaquin Valley,2020-09-17,0.16,0.0,447.0,16.6,88.1,53.3,70.4,97.0,35.0,65.0,58.3,3.3,78.1,69.5,1,17,9,2020
128124,128124,262,Linden,San Joaquin Valley,2020-09-18,0.14,0.0,395.0,16.1,81.6,54.7,68.4,95.0,36.0,68.0,57.4,4.0,96.7,70.5,1,18,9,2020

In [ ]:
data_climate[data_climate['day']==1]

,level_0,index,Stn Id,Stn Name,CIMIS Region,Date,ETo (in),Precip (in),Sol Rad (Ly/day),Avg Vap Pres (mBars),...,Min Rel Hum (%),Avg Rel Hum (%),Dew Point (F),Avg Wind Speed (mph),Wind Run (miles),Avg Soil Temp (F),Target,day,month,year
0,0,0,2,FivePoints,San Joaquin Valley,2018-01-01,0.06,0.00,219.0,7.3,...,46.0,65.0,36.6,3.3,78.3,51.1,0,1,1,2018
30,30,30,2,FivePoints,San Joaquin Valley,2018-02-01,0.07,0.00,222.0,8.4,...,38.0,64.0,40.0,3.3,80.1,53.3,0,1,2,2018
58,58,58,2,FivePoints,San Joaquin Valley,2018-03-01,0.08,0.33,170.0,8.9,...,49.0,67.0,41.4,12.3,294.3,50.3,0,1,3,2018
88,88,88,5,Shafter,San Joaquin Valley,2018-01-01,0.05,0.00,204.0,8.2,...,48.0,78.0,39.4,2.6,62.3,51.5,0,1,1,2018
116,116,116,5,Shafter,San Joaquin Valley,2018-02-01,0.07,0.00,287.0,10.1,...,46.0,75.0,44.9,2.7,64.4,53.3,0,1,2,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127077,127077,127077,261,Gazelle,Northeast Plateau,2020-08-01,0.25,0.00,673.0,11.4,...,23.0,43.0,47.9,3.2,76.5,70.6,1,1,8,2020
127108,127108,127108,261,Gazelle,Northeast Plateau,2020-09-01,0.20,0.00,577.0,10.3,...,21.0,40.0,45.3,2.8,66.6,68.0,1,1,9,2020
127120,127120,127120,262,Linden,San Joaquin Valley,2020-07-01,0.28,0.00,722.0,14.2,...,25.0,52.0,53.8,4.1,99.6,72.1,0,1,7,2020
127151,127151,127151,262,Linden,San Joaquin Valley,2020-08-01,0.26,0.00,689.0,14.6,...,26.0,57.0,54.8,3.7,89.0,67.2,0,1,8,2020
127180,127180,127180,262,Linden,San Joaquin Valley,2020-09-01,0.18,0.00,491.0,15.6,...,42.0,66.0,56.5,4.1,98.9,71.9,1,1,9,2020

In [ ]:
data_excel_crime.reset_index(inplace=True)
data_excel_crime.rename(columns={'index': 'unique_key'}, inplace=True)
data_excel_crime.head()

## **Working with HOUSING DATA**

In [ ]:
pd.set_option('display.max_columns', None)

In [ ]:
csv_file_1 = "/content/gdrive/My Drive/WWCode Python Workshop/Metro_zhvi_uc_sfrcondo_tier_0.0_0.33_sm_sa_month.csv"
data_1 = pd.read_csv(csv_file_1, sep=",")
data_1.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,...,2021-09-30,2021-10-31,2021-11-30,2021-12-31,2022-01-31,2022-02-28,2022-03-31,2022-04-30,2022-05-31,2022-06-30
0,102001,0,United States,Country,NaN,65636.0,65812.0,65991.0,66360.0,66726.0,...,160851.0,162883.0,164797.0,167083.0,169535.0,172237.0,174796.0,177476.0,179887.0,182044.0
1,394913,1,"New York, NY",Msa,NY,140565.0,141355.0,142038.0,143419.0,144711.0,...,375109.0,378331.0,380949.0,383315.0,386150.0,389499.0,393840.0,398565.0,403687.0,408156.0
2,753899,2,"Los Angeles-Long Beach-Anaheim, CA",Msa,CA,150920.0,151319.0,152080.0,153511.0,155108.0,...,596324.0,599491.0,604333.0,610411.0,617079.0,625280.0,637437.0,651329.0,663470.0,665097.0
3,394463,3,"Chicago, IL",Msa,IL,106839.0,107099.0,107422.0,108061.0,108714.0,...,185226.0,187148.0,189036.0,190928.0,192752.0,194570.0,196858.0,199293.0,202044.0,204136.0
4,394514,4,"Dallas-Fort Worth, TX",Msa,TX,83372.0,83445.0,83482.0,83617.0,83773.0,...,228733.0,233081.0,236646.0,240483.0,245491.0,251505.0,257310.0,264053.0,270122.0,275488.0

In [ ]:
data_1.shape

(908, 275)

In [ ]:
data_1.columns

Index(['RegionID', 'SizeRank', 'RegionName', 'RegionType', 'StateName',
       '2000-01-31', '2000-02-29', '2000-03-31', '2000-04-30', '2000-05-31',
       ...
       '2014-03-31', '2014-04-30', '2014-05-31', '2014-06-30', '2014-07-31',
       '2014-08-31', '2014-09-30', '2014-10-31', '2014-11-30', '2014-12-31'],
      dtype='object', length=185)

In [ ]:
data_1.dtypes

RegionID        int64
SizeRank        int64
RegionName     object
RegionType     object
StateName      object
               ...
2022-02-28    float64
2022-03-31    float64
2022-04-30    float64
2022-05-31    float64
2022-06-30    float64
Length: 275, dtype: object

Dropping coulmns That contains years 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022. Keeping years from 2000-2013 since we have criminial data only between those years.

In [ ]:
data_1.columns[data_1.columns.str.contains(pat = '2020')]

Index(['2020-01-31', '2020-02-29', '2020-03-31', '2020-04-30', '2020-05-31',
       '2020-06-30', '2020-07-31', '2020-08-31', '2020-09-30', '2020-10-31',
       '2020-11-30', '2020-12-31'],
      dtype='object')

In [ ]:
data_1 = data_1.drop(data_1.columns[data_1.columns.str.contains(pat = '2020')], axis='columns')

In [ ]:
data_1.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,2000-06-30,2000-07-31,2000-08-31,2000-09-30,2000-10-31,2000-11-30,2000-12-31,2001-01-31,2001-02-28,2001-03-31,2001-04-30,2001-05-31,2001-06-30,2001-07-31,2001-08-31,2001-09-30,2001-10-31,2001-11-30,2001-12-31,2002-01-31,2002-02-28,2002-03-31,2002-04-30,2002-05-31,2002-06-30,2002-07-31,2002-08-31,2002-09-30,2002-10-31,2002-11-30,2002-12-31,2003-01-31,2003-02-28,2003-03-31,2003-04-30,2003-05-31,2003-06-30,2003-07-31,2003-08-31,2003-09-30,2003-10-31,2003-11-30,2003-12-31,2004-01-31,2004-02-29,2004-03-31,2004-04-30,2004-05-31,2004-06-30,2004-07-31,2004-08-31,2004-09-30,2004-10-31,2004-11-30,2004-12-31,2005-01-31,2005-02-28,2005-03-31,2005-04-30,2005-05-31,2005-06-30,2005-07-31,2005-08-31,2005-09-30,2005-10-31,2005-11-30,2005-12-31,2006-01-31,2006-02-28,2006-03-31,2006-04-30,2006-05-31,2006-06-30,2006-07-31,2006-08-31,2006-09-30,2006-10-31,2006-11-30,2006-12-31,2007-01-31,2007-02-28,2007-03-31,2007-04-30,2007-05-31,2007-06-30,2007-07-31,2007-08-31,2007-09-30,2007-10-31,2007-11-30,2007-12-31,2008-01-31,2008-02-29,2008-03-31,2008-04-30,2008-05-31,2008-06-30,2008-07-31,2008-08-31,2008-09-30,2008-10-31,2008-11-30,2008-12-31,2009-01-31,2009-02-28,2009-03-31,2009-04-30,2009-05-31,2009-06-30,2009-07-31,2009-08-31,2009-09-30,2009-10-31,2009-11-30,2009-12-31,2010-01-31,2010-02-28,2010-03-31,2010-04-30,2010-05-31,2010-06-30,2010-07-31,2010-08-31,2010-09-30,2010-10-31,2010-11-30,2010-12-31,2011-01-31,2011-02-28,2011-03-31,2011-04-30,2011-05-31,2011-06-30,2011-07-31,2011-08-31,2011-09-30,2011-10-31,2011-11-30,2011-12-31,2012-01-31,2012-02-29,2012-03-31,2012-04-30,2012-05-31,2012-06-30,2012-07-31,2012-08-31,2012-09-30,2012-10-31,2012-11-30,2012-12-31,2013-01-31,2013-02-28,2013-03-31,2013-04-30,2013-05-31,2013-06-30,2013-07-31,2013-08-31,2013-09-30,2013-10-31,2013-11-30,2013-12-31,2014-01-31,2014-02-28,2014-03-31,2014-04-30,2014-05-31,2014-06-30,2014-07-31,2014-08-31,2014-09-30,2014-10-31,2014-11-30,2014-12-31
0,102001,0,United States,Country,NaN,65636.0,65812.0,65991.0,66360.0,66726.0,67091.0,67455.0,67841.0,68237.0,68636.0,69054.0,69489.0,69903.0,70271.0,70638.0,71024.0,71427.0,71813.0,72202.0,72603.0,73004.0,73406.0,73771.0,74118.0,74437.0,74779.0,75143.0,75529.0,75935.0,76359.0,76817.0,77291.0,77764.0,78242.0,78700.0,79155.0,79570.0,79998.0,80435.0,80904.0,81395.0,81885.0,82391.0,82933.0,83506.0,84078.0,84584.0,85068.0,85563.0,86149.0,86806.0,87503.0,88252.0,89032.0,89857.0,90660.0,91451.0,92206.0,92919.0,93635.0,94349.0,95092.0,95851.0,96694.0,97562.0,98458.0,99336.0,100208.0,101050.0,101832.0,102537.0,103174.0,103720.0,104254.0,104801.0,105382.0,105938.0,106419.0,106794.0,107102.0,107322.0,107526.0,107663.0,107787.0,107866.0,107947.0,108007.0,108075.0,108064.0,107982.0,107794.0,107617.0,107383.0,107129.0,106794.0,106450.0,106014.0,105521.0,104964.0,104377.0,103771.0,103119.0,102409.0,101580.0,100753.0,99948.0,99134.0,98301.0,97463.0,96792.0,96161.0,95572.0,94960.0,94374.0,93835.0,93294.0,92795.0,92405.0,92227.0,92144.0,92083.0,91996.0,91983.0,92065.0,92107.0,92010.0,91665.0,91198.0,90629.0,90067.0,89478.0,88936.0,88404.0,87929.0,87484.0,87024.0,86550.0,86105.0,85766.0,85475.0,85223.0,84956.0,84734.0,84526.0,84396.0,84328.0,84410.0,84584.0,84841.0,85090.0,85355.0,85606.0,85869.0,86164.0,86510.0,86904.0,87372.0,87901.0,88503.0,89131.0,89796.0,90474.0,91150.0,91784.0,92383.0,92957.0,93491.0,94004.0,94499.0,95007.0,95435.0,95815.0,96179.0,96553.0,96889.0,97134.0,97372.0,97656.0,98013.0,98401.0
1,394913,1,"New York, NY",Msa,NY,140565.0,141355.0,142038.0,143419.0,144711.0,146087.0,147558.0,149094.0,150695.0,152250.0,153735.0,155134.0,156492.0,158013.0,159501.0,161071.0,162557.0,164188.0,165808.0,167563.0,169338.0,171268.0,172999.0,174667.0,176375.0,178152.0,179936.0,181665.0,183458.0,185434.0,187566.0,190197.0,192994.0,195830.0,198326.0,200715.0,203081.0,205559.0,208296.0,210887.0,213493.0,216013.0,218730.0,221432.0,223877.0,226111.0,228123.0,230100.0,232260.0,234450.0,236812.0,239221.0,242049.0,245078.0,248305.0,251487.0,254848.0,258163.0,261372.0,264294.0,267136.0,269863.0,272757.0,276178.0,279876.0,283517.0,286903.0,290296.0,293632.0,296998.0,300043.0,303040.0,305548.0,308116.0,310256.0,312414.0,314276.0,316088.0,317223.0,317726.0,317585.0,316979.0,316121.0,315083.0,314079.0,313416.0,313399.0,313486.0,313407.0,312516.0,311255.0,309965.0,308679.0,307774.0,306755.0,305740.0,304966.0,304257.0,303204.0,301711.0,299431.0,297262.0,295004.0,292929.0,290714.0,288234.0,285756.0,283547.0,281340.0,279182.0,276980.0,274747.0,272861.0,270948.0,269177.0,267364.0,265955.0,264875.0,264140.0,263745.0,263667.0,263874.0,263746.0,263638.0,263409.0,263524.0,263514.0,263167.0,262388.0,261172.0,259777.0,258353.0,257383.0,256582.0,256022.0,255106.0,254168.0,252880.0,251590.0,250365.0,249200.0,248110.0,246850.0,245730.0,244745.0,243824.0,243077.0,242389.0,242071.0,241872.0,241618.0,241246.0,240910.0,240691.0,240776.0,241061.0,241576.0,242246.0,242943.0,243850.0,244876.0,246095.0,247325.0,248455.0,249489.0,250657.0,251913.0,253021.0,254211.0,255153.0,256429.0,257583.0,258802.0,259674.0,260168.0,260548.0,260863.0,261213.0,261389.0,261752.0
2,753899,2,"Los Angeles-Long Beach-Anaheim, CA",Msa,CA,150920.0,151319.0,152080.0,153511.0,155108.0,156605.0,158164.0,159847.0,161438.0,162836.0,164145.0,165494.0,166475.0,167478.0,168613.0,170297.0,171974.0,173593.0,175279.0,177087.0,178842.0,180608.0,182151.0,183834.0,185173.0,186730.0,188583.0,190975.0,193649.0,196322.0,199730.0,203310.0,207056.0,210411.0,213755.0,216996.0,219636.0,222044.0,224814.0,227864.0,231717.0,234771.0,238957.0,243309.0,248336.0,252331.0,256219.0,260257.0,265016.0,270074.0,275589.0,282138.0,290301.0,298337.0,305552.0,311807.0,318709.0,325497.0,330193.0,334628.0,338381.0,343825.0,349283.0,355067.0,360298.0,365678.0,371820.0,378407.0,385020.0,392012.0,396868.0,401643.0,405696.0,409534.0,413257.0,416338.0,420559.0,423902.0,425718.0,427340.0,426680.0,427145.0,427026.0,427975.0,428568.0,428672.0,428078.0,427424.0,425549.0,423674.0,419889.0,415782.0,410823.0,405741.0,401730.0,396907.0,392906.0,386901.0,379560.0,369575.0,358983.0,349295.0,339892.0,331251.0,324589.0,318326.0,311855.0,303553.0,297519.0,293759.0,291081.0,288025.0,284985.0,281403.0,278748.0,277029.0,276377.0,276126.0,277230.0,280015.0,281075.0,280622.0,280856.0,282790.0,285548.0,285100.0,283631.0,280601.0,278174.0,275837.0,273680.0,273052.0,272686.0,273154.0,272087.0,271149.0,268032.0,267477.0,266712.0,265629.0,262882.0,260321.0,260016.0,260089.0,259790.0,259388.0,259037.0,259422.0,260208.0,261476.0,263213.0,264571.0,266093.0,268691.0,271650.0,276172.0,280271.0,286429.0,292436.0,299264.0,304917.0,310947.0,316455.0,322443.0,327403.0,331322.0,335374.0,338933.0,343157.0,345159.0,346471.0,346336.0,346964.0,347417.0,348356.0,347823.0,347893.0,348699.0,351000.0,353667.0
3,394463,3,"Chicago, IL",Msa,IL,106839.0,107099.0,107422.0,108061.0,108714.0,109349.0,110033.0,110844.0,111711.0,112603.0,113395.0,114149.0,114839.0,115449.0,116144.0,116857.0,117708.0,118480.0,119223.0,120012.0,120814.0,121678.0,122358.0,122963.0,123473.0,124099.0,124845.0,125464.0,126156.0,126779.0,127626.0,128500.0,129379.0,130210.0,130783.0,131458.0,132075.0,132855.0,133558.0,134374.0,135082.0,135716.0,136278.0,137001.0,137867.0,138713.0,139431.0,140067.0,140863.0,141650.0,142439.0,143292.0,144230.0,145326.0,146330.0,147362.0,148239.0,149169.0,150083.0,151084.0,152030.0,153070.0,154120.0,155288.0,156454.0,157652.0,158752.0,159823.0,160949.0,162034.0,162967.0,163856.0,164710.0,165568.0,166425.0,167182.0,168013.0,168534.0,169014.0,169386.0,169723.0,169921.0,170081.0,170341.0,170773.0,171177.0,171467.0,171551.0,171485.0,171307.0,171016.0,170743.0,170240.0,169779.0,169298.0,168708.0,168061.0,NaN,NaN,164779.0,NaN,163207.0,162668.0,160627.0,159397.0,157199.0,155492.0,153147.0,150508.0,148631.0,146696.0,145866.0,144398.0,143369.0,142250.0,141201.0,139514.0,138017.0,136653.0,136228.0,135528.0,135290.0,134386.0,134782.0,134376.0,134842.0,133286.0,132374.0,130651.0,129513.0,127566.0,125853.0,124239.0,123000.0,122178.0,121095.0,120521.0,119500.0,119146.0,118233.0,117419.0,115771.0,114770.0,113265.0,112502.0,111089.0,110844.0,110460.0,110540.0,110294.0,109677.0,109052.0,108383.0,108517.0,108678.0,108755.0,109103.0,109671.0,110207.0,110940.0,111669.0,112923.0,113930.0,115153.0,116082.0,117400.0,117975.0,118788.0,119166.0,119994.0,120454.0,120795.0,121319.0,122122.0,122839.0,123156.0,123520.0,123766.0,124127.0,124530.0
4,394514,4,"Dallas-Fort Worth, TX",Msa,TX,83372.0,83445.0,83482.0,83617.0,83773.0,83922.0,84093.0,84357.0,84662.0,84988.0,85299.0,85663.0,85835.0,85626.0,85465.0,85442.0,85651.0,85721.0,85800.0,86041.0,86234.0,86384.0,86432.0,86524.0,86604.0,86804.0,87061.0,87437.0,87779.0,88286.0,88730.0,89196.0,89526.0,89845.0,90137.0,90408.0,90641.0,90800.0,91004.0,91177.0,91316.0,91458.0,91542.0,91710.0,91878.0,92108.0,92293.0,92309.0,92861.0,93882.0,NaN,96880.0,97644.0,97946.0,98092.0,98416.0,98693.0,98962.0,99140.0,99283.0,99869.0,100172.0,100503.0,100639.0,101014.0,101386.0,101599.0,101829.0,102072.0,102066.0,102140.0,102044.0,102097.0,102308.0,102578.0,103008.0,103453.0,103862.0,104073.0,104130.0,104306.0,104875.0,105237.0,105617.0,105407.0,105150.0,104869.0,105080.0,105458.0,105782.0,106030.0,106307.0,106719.0,106933.0,107053.0,107139.0,106461.0,105582.0,104518.0,104122.0,103791.0,103523.0,103363.0,102875.0,102141.0,101231.0,100497.0,100048.0,99635.0,99656.0,99702.0,99950.0,100087.0,100054.0,100056.0,99801.0,99698.0,99568.0,99904.0,100145.0,100067.0,99846.0,99624.0,99828.0,99912.0,99985.0,99611.0,98985.0,98154.0,97483.0,96882.0,96580.0,96248.0,95817.0,95403.0,94896.0,94574.0,94128.0,94010.0,93812.0,93796.0,93665.0,93592.0,93304.0,93035.0,93202.0,93490.0,93838.0,94092.0,94450.0,95004.0,95293.0,95536.0,95723.0,96154.0,96566.0,96969.0,97292.0,97815.0,98484.0,99248.0,100063.0,100899.0,101598.0,102389.0,103264.0,104268.0,105138.0,105671.0,106259.0,106813.0,107510.0,108239.0,109105.0,109616.0,110158.0,110598.0,111454.0,112459.0,113519.0

In [ ]:
data_1.shape

(908, 185)

In [ ]:
data_1.isnull().sum()

RegionID       0
SizeRank       0
RegionName     0
RegionType     0
StateName      1
              ..
2014-08-31    36
2014-09-30    33
2014-10-31    36
2014-11-30    36
2014-12-31    35
Length: 185, dtype: int64

In [ ]:
data_1['RegionName']

0                           United States
1                            New York, NY
2      Los Angeles-Long Beach-Anaheim, CA
3                             Chicago, IL
4                   Dallas-Fort Worth, TX
                      ...
903                            Lamesa, TX
904                             Craig, CO
905                             Pecos, TX
906                            Vernon, TX
907                         Ketchikan, AK
Name: RegionName, Length: 908, dtype: object

Splitting Region Name

In [ ]:
new = data_1["RegionName"].str.split(", ", n = 1, expand = True)
 
# making separate first name column from new data frame
data_1["City "]= new[0]
 
# making separate last name column from new data frame
data_1["State"]= new[1]
 
# Dropping old Name columns
data_1.drop(columns =["RegionName"], inplace = True)

data_1.head()

,RegionID,SizeRank,RegionType,StateName,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,2000-06-30,2000-07-31,2000-08-31,2000-09-30,2000-10-31,2000-11-30,2000-12-31,2001-01-31,2001-02-28,2001-03-31,2001-04-30,2001-05-31,2001-06-30,2001-07-31,2001-08-31,2001-09-30,2001-10-31,2001-11-30,2001-12-31,2002-01-31,2002-02-28,2002-03-31,2002-04-30,2002-05-31,2002-06-30,2002-07-31,2002-08-31,2002-09-30,2002-10-31,2002-11-30,2002-12-31,2003-01-31,2003-02-28,2003-03-31,2003-04-30,2003-05-31,2003-06-30,2003-07-31,2003-08-31,2003-09-30,2003-10-31,2003-11-30,2003-12-31,2004-01-31,2004-02-29,2004-03-31,2004-04-30,2004-05-31,2004-06-30,2004-07-31,2004-08-31,2004-09-30,2004-10-31,2004-11-30,2004-12-31,2005-01-31,2005-02-28,2005-03-31,2005-04-30,2005-05-31,2005-06-30,2005-07-31,2005-08-31,2005-09-30,2005-10-31,2005-11-30,2005-12-31,2006-01-31,2006-02-28,2006-03-31,2006-04-30,2006-05-31,2006-06-30,2006-07-31,2006-08-31,2006-09-30,2006-10-31,2006-11-30,2006-12-31,2007-01-31,2007-02-28,2007-03-31,2007-04-30,2007-05-31,2007-06-30,2007-07-31,2007-08-31,2007-09-30,2007-10-31,2007-11-30,2007-12-31,2008-01-31,2008-02-29,2008-03-31,2008-04-30,2008-05-31,2008-06-30,2008-07-31,2008-08-31,2008-09-30,2008-10-31,2008-11-30,2008-12-31,2009-01-31,2009-02-28,2009-03-31,2009-04-30,2009-05-31,2009-06-30,2009-07-31,2009-08-31,2009-09-30,2009-10-31,2009-11-30,2009-12-31,2010-01-31,2010-02-28,2010-03-31,2010-04-30,2010-05-31,2010-06-30,2010-07-31,2010-08-31,2010-09-30,2010-10-31,2010-11-30,2010-12-31,2011-01-31,2011-02-28,2011-03-31,2011-04-30,2011-05-31,2011-06-30,2011-07-31,2011-08-31,2011-09-30,2011-10-31,2011-11-30,2011-12-31,2012-01-31,2012-02-29,2012-03-31,2012-04-30,2012-05-31,2012-06-30,2012-07-31,2012-08-31,2012-09-30,2012-10-31,2012-11-30,2012-12-31,2013-01-31,2013-02-28,2013-03-31,2013-04-30,2013-05-31,2013-06-30,2013-07-31,2013-08-31,2013-09-30,2013-10-31,2013-11-30,2013-12-31,2014-01-31,2014-02-28,2014-03-31,2014-04-30,2014-05-31,2014-06-30,2014-07-31,2014-08-31,2014-09-30,2014-10-31,2014-11-30,2014-12-31,City,State
0,102001,0,Country,NaN,65636.0,65812.0,65991.0,66360.0,66726.0,67091.0,67455.0,67841.0,68237.0,68636.0,69054.0,69489.0,69903.0,70271.0,70638.0,71024.0,71427.0,71813.0,72202.0,72603.0,73004.0,73406.0,73771.0,74118.0,74437.0,74779.0,75143.0,75529.0,75935.0,76359.0,76817.0,77291.0,77764.0,78242.0,78700.0,79155.0,79570.0,79998.0,80435.0,80904.0,81395.0,81885.0,82391.0,82933.0,83506.0,84078.0,84584.0,85068.0,85563.0,86149.0,86806.0,87503.0,88252.0,89032.0,89857.0,90660.0,91451.0,92206.0,92919.0,93635.0,94349.0,95092.0,95851.0,96694.0,97562.0,98458.0,99336.0,100208.0,101050.0,101832.0,102537.0,103174.0,103720.0,104254.0,104801.0,105382.0,105938.0,106419.0,106794.0,107102.0,107322.0,107526.0,107663.0,107787.0,107866.0,107947.0,108007.0,108075.0,108064.0,107982.0,107794.0,107617.0,107383.0,107129.0,106794.0,106450.0,106014.0,105521.0,104964.0,104377.0,103771.0,103119.0,102409.0,101580.0,100753.0,99948.0,99134.0,98301.0,97463.0,96792.0,96161.0,95572.0,94960.0,94374.0,93835.0,93294.0,92795.0,92405.0,92227.0,92144.0,92083.0,91996.0,91983.0,92065.0,92107.0,92010.0,91665.0,91198.0,90629.0,90067.0,89478.0,88936.0,88404.0,87929.0,87484.0,87024.0,86550.0,86105.0,85766.0,85475.0,85223.0,84956.0,84734.0,84526.0,84396.0,84328.0,84410.0,84584.0,84841.0,85090.0,85355.0,85606.0,85869.0,86164.0,86510.0,86904.0,87372.0,87901.0,88503.0,89131.0,89796.0,90474.0,91150.0,91784.0,92383.0,92957.0,93491.0,94004.0,94499.0,95007.0,95435.0,95815.0,96179.0,96553.0,96889.0,97134.0,97372.0,97656.0,98013.0,98401.0,United States,None
1,394913,1,Msa,NY,140565.0,141355.0,142038.0,143419.0,144711.0,146087.0,147558.0,149094.0,150695.0,152250.0,153735.0,155134.0,156492.0,158013.0,159501.0,161071.0,162557.0,164188.0,165808.0,167563.0,169338.0,171268.0,172999.0,174667.0,176375.0,178152.0,179936.0,181665.0,183458.0,185434.0,187566.0,190197.0,192994.0,195830.0,198326.0,200715.0,203081.0,205559.0,208296.0,210887.0,213493.0,216013.0,218730.0,221432.0,223877.0,226111.0,228123.0,230100.0,232260.0,234450.0,236812.0,239221.0,242049.0,245078.0,248305.0,251487.0,254848.0,258163.0,261372.0,264294.0,267136.0,269863.0,272757.0,276178.0,279876.0,283517.0,286903.0,290296.0,293632.0,296998.0,300043.0,303040.0,305548.0,308116.0,310256.0,312414.0,314276.0,316088.0,317223.0,317726.0,317585.0,316979.0,316121.0,315083.0,314079.0,313416.0,313399.0,313486.0,313407.0,312516.0,311255.0,309965.0,308679.0,307774.0,306755.0,305740.0,304966.0,304257.0,303204.0,301711.0,299431.0,297262.0,295004.0,292929.0,290714.0,288234.0,285756.0,283547.0,281340.0,279182.0,276980.0,274747.0,272861.0,270948.0,269177.0,267364.0,265955.0,264875.0,264140.0,263745.0,263667.0,263874.0,263746.0,263638.0,263409.0,263524.0,263514.0,263167.0,262388.0,261172.0,259777.0,258353.0,257383.0,256582.0,256022.0,255106.0,254168.0,252880.0,251590.0,250365.0,249200.0,248110.0,246850.0,245730.0,244745.0,243824.0,243077.0,242389.0,242071.0,241872.0,241618.0,241246.0,240910.0,240691.0,240776.0,241061.0,241576.0,242246.0,242943.0,243850.0,244876.0,246095.0,247325.0,248455.0,249489.0,250657.0,251913.0,253021.0,254211.0,255153.0,256429.0,257583.0,258802.0,259674.0,260168.0,260548.0,260863.0,261213.0,261389.0,261752.0,New York,NY
2,753899,2,Msa,CA,150920.0,151319.0,152080.0,153511.0,155108.0,156605.0,158164.0,159847.0,161438.0,162836.0,164145.0,165494.0,166475.0,167478.0,168613.0,170297.0,171974.0,173593.0,175279.0,177087.0,178842.0,180608.0,182151.0,183834.0,185173.0,186730.0,188583.0,190975.0,193649.0,196322.0,199730.0,203310.0,207056.0,210411.0,213755.0,216996.0,219636.0,222044.0,224814.0,227864.0,231717.0,234771.0,238957.0,243309.0,248336.0,252331.0,256219.0,260257.0,265016.0,270074.0,275589.0,282138.0,290301.0,298337.0,305552.0,311807.0,318709.0,325497.0,330193.0,334628.0,338381.0,343825.0,349283.0,355067.0,360298.0,365678.0,371820.0,378407.0,385020.0,392012.0,396868.0,401643.0,405696.0,409534.0,413257.0,416338.0,420559.0,423902.0,425718.0,427340.0,426680.0,427145.0,427026.0,427975.0,428568.0,428672.0,428078.0,427424.0,425549.0,423674.0,419889.0,415782.0,410823.0,405741.0,401730.0,396907.0,392906.0,386901.0,379560.0,369575.0,358983.0,349295.0,339892.0,331251.0,324589.0,318326.0,311855.0,303553.0,297519.0,293759.0,291081.0,288025.0,284985.0,281403.0,278748.0,277029.0,276377.0,276126.0,277230.0,280015.0,281075.0,280622.0,280856.0,282790.0,285548.0,285100.0,283631.0,280601.0,278174.0,275837.0,273680.0,273052.0,272686.0,273154.0,272087.0,271149.0,268032.0,267477.0,266712.0,265629.0,262882.0,260321.0,260016.0,260089.0,259790.0,259388.0,259037.0,259422.0,260208.0,261476.0,263213.0,264571.0,266093.0,268691.0,271650.0,276172.0,280271.0,286429.0,292436.0,299264.0,304917.0,310947.0,316455.0,322443.0,327403.0,331322.0,335374.0,338933.0,343157.0,345159.0,346471.0,346336.0,346964.0,347417.0,348356.0,347823.0,347893.0,348699.0,351000.0,353667.0,Los Angeles-Long Beach-Anaheim,CA
3,394463,3,Msa,IL,106839.0,107099.0,107422.0,108061.0,108714.0,109349.0,110033.0,110844.0,111711.0,112603.0,113395.0,114149.0,114839.0,115449.0,116144.0,116857.0,117708.0,118480.0,119223.0,120012.0,120814.0,121678.0,122358.0,122963.0,123473.0,124099.0,124845.0,125464.0,126156.0,126779.0,127626.0,128500.0,129379.0,130210.0,130783.0,131458.0,132075.0,132855.0,133558.0,134374.0,135082.0,135716.0,136278.0,137001.0,137867.0,138713.0,139431.0,140067.0,140863.0,141650.0,142439.0,143292.0,144230.0,145326.0,146330.0,147362.0,148239.0,149169.0,150083.0,151084.0,152030.0,153070.0,154120.0,155288.0,156454.0,157652.0,158752.0,159823.0,160949.0,162034.0,162967.0,163856.0,164710.0,165568.0,166425.0,167182.0,168013.0,168534.0,169014.0,169386.0,169723.0,169921.0,170081.0,170341.0,170773.0,171177.0,171467.0,171551.0,171485.0,171307.0,171016.0,170743.0,170240.0,169779.0,169298.0,168708.0,168061.0,NaN,NaN,164779.0,NaN,163207.0,162668.0,160627.0,159397.0,157199.0,155492.0,153147.0,150508.0,148631.0,146696.0,145866.0,144398.0,143369.0,142250.0,141201.0,139514.0,138017.0,136653.0,136228.0,135528.0,135290.0,134386.0,134782.0,134376.0,134842.0,133286.0,132374.0,130651.0,129513.0,127566.0,125853.0,124239.0,123000.0,122178.0,121095.0,120521.0,119500.0,119146.0,118233.0,117419.0,115771.0,114770.0,113265.0,112502.0,111089.0,110844.0,110460.0,110540.0,110294.0,109677.0,109052.0,108383.0,108517.0,108678.0,108755.0,109103.0,109671.0,110207.0,110940.0,111669.0,112923.0,113930.0,115153.0,116082.0,117400.0,117975.0,118788.0,119166.0,119994.0,120454.0,120795.0,121319.0,122122.0,122839.0,123156.0,123520.0,123766.0,124127.0,124530.0,Chicago,IL
4,394514,4,Msa,TX,83372.0,83445.0,83482.0,83617.0,83773.0,83922.0,84093.0,84357.0,84662.0,84988.0,85299.0,85663.0,85835.0,85626.0,85465.0,85442.0,85651.0,85721.0,85800.0,86041.0,86234.0,86384.0,86432.0,86524.0,86604.0,86804.0,87061.0,87437.0,87779.0,88286.0,88730.0,89196.0,89526.0,89845.0,90137.0,90408.0,90641.0,90800.0,91004.0,91177.0,91316.0,91458.0,91542.0,91710.0,91878.0,92108.0,92293.0,92309.0,92861.0,93882.0,NaN,96880.0,97644.0,97946.0,98092.0,98416.0,98693.0,98962.0,99140.0,99283.0,99869.0,100172.0,100503.0,100639.0,101014.0,101386.0,101599.0,101829.0,102072.0,102066.0,102140.0,102044.0,102097.0,102308.0,102578.0,103008.0,103453.0,103862.0,104073.0,104130.0,104306.0,104875.0,105237.0,105617.0,105407.0,105150.0,104869.0,105080.0,105458.0,105782.0,106030.0,106307.0,106719.0,106933.0,107053.0,107139.0,106461.0,105582.0,104518.0,104122.0,103791.0,103523.0,103363.0,102875.0,102141.0,101231.0,100497.0,100048.0,99635.0,99656.0,99702.0,99950.0,100087.0,100054.0,100056.0,99801.0,99698.0,99568.0,99904.0,100145.0,100067.0,99846.0,99624.0,99828.0,99912.0,99985.0,99611.0,98985.0,98154.0,97483.0,96882.0,96580.0,96248.0,95817.0,95403.0,94896.0,94574.0,94128.0,94010.0,93812.0,93796.0,93665.0,93592.0,93304.0,93035.0,93202.0,93490.0,93838.0,94092.0,94450.0,95004.0,95293.0,95536.0,95723.0,96154.0,96566.0,96969.0,97292.0,97815.0,98484.0,99248.0,100063.0,100899.0,101598.0,102389.0,103264.0,104268.0,105138.0,105671.0,106259.0,106813.0,107510.0,108239.0,109105.0,109616.0,110158.0,110598.0,111454.0,112459.0,113519.0,Dallas-Fort Worth,TX

In [ ]:
data_1=data_1.drop(data_1.index[0])

In [ ]:
data_1.head()

,RegionID,SizeRank,RegionType,StateName,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,2000-06-30,2000-07-31,2000-08-31,2000-09-30,2000-10-31,2000-11-30,2000-12-31,2001-01-31,2001-02-28,2001-03-31,2001-04-30,2001-05-31,2001-06-30,2001-07-31,2001-08-31,2001-09-30,2001-10-31,2001-11-30,2001-12-31,2002-01-31,2002-02-28,2002-03-31,2002-04-30,2002-05-31,2002-06-30,2002-07-31,2002-08-31,2002-09-30,2002-10-31,2002-11-30,2002-12-31,2003-01-31,2003-02-28,2003-03-31,2003-04-30,2003-05-31,2003-06-30,2003-07-31,2003-08-31,2003-09-30,2003-10-31,2003-11-30,2003-12-31,2004-01-31,2004-02-29,2004-03-31,2004-04-30,2004-05-31,2004-06-30,2004-07-31,2004-08-31,2004-09-30,2004-10-31,2004-11-30,2004-12-31,2005-01-31,2005-02-28,2005-03-31,2005-04-30,2005-05-31,2005-06-30,2005-07-31,2005-08-31,2005-09-30,2005-10-31,2005-11-30,2005-12-31,2006-01-31,2006-02-28,2006-03-31,2006-04-30,2006-05-31,2006-06-30,2006-07-31,2006-08-31,2006-09-30,2006-10-31,2006-11-30,2006-12-31,2007-01-31,2007-02-28,2007-03-31,2007-04-30,2007-05-31,2007-06-30,2007-07-31,2007-08-31,2007-09-30,2007-10-31,2007-11-30,2007-12-31,2008-01-31,2008-02-29,2008-03-31,2008-04-30,2008-05-31,2008-06-30,2008-07-31,2008-08-31,2008-09-30,2008-10-31,2008-11-30,2008-12-31,2009-01-31,2009-02-28,2009-03-31,2009-04-30,2009-05-31,2009-06-30,2009-07-31,2009-08-31,2009-09-30,2009-10-31,2009-11-30,2009-12-31,2010-01-31,2010-02-28,2010-03-31,2010-04-30,2010-05-31,2010-06-30,2010-07-31,2010-08-31,2010-09-30,2010-10-31,2010-11-30,2010-12-31,2011-01-31,2011-02-28,2011-03-31,2011-04-30,2011-05-31,2011-06-30,2011-07-31,2011-08-31,2011-09-30,2011-10-31,2011-11-30,2011-12-31,2012-01-31,2012-02-29,2012-03-31,2012-04-30,2012-05-31,2012-06-30,2012-07-31,2012-08-31,2012-09-30,2012-10-31,2012-11-30,2012-12-31,2013-01-31,2013-02-28,2013-03-31,2013-04-30,2013-05-31,2013-06-30,2013-07-31,2013-08-31,2013-09-30,2013-10-31,2013-11-30,2013-12-31,2014-01-31,2014-02-28,2014-03-31,2014-04-30,2014-05-31,2014-06-30,2014-07-31,2014-08-31,2014-09-30,2014-10-31,2014-11-30,2014-12-31,City,State
1,394913,1,Msa,NY,140565.0,141355.0,142038.0,143419.0,144711.0,146087.0,147558.0,149094.0,150695.0,152250.0,153735.0,155134.0,156492.0,158013.0,159501.0,161071.0,162557.0,164188.0,165808.0,167563.0,169338.0,171268.0,172999.0,174667.0,176375.0,178152.0,179936.0,181665.0,183458.0,185434.0,187566.0,190197.0,192994.0,195830.0,198326.0,200715.0,203081.0,205559.0,208296.0,210887.0,213493.0,216013.0,218730.0,221432.0,223877.0,226111.0,228123.0,230100.0,232260.0,234450.0,236812.0,239221.0,242049.0,245078.0,248305.0,251487.0,254848.0,258163.0,261372.0,264294.0,267136.0,269863.0,272757.0,276178.0,279876.0,283517.0,286903.0,290296.0,293632.0,296998.0,300043.0,303040.0,305548.0,308116.0,310256.0,312414.0,314276.0,316088.0,317223.0,317726.0,317585.0,316979.0,316121.0,315083.0,314079.0,313416.0,313399.0,313486.0,313407.0,312516.0,311255.0,309965.0,308679.0,307774.0,306755.0,305740.0,304966.0,304257.0,303204.0,301711.0,299431.0,297262.0,295004.0,292929.0,290714.0,288234.0,285756.0,283547.0,281340.0,279182.0,276980.0,274747.0,272861.0,270948.0,269177.0,267364.0,265955.0,264875.0,264140.0,263745.0,263667.0,263874.0,263746.0,263638.0,263409.0,263524.0,263514.0,263167.0,262388.0,261172.0,259777.0,258353.0,257383.0,256582.0,256022.0,255106.0,254168.0,252880.0,251590.0,250365.0,249200.0,248110.0,246850.0,245730.0,244745.0,243824.0,243077.0,242389.0,242071.0,241872.0,241618.0,241246.0,240910.0,240691.0,240776.0,241061.0,241576.0,242246.0,242943.0,243850.0,244876.0,246095.0,247325.0,248455.0,249489.0,250657.0,251913.0,253021.0,254211.0,255153.0,256429.0,257583.0,258802.0,259674.0,260168.0,260548.0,260863.0,261213.0,261389.0,261752.0,New York,NY
2,753899,2,Msa,CA,150920.0,151319.0,152080.0,153511.0,155108.0,156605.0,158164.0,159847.0,161438.0,162836.0,164145.0,165494.0,166475.0,167478.0,168613.0,170297.0,171974.0,173593.0,175279.0,177087.0,178842.0,180608.0,182151.0,183834.0,185173.0,186730.0,188583.0,190975.0,193649.0,196322.0,199730.0,203310.0,207056.0,210411.0,213755.0,216996.0,219636.0,222044.0,224814.0,227864.0,231717.0,234771.0,238957.0,243309.0,248336.0,252331.0,256219.0,260257.0,265016.0,270074.0,275589.0,282138.0,290301.0,298337.0,305552.0,311807.0,318709.0,325497.0,330193.0,334628.0,338381.0,343825.0,349283.0,355067.0,360298.0,365678.0,371820.0,378407.0,385020.0,392012.0,396868.0,401643.0,405696.0,409534.0,413257.0,416338.0,420559.0,423902.0,425718.0,427340.0,426680.0,427145.0,427026.0,427975.0,428568.0,428672.0,428078.0,427424.0,425549.0,423674.0,419889.0,415782.0,410823.0,405741.0,401730.0,396907.0,392906.0,386901.0,379560.0,369575.0,358983.0,349295.0,339892.0,331251.0,324589.0,318326.0,311855.0,303553.0,297519.0,293759.0,291081.0,288025.0,284985.0,281403.0,278748.0,277029.0,276377.0,276126.0,277230.0,280015.0,281075.0,280622.0,280856.0,282790.0,285548.0,285100.0,283631.0,280601.0,278174.0,275837.0,273680.0,273052.0,272686.0,273154.0,272087.0,271149.0,268032.0,267477.0,266712.0,265629.0,262882.0,260321.0,260016.0,260089.0,259790.0,259388.0,259037.0,259422.0,260208.0,261476.0,263213.0,264571.0,266093.0,268691.0,271650.0,276172.0,280271.0,286429.0,292436.0,299264.0,304917.0,310947.0,316455.0,322443.0,327403.0,331322.0,335374.0,338933.0,343157.0,345159.0,346471.0,346336.0,346964.0,347417.0,348356.0,347823.0,347893.0,348699.0,351000.0,353667.0,Los Angeles-Long Beach-Anaheim,CA
3,394463,3,Msa,IL,106839.0,107099.0,107422.0,108061.0,108714.0,109349.0,110033.0,110844.0,111711.0,112603.0,113395.0,114149.0,114839.0,115449.0,116144.0,116857.0,117708.0,118480.0,119223.0,120012.0,120814.0,121678.0,122358.0,122963.0,123473.0,124099.0,124845.0,125464.0,126156.0,126779.0,127626.0,128500.0,129379.0,130210.0,130783.0,131458.0,132075.0,132855.0,133558.0,134374.0,135082.0,135716.0,136278.0,137001.0,137867.0,138713.0,139431.0,140067.0,140863.0,141650.0,142439.0,143292.0,144230.0,145326.0,146330.0,147362.0,148239.0,149169.0,150083.0,151084.0,152030.0,153070.0,154120.0,155288.0,156454.0,157652.0,158752.0,159823.0,160949.0,162034.0,162967.0,163856.0,164710.0,165568.0,166425.0,167182.0,168013.0,168534.0,169014.0,169386.0,169723.0,169921.0,170081.0,170341.0,170773.0,171177.0,171467.0,171551.0,171485.0,171307.0,171016.0,170743.0,170240.0,169779.0,169298.0,168708.0,168061.0,NaN,NaN,164779.0,NaN,163207.0,162668.0,160627.0,159397.0,157199.0,155492.0,153147.0,150508.0,148631.0,146696.0,145866.0,144398.0,143369.0,142250.0,141201.0,139514.0,138017.0,136653.0,136228.0,135528.0,135290.0,134386.0,134782.0,134376.0,134842.0,133286.0,132374.0,130651.0,129513.0,127566.0,125853.0,124239.0,123000.0,122178.0,121095.0,120521.0,119500.0,119146.0,118233.0,117419.0,115771.0,114770.0,113265.0,112502.0,111089.0,110844.0,110460.0,110540.0,110294.0,109677.0,109052.0,108383.0,108517.0,108678.0,108755.0,109103.0,109671.0,110207.0,110940.0,111669.0,112923.0,113930.0,115153.0,116082.0,117400.0,117975.0,118788.0,119166.0,119994.0,120454.0,120795.0,121319.0,122122.0,122839.0,123156.0,123520.0,123766.0,124127.0,124530.0,Chicago,IL
4,394514,4,Msa,TX,83372.0,83445.0,83482.0,83617.0,83773.0,83922.0,84093.0,84357.0,84662.0,84988.0,85299.0,85663.0,85835.0,85626.0,85465.0,85442.0,85651.0,85721.0,85800.0,86041.0,86234.0,86384.0,86432.0,86524.0,86604.0,86804.0,87061.0,87437.0,87779.0,88286.0,88730.0,89196.0,89526.0,89845.0,90137.0,90408.0,90641.0,90800.0,91004.0,91177.0,91316.0,91458.0,91542.0,91710.0,91878.0,92108.0,92293.0,92309.0,92861.0,93882.0,NaN,96880.0,97644.0,97946.0,98092.0,98416.0,98693.0,98962.0,99140.0,99283.0,99869.0,100172.0,100503.0,100639.0,101014.0,101386.0,101599.0,101829.0,102072.0,102066.0,102140.0,102044.0,102097.0,102308.0,102578.0,103008.0,103453.0,103862.0,104073.0,104130.0,104306.0,104875.0,105237.0,105617.0,105407.0,105150.0,104869.0,105080.0,105458.0,105782.0,106030.0,106307.0,106719.0,106933.0,107053.0,107139.0,106461.0,105582.0,104518.0,104122.0,103791.0,103523.0,103363.0,102875.0,102141.0,101231.0,100497.0,100048.0,99635.0,99656.0,99702.0,99950.0,100087.0,100054.0,100056.0,99801.0,99698.0,99568.0,99904.0,100145.0,100067.0,99846.0,99624.0,99828.0,99912.0,99985.0,99611.0,98985.0,98154.0,97483.0,96882.0,96580.0,96248.0,95817.0,95403.0,94896.0,94574.0,94128.0,94010.0,93812.0,93796.0,93665.0,93592.0,93304.0,93035.0,93202.0,93490.0,93838.0,94092.0,94450.0,95004.0,95293.0,95536.0,95723.0,96154.0,96566.0,96969.0,97292.0,97815.0,98484.0,99248.0,100063.0,100899.0,101598.0,102389.0,103264.0,104268.0,105138.0,105671.0,106259.0,106813.0,107510.0,108239.0,109105.0,109616.0,110158.0,110598.0,111454.0,112459.0,113519.0,Dallas-Fort Worth,TX
5,394974,5,Msa,PA,75530.0,75779.0,75940.0,76326.0,76676.0,77033.0,77376.0,77688.0,78051.0,78400.0,78742.0,79054.0,79378.0,79746.0,80167.0,80613.0,81018.0,81436.0,81903.0,82421.0,82964.0,83459.0,83981.0,84402.0,84832.0,85256.0,85787.0,86373.0,86957.0,87616.0,88342.0,89231.0,90178.0,91114.0,91917.0,92726.0,93495.0,94304.0,95050.0,95918.0,96860.0,97921.0,99088.0,100325.0,101582.0,102686.0,103718.0,104610.0,105496.0,106387.0,107329.0,108367.0,109623.0,111144.0,112925.0,114854.0,116540.0,117892.0,119027.0,120330.0,121815.0,123058.0,124267.0,125506.0,127175.0,129034.0,131049.0,133002.0,134807.0,136514.0,138022.0,139442.0,140501.0,141506.0,142440.0,143614.0,144835.0,146092.0,147165.0,147912.0,148358.0,148612.0,148747.0,148857.0,148964.0,149178.0,149633.0,150043.0,150675.0,151067.0,151401.0,151286.0,150982.0,150832.0,150704.0,150567.0,150074.0,150000.0,149885.0,149929.0,149417.0,148720.0,147690.0,146636.0,145572.0,144682.0,143820.0,142924.0,141922.0,141189.0,140857.0,140734.0,140437.0,139926.0,139281.0,138737.0,138253.0,138033.0,138024.0,138018.0,138170.0,138227.0,138397.0,138547.0,138752.0,138865.0,138579.0,137822.0,136574.0,135264.0,134046.0,133096.0,132361.0,131876.0,131601.0,131018.0,130165.0,129002.0,127967.0,127068.0,126380.0,125799.0,125289.0,124821.0,124324.0,123821.0,123589.0,123492.0,123373.0,122982.0,122519.0,122067.0,121779.0,121509.0,121370.0,121246.0,121294.0,121356.0,121575.0,121883.0,122416.0,122968.0,123422.0,123673.0,123880.0,124102.0,124430.0,124686.0,125030.0,125325.0,125536.0,125455.0,125445.0,125483.0,125642.0,125619.0,125583.0,125556.0,125647.0,125837.0,Philadelphia,PA

In [ ]:
data_1['house_type']='Condo'
data_1['cost_percentile_range']='lower' #lower is < 33% percentile
data_1.head()

,RegionID,SizeRank,RegionType,StateName,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,2000-06-30,2000-07-31,2000-08-31,2000-09-30,2000-10-31,2000-11-30,2000-12-31,2001-01-31,2001-02-28,2001-03-31,2001-04-30,2001-05-31,2001-06-30,2001-07-31,2001-08-31,2001-09-30,2001-10-31,2001-11-30,2001-12-31,2002-01-31,2002-02-28,2002-03-31,2002-04-30,2002-05-31,2002-06-30,2002-07-31,2002-08-31,2002-09-30,2002-10-31,2002-11-30,2002-12-31,2003-01-31,2003-02-28,2003-03-31,2003-04-30,2003-05-31,2003-06-30,2003-07-31,2003-08-31,2003-09-30,2003-10-31,2003-11-30,2003-12-31,2004-01-31,2004-02-29,2004-03-31,2004-04-30,2004-05-31,2004-06-30,2004-07-31,2004-08-31,2004-09-30,2004-10-31,2004-11-30,2004-12-31,2005-01-31,2005-02-28,2005-03-31,2005-04-30,2005-05-31,2005-06-30,2005-07-31,2005-08-31,2005-09-30,2005-10-31,2005-11-30,2005-12-31,2006-01-31,2006-02-28,2006-03-31,2006-04-30,2006-05-31,2006-06-30,2006-07-31,2006-08-31,2006-09-30,2006-10-31,2006-11-30,2006-12-31,2007-01-31,2007-02-28,2007-03-31,2007-04-30,2007-05-31,2007-06-30,2007-07-31,2007-08-31,2007-09-30,2007-10-31,2007-11-30,2007-12-31,2008-01-31,2008-02-29,2008-03-31,2008-04-30,2008-05-31,2008-06-30,2008-07-31,2008-08-31,2008-09-30,2008-10-31,2008-11-30,2008-12-31,2009-01-31,2009-02-28,2009-03-31,2009-04-30,2009-05-31,2009-06-30,2009-07-31,2009-08-31,2009-09-30,2009-10-31,2009-11-30,2009-12-31,2010-01-31,2010-02-28,2010-03-31,2010-04-30,2010-05-31,2010-06-30,2010-07-31,2010-08-31,2010-09-30,2010-10-31,2010-11-30,2010-12-31,2011-01-31,2011-02-28,2011-03-31,2011-04-30,2011-05-31,2011-06-30,2011-07-31,2011-08-31,2011-09-30,2011-10-31,2011-11-30,2011-12-31,2012-01-31,2012-02-29,2012-03-31,2012-04-30,2012-05-31,2012-06-30,2012-07-31,2012-08-31,2012-09-30,2012-10-31,2012-11-30,2012-12-31,2013-01-31,2013-02-28,2013-03-31,2013-04-30,2013-05-31,2013-06-30,2013-07-31,2013-08-31,2013-09-30,2013-10-31,2013-11-30,2013-12-31,2014-01-31,2014-02-28,2014-03-31,2014-04-30,2014-05-31,2014-06-30,2014-07-31,2014-08-31,2014-09-30,2014-10-31,2014-11-30,2014-12-31,City,State,house_type,cost_percentile_range
1,394913,1,Msa,NY,140565.0,141355.0,142038.0,143419.0,144711.0,146087.0,147558.0,149094.0,150695.0,152250.0,153735.0,155134.0,156492.0,158013.0,159501.0,161071.0,162557.0,164188.0,165808.0,167563.0,169338.0,171268.0,172999.0,174667.0,176375.0,178152.0,179936.0,181665.0,183458.0,185434.0,187566.0,190197.0,192994.0,195830.0,198326.0,200715.0,203081.0,205559.0,208296.0,210887.0,213493.0,216013.0,218730.0,221432.0,223877.0,226111.0,228123.0,230100.0,232260.0,234450.0,236812.0,239221.0,242049.0,245078.0,248305.0,251487.0,254848.0,258163.0,261372.0,264294.0,267136.0,269863.0,272757.0,276178.0,279876.0,283517.0,286903.0,290296.0,293632.0,296998.0,300043.0,303040.0,305548.0,308116.0,310256.0,312414.0,314276.0,316088.0,317223.0,317726.0,317585.0,316979.0,316121.0,315083.0,314079.0,313416.0,313399.0,313486.0,313407.0,312516.0,311255.0,309965.0,308679.0,307774.0,306755.0,305740.0,304966.0,304257.0,303204.0,301711.0,299431.0,297262.0,295004.0,292929.0,290714.0,288234.0,285756.0,283547.0,281340.0,279182.0,276980.0,274747.0,272861.0,270948.0,269177.0,267364.0,265955.0,264875.0,264140.0,263745.0,263667.0,263874.0,263746.0,263638.0,263409.0,263524.0,263514.0,263167.0,262388.0,261172.0,259777.0,258353.0,257383.0,256582.0,256022.0,255106.0,254168.0,252880.0,251590.0,250365.0,249200.0,248110.0,246850.0,245730.0,244745.0,243824.0,243077.0,242389.0,242071.0,241872.0,241618.0,241246.0,240910.0,240691.0,240776.0,241061.0,241576.0,242246.0,242943.0,243850.0,244876.0,246095.0,247325.0,248455.0,249489.0,250657.0,251913.0,253021.0,254211.0,255153.0,256429.0,257583.0,258802.0,259674.0,260168.0,260548.0,260863.0,261213.0,261389.0,261752.0,New York,NY,Condo,lower
2,753899,2,Msa,CA,150920.0,151319.0,152080.0,153511.0,155108.0,156605.0,158164.0,159847.0,161438.0,162836.0,164145.0,165494.0,166475.0,167478.0,168613.0,170297.0,171974.0,173593.0,175279.0,177087.0,178842.0,180608.0,182151.0,183834.0,185173.0,186730.0,188583.0,190975.0,193649.0,196322.0,199730.0,203310.0,207056.0,210411.0,213755.0,216996.0,219636.0,222044.0,224814.0,227864.0,231717.0,234771.0,238957.0,243309.0,248336.0,252331.0,256219.0,260257.0,265016.0,270074.0,275589.0,282138.0,290301.0,298337.0,305552.0,311807.0,318709.0,325497.0,330193.0,334628.0,338381.0,343825.0,349283.0,355067.0,360298.0,365678.0,371820.0,378407.0,385020.0,392012.0,396868.0,401643.0,405696.0,409534.0,413257.0,416338.0,420559.0,423902.0,425718.0,427340.0,426680.0,427145.0,427026.0,427975.0,428568.0,428672.0,428078.0,427424.0,425549.0,423674.0,419889.0,415782.0,410823.0,405741.0,401730.0,396907.0,392906.0,386901.0,379560.0,369575.0,358983.0,349295.0,339892.0,331251.0,324589.0,318326.0,311855.0,303553.0,297519.0,293759.0,291081.0,288025.0,284985.0,281403.0,278748.0,277029.0,276377.0,276126.0,277230.0,280015.0,281075.0,280622.0,280856.0,282790.0,285548.0,285100.0,283631.0,280601.0,278174.0,275837.0,273680.0,273052.0,272686.0,273154.0,272087.0,271149.0,268032.0,267477.0,266712.0,265629.0,262882.0,260321.0,260016.0,260089.0,259790.0,259388.0,259037.0,259422.0,260208.0,261476.0,263213.0,264571.0,266093.0,268691.0,271650.0,276172.0,280271.0,286429.0,292436.0,299264.0,304917.0,310947.0,316455.0,322443.0,327403.0,331322.0,335374.0,338933.0,343157.0,345159.0,346471.0,346336.0,346964.0,347417.0,348356.0,347823.0,347893.0,348699.0,351000.0,353667.0,Los Angeles-Long Beach-Anaheim,CA,Condo,lower
3,394463,3,Msa,IL,106839.0,107099.0,107422.0,108061.0,108714.0,109349.0,110033.0,110844.0,111711.0,112603.0,113395.0,114149.0,114839.0,115449.0,116144.0,116857.0,117708.0,118480.0,119223.0,120012.0,120814.0,121678.0,122358.0,122963.0,123473.0,124099.0,124845.0,125464.0,126156.0,126779.0,127626.0,128500.0,129379.0,130210.0,130783.0,131458.0,132075.0,132855.0,133558.0,134374.0,135082.0,135716.0,136278.0,137001.0,137867.0,138713.0,139431.0,140067.0,140863.0,141650.0,142439.0,143292.0,144230.0,145326.0,146330.0,147362.0,148239.0,149169.0,150083.0,151084.0,152030.0,153070.0,154120.0,155288.0,156454.0,157652.0,158752.0,159823.0,160949.0,162034.0,162967.0,163856.0,164710.0,165568.0,166425.0,167182.0,168013.0,168534.0,169014.0,169386.0,169723.0,169921.0,170081.0,170341.0,170773.0,171177.0,171467.0,171551.0,171485.0,171307.0,171016.0,170743.0,170240.0,169779.0,169298.0,168708.0,168061.0,NaN,NaN,164779.0,NaN,163207.0,162668.0,160627.0,159397.0,157199.0,155492.0,153147.0,150508.0,148631.0,146696.0,145866.0,144398.0,143369.0,142250.0,141201.0,139514.0,138017.0,136653.0,136228.0,135528.0,135290.0,134386.0,134782.0,134376.0,134842.0,133286.0,132374.0,130651.0,129513.0,127566.0,125853.0,124239.0,123000.0,122178.0,121095.0,120521.0,119500.0,119146.0,118233.0,117419.0,115771.0,114770.0,113265.0,112502.0,111089.0,110844.0,110460.0,110540.0,110294.0,109677.0,109052.0,108383.0,108517.0,108678.0,108755.0,109103.0,109671.0,110207.0,110940.0,111669.0,112923.0,113930.0,115153.0,116082.0,117400.0,117975.0,118788.0,119166.0,119994.0,120454.0,120795.0,121319.0,122122.0,122839.0,123156.0,123520.0,123766.0,124127.0,124530.0,Chicago,IL,Condo,lower
4,394514,4,Msa,TX,83372.0,83445.0,83482.0,83617.0,83773.0,83922.0,84093.0,84357.0,84662.0,84988.0,85299.0,85663.0,85835.0,85626.0,85465.0,85442.0,85651.0,85721.0,85800.0,86041.0,86234.0,86384.0,86432.0,86524.0,86604.0,86804.0,87061.0,87437.0,87779.0,88286.0,88730.0,89196.0,89526.0,89845.0,90137.0,90408.0,90641.0,90800.0,91004.0,91177.0,91316.0,91458.0,91542.0,91710.0,91878.0,92108.0,92293.0,92309.0,92861.0,93882.0,NaN,96880.0,97644.0,97946.0,98092.0,98416.0,98693.0,98962.0,99140.0,99283.0,99869.0,100172.0,100503.0,100639.0,101014.0,101386.0,101599.0,101829.0,102072.0,102066.0,102140.0,102044.0,102097.0,102308.0,102578.0,103008.0,103453.0,103862.0,104073.0,104130.0,104306.0,104875.0,105237.0,105617.0,105407.0,105150.0,104869.0,105080.0,105458.0,105782.0,106030.0,106307.0,106719.0,106933.0,107053.0,107139.0,106461.0,105582.0,104518.0,104122.0,103791.0,103523.0,103363.0,102875.0,102141.0,101231.0,100497.0,100048.0,99635.0,99656.0,99702.0,99950.0,100087.0,100054.0,100056.0,99801.0,99698.0,99568.0,99904.0,100145.0,100067.0,99846.0,99624.0,99828.0,99912.0,99985.0,99611.0,98985.0,98154.0,97483.0,96882.0,96580.0,96248.0,95817.0,95403.0,94896.0,94574.0,94128.0,94010.0,93812.0,93796.0,93665.0,93592.0,93304.0,93035.0,93202.0,93490.0,93838.0,94092.0,94450.0,95004.0,95293.0,95536.0,95723.0,96154.0,96566.0,96969.0,97292.0,97815.0,98484.0,99248.0,100063.0,100899.0,101598.0,102389.0,103264.0,104268.0,105138.0,105671.0,106259.0,106813.0,107510.0,108239.0,109105.0,109616.0,110158.0,110598.0,111454.0,112459.0,113519.0,Dallas-Fort Worth,TX,Condo,lower
5,394974,5,Msa,PA,75530.0,75779.0,75940.0,76326.0,76676.0,77033.0,77376.0,77688.0,78051.0,78400.0,78742.0,79054.0,79378.0,79746.0,80167.0,80613.0,81018.0,81436.0,81903.0,82421.0,82964.0,83459.0,83981.0,84402.0,84832.0,85256.0,85787.0,86373.0,86957.0,87616.0,88342.0,89231.0,90178.0,91114.0,91917.0,92726.0,93495.0,94304.0,95050.0,95918.0,96860.0,97921.0,99088.0,100325.0,101582.0,102686.0,103718.0,104610.0,105496.0,106387.0,107329.0,108367.0,109623.0,111144.0,112925.0,114854.0,116540.0,117892.0,119027.0,120330.0,121815.0,123058.0,124267.0,125506.0,127175.0,129034.0,131049.0,133002.0,134807.0,136514.0,138022.0,139442.0,140501.0,141506.0,142440.0,143614.0,144835.0,146092.0,147165.0,147912.0,148358.0,148612.0,148747.0,148857.0,148964.0,149178.0,149633.0,150043.0,150675.0,151067.0,151401.0,151286.0,150982.0,150832.0,150704.0,150567.0,150074.0,150000.0,149885.0,149929.0,149417.0,148720.0,147690.0,146636.0,145572.0,144682.0,143820.0,142924.0,141922.0,141189.0,140857.0,140734.0,140437.0,139926.0,139281.0,138737.0,138253.0,138033.0,138024.0,138018.0,138170.0,138227.0,138397.0,138547.0,138752.0,138865.0,138579.0,137822.0,136574.0,135264.0,134046.0,133096.0,132361.0,131876.0,131601.0,131018.0,130165.0,129002.0,127967.0,127068.0,126380.0,125799.0,125289.0,124821.0,124324.0,123821.0,123589.0,123492.0,123373.0,122982.0,122519.0,122067.0,121779.0,121509.0,121370.0,121246.0,121294.0,121356.0,121575.0,121883.0,122416.0,122968.0,123422.0,123673.0,123880.0,124102.0,124430.0,124686.0,125030.0,125325.0,125536.0,125455.0,125445.0,125483.0,125642.0,125619.0,125583.0,125556.0,125647.0,125837.0,Philadelphia,PA,Condo,lower

In [ ]:
csv_file_2 = "/content/gdrive/My Drive/WWCode Python Workshop/Metro_zhvi_uc_sfrcondo_tier_0.33_0.67_month.csv"
data_2 = pd.read_csv(csv_file_2, sep=",", header='infer' )
data_2.head(10)

,RegionID,SizeRank,RegionName,RegionType,StateName,1996-01-31,1996-02-29,1996-03-31,1996-04-30,1996-05-31,1996-06-30,1996-07-31,1996-08-31,1996-09-30,1996-10-31,1996-11-30,1996-12-31,1997-01-31,1997-02-28,1997-03-31,1997-04-30,1997-05-31,1997-06-30,1997-07-31,1997-08-31,1997-09-30,1997-10-31,1997-11-30,1997-12-31,1998-01-31,1998-02-28,1998-03-31,1998-04-30,1998-05-31,1998-06-30,1998-07-31,1998-08-31,1998-09-30,1998-10-31,1998-11-30,1998-12-31,1999-01-31,1999-02-28,1999-03-31,1999-04-30,1999-05-31,1999-06-30,1999-07-31,1999-08-31,1999-09-30,1999-10-31,1999-11-30,1999-12-31,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,2000-06-30,2000-07-31,2000-08-31,2000-09-30,2000-10-31,2000-11-30,2000-12-31,2001-01-31,2001-02-28,2001-03-31,2001-04-30,2001-05-31,2001-06-30,2001-07-31,2001-08-31,2001-09-30,2001-10-31,2001-11-30,2001-12-31,2002-01-31,2002-02-28,2002-03-31,2002-04-30,2002-05-31,2002-06-30,2002-07-31,2002-08-31,2002-09-30,2002-10-31,2002-11-30,2002-12-31,2003-01-31,2003-02-28,2003-03-31,2003-04-30,2003-05-31,2003-06-30,2003-07-31,2003-08-31,2003-09-30,2003-10-31,2003-11-30,2003-12-31,2004-01-31,2004-02-29,2004-03-31,2004-04-30,2004-05-31,2004-06-30,2004-07-31,2004-08-31,2004-09-30,2004-10-31,2004-11-30,2004-12-31,2005-01-31,2005-02-28,2005-03-31,2005-04-30,2005-05-31,2005-06-30,2005-07-31,2005-08-31,2005-09-30,2005-10-31,2005-11-30,2005-12-31,2006-01-31,2006-02-28,2006-03-31,2006-04-30,2006-05-31,2006-06-30,2006-07-31,2006-08-31,2006-09-30,2006-10-31,2006-11-30,2006-12-31,2007-01-31,2007-02-28,2007-03-31,2007-04-30,2007-05-31,2007-06-30,2007-07-31,2007-08-31,2007-09-30,2007-10-31,2007-11-30,2007-12-31,2008-01-31,2008-02-29,2008-03-31,2008-04-30,2008-05-31,2008-06-30,2008-07-31,2008-08-31,2008-09-30,2008-10-31,2008-11-30,2008-12-31,2009-01-31,2009-02-28,2009-03-31,2009-04-30,2009-05-31,2009-06-30,2009-07-31,2009-08-31,2009-09-30,2009-10-31,2009-11-30,2009-12-31,2010-01-31,2010-02-28,2010-03-31,2010-04-30,2010-05-31,2010-06-30,2010-07-31,2010-08-31,2010-09-30,2010-10-31,2010-11-30,2010-12-31,2011-01-31,2011-02-28,2011-03-31,2011-04-30,2011-05-31,2011-06-30,2011-07-31,2011-08-31,2011-09-30,2011-10-31,2011-11-30,2011-12-31,2012-01-31,2012-02-29,2012-03-31,2012-04-30,2012-05-31,2012-06-30,2012-07-31,2012-08-31,2012-09-30,2012-10-31,2012-11-30,2012-12-31,2013-01-31,2013-02-28,2013-03-31,2013-04-30,2013-05-31,2013-06-30,2013-07-31,2013-08-31,2013-09-30,2013-10-31,2013-11-30,2013-12-31,2014-01-31,2014-02-28,2014-03-31,2014-04-30,2014-05-31,2014-06-30,2014-07-31,2014-08-31,2014-09-30,2014-10-31,2014-11-30,2014-12-31,2015-01-31,2015-02-28,2015-03-31,2015-04-30,2015-05-31,2015-06-30,2015-07-31,2015-08-31,2015-09-30,2015-10-31,2015-11-30,2015-12-31,2016-01-31,2016-02-29,2016-03-31,2016-04-30,2016-05-31,2016-06-30,2016-07-31,2016-08-31,2016-09-30,2016-10-31,2016-11-30,2016-12-31,2017-01-31,2017-02-28,2017-03-31,2017-04-30,2017-05-31,2017-06-30,2017-07-31,2017-08-31,2017-09-30,2017-10-31,2017-11-30,2017-12-31,2018-01-31,2018-02-28,2018-03-31,2018-04-30,2018-05-31,2018-06-30,2018-07-31,2018-08-31,2018-09-30,2018-10-31,2018-11-30,2018-12-31,2019-01-31,2019-02-28,2019-03-31,2019-04-30,2019-05-31,2019-06-30,2019-07-31,2019-08-31,2019-09-30,2019-10-31,2019-11-30,2019-12-31,2020-01-31,2020-02-29,2020-03-31,2020-04-30,2020-05-31,2020-06-30,2020-07-31,2020-08-31,2020-09-30,2020-10-31,2020-11-30,2020-12-31,2021-01-31,2021-02-28,2021-03-31,2021-04-30,2021-05-31,2021-06-30,2021-07-31,2021-08-31,2021-09-30,2021-10-31,2021-11-30,2021-12-31,2022-01-31,2022-02-28,2022-03-31,2022-04-30,2022-05-31,2022-06-30
0,102001,0,United States,Country,NaN,108612.869189,108444.377435,108503.913064,108710.656405,108958.135846,109173.415608,109352.881004,109649.156251,109844.272340,110088.619136,110319.573090,110549.894575,110785.419274,110983.302345,111261.582554,111539.835309,112053.249038,112374.957920,112734.531037,113026.290072,113344.827100,113518.526356,114021.712714,114385.531685,115328.108700,115553.525020,115877.577249,116188.810402,116751.896842,117230.697758,117667.056566,118261.162615,118842.898208,119285.740135,119666.274666,119999.261678,120403.722699,120989.794183,121529.339417,122153.537875,122858.422628,123789.840802,124513.524956,124906.754201,125545.633641,126134.437631,126902.459562,127515.581441,128214.886815,128822.736781,129554.179512,130358.655502,131172.870922,131985.291562,132853.337899,133708.959892,134504.129368,135267.910507,136186.486884,136954.004492,137593.349004,138168.341841,139049.436413,139891.522710,140756.671860,141672.053176,142557.466145,143409.152475,144224.634219,145001.250592,145648.903382,146264.399014,146871.781067,147470.926267,148310.022073,149127.701728,150133.096747,151206.165664,152294.359684,153328.710654,154269.349467,155230.159083,156062.422140,156873.305112,157565.716868,158302.931602,159298.991322,160321.715566,161551.489348,162641.264953,163868.529872,165195.816783,166390.294509,167454.260649,168345.908407,169244.026653,170259.436972,171491.948022,172961.492301,174489.856463,176519.167262,178414.235458,180352.359844,182163.025169,183790.225699,185254.590074,186595.459843,188117.420751,189432.559450,190887.178046,192777.992816,195054.588633,197166.321247,199484.215451,201810.209220,203802.697174,205729.039164,207296.213554,208461.740051,209599.966437,210351.657616,211290.177801,212876.335330,214299.697155,215549.621800,216694.836639,217321.746789,217807.039009,217903.815011,217923.643692,217588.562892,217314.512907,216959.849405,216750.360759,216838.820371,217026.343490,216770.240077,216428.119378,215857.765326,215318.326893,214246.940139,213248.929167,211758.878517,210436.487822,208632.184160,206831.779647,205405.821132,203916.756069,202565.847864,201004.749514,199176.518143,196967.030699,195291.121202,193396.037872,190905.670556,189055.199854,187107.320143,185851.321678,184593.634672,183389.152630,182440.795624,181651.236618,180849.036506,179906.615973,179111.383433,178726.325884,178718.233385,178342.958892,177948.105691,177843.836943,178122.006824,178646.807622,178577.444423,178023.007632,176894.021269,175953.317612,174607.195574,173403.692647,172169.016132,171076.591007,169903.184580,169065.873865,168470.775447,167660.806407,167039.729324,166585.832534,166173.425728,165616.232125,165094.817491,164394.962267,163908.344792,163449.460120,163186.444070,163184.568274,163973.234033,164654.711133,165397.340142,166061.946742,166569.247584,166994.415726,167476.674834,168054.941061,168701.361249,169394.059456,170416.370219,171525.298260,173140.321405,174709.953916,176336.871439,177944.603242,179249.366984,180282.911340,181334.289391,182296.008977,182943.129596,183811.579550,184698.109238,185605.785524,186414.517256,187334.068040,188342.631119,189109.021338,189465.903098,189572.812175,189902.140599,190510.497913,191060.699657,191701.707903,192340.404348,193357.895373,194751.191550,195954.563167,197185.533604,198015.472924,198524.706406,199234.083933,199814.149291,200334.344844,200954.099331,202043.557461,202900.534914,204004.606944,205168.221526,206709.026340,207947.040963,208953.336058,209720.687421,210323.284547,211054.639176,211965.715715,212993.114480,213947.157407,214938.775728,216314.870628,217934.460618,219705.789733,221118.473732,222290.399543,222998.017635,223773.855949,224791.757408,225807.465788,226888.502338,228173.622186,229263.922283,230931.039384,232729.285635,234400.638398,235939.870126,236986.555640,237600.312642,238221.542455,238785.876499,239322.536932,240055.901119,240920.509287,241751.191889,242737.049390,243888.984935,245048.633716,246158.478241,246839.115167,247149.399105,247522.415366,247980.770494,248458.317076,248959.833223,249875.634267,251031.533967,252482.025660,254482.348269,256015.222293,256416.989483,257489.539680,259474.984860,261737.851200,264285.300818,267230.903426,270190.387417,272946.714969,276645.147775,280464.644911,284783.030867,289685.142856,296222.614665,302595.184758,307671.343492,311806.345974,315195.936010,318565.272355,322143.055679,327291.684511,332119.961470,337914.404130,343952.510967,350424.227694,354625.010567,357379.894829
1,394913,1,"New York, NY",Msa,NY,188619.824154,186902.344781,186516.831244,186200.628706,186092.565350,185535.644755,185557.174303,185684.913846,185632.297930,185808.981104,186382.967096,186644.169385,187381.429205,187851.636777,188288.906071,188758.925860,189407.111435,190156.329751,190792.385624,191309.801468,191774.940179,192168.051538,193730.515945,194641.892733,195207.881433,195150.883959,195508.501557,195995.941181,196738.385987,197355.688014,198146.617671,199343.020230,200528.148039,201631.622690,202813.215642,204196.605714,204449.126934,205912.957032,207342.685950,208918.047002,211054.587539,213068.012751,215850.612790,216956.704982,218827.000914,220525.679671,222658.000042,224576.999673,226193.393088,228720.659112,230973.443302,233065.708337,235431.880865,238174.521162,240997.892657,243300.384998,246004.635744,248252.611815,250734.224699,252989.690028,254712.446877,257409.003775,259411.706957,261819.103936,264436.862156,267192.475488,269785.933402,272773.970797,275579.784290,278589.373265,281232.103867,283678.220978,286440.413042,288338.326616,290446.582177,293317.326124,296037.703624,299542.673180,303595.828848,308568.377542,312556.816193,316041.165384,319747.717122,323743.754932,326873.685109,330264.645632,334961.726141,337492.768228,341553.239519,346082.848492,349921.314952,353553.061691,356938.198475,359443.064656,362567.566207,365634.731207,368944.900169,371396.855152,375163.091250,378347.399848,383486.696783,388493.685309,393928.507727,398965.268062,404313.853455,408773.624801,412917.566031,416758.363958,420083.040892,423332.525394,427585.017478,433744.140708,438859.639849,443545.824885,449426.544625,454556.669016,459278.038119,464539.484967,467543.265618,471610.707323,474150.574492,476967.133966,478327.292717,480953.702807,483561.945623,485682.659018,486802.290095,486216.152829,485068.856350,482616.952379,480424.611998,478417.733860,475949.099176,475258.737799,477169.234887,474708.120653,474945.476413,473238.220264,471088.142427,471052.604372,468379.758092,467341.497997,465901.919724,462891.799659,461560.168505,459554.281220,455253.037694,453988.801501,449444.236248,446778.353365,445217.802639,442181.701941,438256.601045,434871.191266,430476.300262,426992.679121,422388.672943,418592.065546,415851.672992,412119.563213,411100.640199,408354.754986,406152.142261,404362.892871,403471.668551,402160.588498,401515.428669,401293.335391,400924.140688,401356.652062,399807.325103,400272.981528,400795.620811,402495.581580,403026.777882,402367.631716,400976.373125,398320.983500,395729.433417,393320.335110,392953.438953,391417.163979,391175.015369,389124.370142,388229.253952,386599.858970,385676.118368,384343.236586,382335.750565,380387.489986,377790.792231,376417.812537,374940.603418,373130.433040,372938.407394,373047.346783,373479.568126,374377.916739,374328.306472,373924.374487,374003.664529,373274.597659,373388.298403,374100.980021,374055.114274,375303.419869,377102.253337,379596.406346,382393.891141,384227.699743,386261.523496,387743.875608,389119.645034,390761.454868,391730.505987,392374.914648,395098.644846,396094.516082,398143.875961,400640.640111,402376.289657,403777.887419,404607.469094,404889.911270,405171.403280,405017.237024,404491.017121,405573.267451,406160.411531,407339.632833,408317.971740,411067.679021,412625.061031,414213.258662,415023.009097,414709.340304,415590.599266,415731.944287,417095.603715,416906.305970,416895.751702,418448.998947,420323.196065,423003.396998,424913.332825,426068.910917,427447.451795,428019.709109,428604.649823,429513.339785,430216.749080,431185.079845,434164.006653,434759.143562,438013.783374,440660.430863,445136.287918,447252.864772,449691.733440,451198.418603,452182.433352,453108.443054,454086.966266,455074.724839,458326.626518,461527.787091,464611.538483,468956.984533,471175.149309,471850.332393,472305.680419,472829.754714,473910.134575,474808.116385,475433.856970,475547.435046,476003.988152,477235.530293,479151.022466,481061.828917,482480.905841,482181.093366,482213.351046,481191.335441,479561.858501,478541.900376,478143.171578,479146.497307,480601.883021,482477.436911,484815.595961,487915.696929,488577.788773,489213.729764,492812.989391,495959.338706,501952.076003,507724.342321,512433.007611,517563.739996,520983.836297,526240.231344,531657.695028,537815.710103,546286.909866,555878.206354,562684.494158,568042.054368,571657.036139,573310.481602,575563.148840,578104.763070,583117.029391,588738.040691,598917.003736,607892.523209,615684.294840,619950.798036
2,753899,2,"Los Angeles-Long Beach-Anaheim, CA",Msa,CA,186899.297694,186230.648116,185938.942509,185915.273272,185784.264608,185654.010615,185459.018376,185533.691323,185297.526485,185011.375027,184902.046734,184615.124770,185699.376445,183931.363626,184844.280027,185400.804514,185463.078245,186451.081882,186916.231280,188128.749583,189306.316586,189551.637797,190399.607506,191166.448937,195595.737164,196831.812837,198016.612687,199479.871416,201256.648823,202646.700109,202602.900140,205397.813363,207360.591043,207805.774373,210433.836056,210240.446496,213233.839694,214631.399420,215997.752469,217615.121788,219829.533986,223460.501587,224722.071057,224578.896082,226401.767743,228113.591145,230016.048396,230721.737340,232396.191359,233686.447555,236815.086754,239610.094383,241949.322804,245149.867192,247346.914519,249875.937214,252096.204194,253501.971824,255704.865492,257158.039391,257943.502427,259984.655983,263130.783439,266372.466589,268839.626505,271818.044130,274423.165631,277097.335478,279721.783746,282018.193836,283627.420307,285445.679595,287150.847960,289363.454108,294164.245903,298731.596355,303210.906997,308685.567437,315934.725250,320848.995331,325749.523670,330471.789965,335061.786020,338237.323590,340957.520630,343885.849430,350359.405742,355503.521604,363291.492396,366143.801515,375473.396316,383964.712428,389735.072522,393683.828898,401292.830814,405157.396276,412933.121328,421686.173415,431292.401346,444238.791853,461650.194186,470393.401006,478603.135467,489978.975133,498201.582406,504028.108166,504927.089519,511448.948996,516155.893455,523119.277314,534499.948989,541738.805236,550346.342477,559915.675028,570731.600562,580541.359008,589981.503927,598679.372367,596119.658408,603344.338972,609481.055726,606646.987024,617135.320805,623211.794721,627187.619900,632800.018136,629821.297881,633960.434469,628265.954008,629328.760733,625553.268881,621273.995516,623253.685384,618350.421282,617236.491126,619466.652706,613679.878013,612360.687493,604985.086137,596872.273152,588807.809323,581138.717054,575497.367032,561087.237857,556010.427588,540800.385732,528966.993447,515510.545776,502862.746794,493332.359987,482859.923180,474664.077041,473431.999377,461188.603461,447632.110991,436035.726178,434295.104754,432168.883470,427990.545159,427332.039258,427741.188413,420102.824910,422542.299517,425965.396405,423463.083047,425931.946467,432837.618626,433618.136801,427518.570402,427084.337382,434334.813691,438047.685320,442808.554467,433449.043016,431053.797479,429515.253420,422519.506945,418759.680782,415587.230476,414579.954091,413168.541279,413638.053858,409563.620138,409818.249825,402897.699948,407851.534171,407068.024889,397452.223073,395125.750769,394395.391912,394070.585205,392930.674585,390233.507782,390095.374081,392143.043718,394720.322497,397665.465145,399856.512888,403651.608453,404122.230297,406834.074686,414292.740743,415150.721980,423826.506685,430833.178162,441533.337346,452321.108739,463708.503517,469806.618503,480021.007919,486345.259723,492854.810484,498117.234272,500186.591856,507518.531012,510504.620187,514655.114702,512632.293383,514018.439790,515166.395798,516447.973520,516482.914696,517531.178463,510588.062354,512842.916544,517227.250487,519778.980336,523908.327590,531388.220183,534929.500331,537930.028341,539107.900322,544590.136272,545988.769206,542497.753738,546531.977519,549642.241353,553481.686137,556590.001074,567679.041625,565776.377269,570147.511393,575036.692185,578974.400849,583343.033475,585200.476565,580024.378356,584899.277368,589422.130363,592356.082048,596367.651528,599374.511902,607218.079106,607643.614628,612426.926945,616741.699820,622262.922597,625451.982074,618478.590680,621282.010441,626099.954517,629859.036070,639310.217493,644498.541108,645645.436301,655224.803678,660291.630384,662564.598273,666107.581935,669567.020264,658172.711099,659535.424634,661384.183737,663734.211561,664501.170132,662306.948029,662797.497700,661086.815272,660824.929918,665813.588990,668034.761531,668002.246597,660002.007575,664282.970906,669249.709391,671954.815974,672045.963992,677807.473005,683604.351376,693733.764182,701977.461231,702690.942259,689811.003508,693439.493476,702073.960571,711438.799043,719990.110623,733050.677750,735477.156950,741698.789475,750782.656575,761944.318271,768773.156221,787967.691186,811508.244824,829316.336688,843166.922139,842110.370715,846924.686824,855066.376077,863486.466441,875907.904785,889134.920246,903405.179501,932486.596193,951912.968228,956952.456306,934729.849097

In [ ]:
data_2=data_2.drop(data_2.index[0])

In [ ]:
data_2.shape

(911, 323)

In [ ]:
data_2.columns

Index(['RegionID', 'SizeRank', 'RegionName', 'RegionType', 'StateName',
       '1996-01-31', '1996-02-29', '1996-03-31', '1996-04-30', '1996-05-31',
       ...
       '2014-03-31', '2014-04-30', '2014-05-31', '2014-06-30', '2014-07-31',
       '2014-08-31', '2014-09-30', '2014-10-31', '2014-11-30', '2014-12-31'],
      dtype='object', length=233)

In [ ]:
data_2 = data_2.drop(data_2.columns[data_2.columns.str.contains(pat = '1999')], axis='columns')

In [ ]:
data_2.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,2000-06-30,2000-07-31,2000-08-31,2000-09-30,2000-10-31,2000-11-30,2000-12-31,2001-01-31,2001-02-28,2001-03-31,2001-04-30,2001-05-31,2001-06-30,2001-07-31,2001-08-31,2001-09-30,2001-10-31,2001-11-30,2001-12-31,2002-01-31,2002-02-28,2002-03-31,2002-04-30,2002-05-31,2002-06-30,2002-07-31,2002-08-31,2002-09-30,2002-10-31,2002-11-30,2002-12-31,2003-01-31,2003-02-28,2003-03-31,2003-04-30,2003-05-31,2003-06-30,2003-07-31,2003-08-31,2003-09-30,2003-10-31,2003-11-30,2003-12-31,2004-01-31,2004-02-29,2004-03-31,2004-04-30,2004-05-31,2004-06-30,2004-07-31,2004-08-31,2004-09-30,2004-10-31,2004-11-30,2004-12-31,2005-01-31,2005-02-28,2005-03-31,2005-04-30,2005-05-31,2005-06-30,2005-07-31,2005-08-31,2005-09-30,2005-10-31,2005-11-30,2005-12-31,2006-01-31,2006-02-28,2006-03-31,2006-04-30,2006-05-31,2006-06-30,2006-07-31,2006-08-31,2006-09-30,2006-10-31,2006-11-30,2006-12-31,2007-01-31,2007-02-28,2007-03-31,2007-04-30,2007-05-31,2007-06-30,2007-07-31,2007-08-31,2007-09-30,2007-10-31,2007-11-30,2007-12-31,2008-01-31,2008-02-29,2008-03-31,2008-04-30,2008-05-31,2008-06-30,2008-07-31,2008-08-31,2008-09-30,2008-10-31,2008-11-30,2008-12-31,2009-01-31,2009-02-28,2009-03-31,2009-04-30,2009-05-31,2009-06-30,2009-07-31,2009-08-31,2009-09-30,2009-10-31,2009-11-30,2009-12-31,2010-01-31,2010-02-28,2010-03-31,2010-04-30,2010-05-31,2010-06-30,2010-07-31,2010-08-31,2010-09-30,2010-10-31,2010-11-30,2010-12-31,2011-01-31,2011-02-28,2011-03-31,2011-04-30,2011-05-31,2011-06-30,2011-07-31,2011-08-31,2011-09-30,2011-10-31,2011-11-30,2011-12-31,2012-01-31,2012-02-29,2012-03-31,2012-04-30,2012-05-31,2012-06-30,2012-07-31,2012-08-31,2012-09-30,2012-10-31,2012-11-30,2012-12-31,2013-01-31,2013-02-28,2013-03-31,2013-04-30,2013-05-31,2013-06-30,2013-07-31,2013-08-31,2013-09-30,2013-10-31,2013-11-30,2013-12-31,2014-01-31,2014-02-28,2014-03-31,2014-04-30,2014-05-31,2014-06-30,2014-07-31,2014-08-31,2014-09-30,2014-10-31,2014-11-30,2014-12-31
1,394913,1,"New York, NY",Msa,NY,226193.393088,228720.659112,230973.443302,233065.708337,235431.880865,238174.521162,240997.892657,243300.384998,246004.635744,248252.611815,250734.224699,252989.690028,254712.446877,257409.003775,259411.706957,261819.103936,264436.862156,267192.475488,269785.933402,272773.970797,275579.784290,278589.373265,281232.103867,283678.220978,286440.413042,288338.326616,290446.582177,293317.326124,296037.703624,299542.673180,303595.828848,308568.377542,312556.816193,316041.165384,319747.717122,323743.754932,326873.685109,330264.645632,334961.726141,337492.768228,341553.239519,346082.848492,349921.314952,353553.061691,356938.198475,359443.064656,362567.566207,365634.731207,368944.900169,371396.855152,375163.091250,378347.399848,383486.696783,388493.685309,393928.507727,398965.268062,404313.853455,408773.624801,412917.566031,416758.363958,420083.040892,423332.525394,427585.017478,433744.140708,438859.639849,443545.824885,449426.544625,454556.669016,459278.038119,464539.484967,467543.265618,471610.707323,474150.574492,476967.133966,478327.292717,480953.702807,483561.945623,485682.659018,486802.290095,486216.152829,485068.856350,482616.952379,480424.611998,478417.733860,475949.099176,475258.737799,477169.234887,474708.120653,474945.476413,473238.220264,471088.142427,471052.604372,468379.758092,467341.497997,465901.919724,462891.799659,461560.168505,459554.281220,455253.037694,453988.801501,449444.236248,446778.353365,445217.802639,442181.701941,438256.601045,434871.191266,430476.300262,426992.679121,422388.672943,418592.065546,415851.672992,412119.563213,411100.640199,408354.754986,406152.142261,404362.892871,403471.668551,402160.588498,401515.428669,401293.335391,400924.140688,401356.652062,399807.325103,400272.981528,400795.620811,402495.581580,403026.777882,402367.631716,400976.373125,398320.983500,395729.433417,393320.335110,392953.438953,391417.163979,391175.015369,389124.370142,388229.253952,386599.858970,385676.118368,384343.236586,382335.750565,380387.489986,377790.792231,376417.812537,374940.603418,373130.433040,372938.407394,373047.346783,373479.568126,374377.916739,374328.306472,373924.374487,374003.664529,373274.597659,373388.298403,374100.980021,374055.114274,375303.419869,377102.253337,379596.406346,382393.891141,384227.699743,386261.523496,387743.875608,389119.645034,390761.454868,391730.505987,392374.914648,395098.644846,396094.516082,398143.875961,400640.640111,402376.289657,403777.887419,404607.469094,404889.911270,405171.403280,405017.237024,404491.017121,405573.267451
2,753899,2,"Los Angeles-Long Beach-Anaheim, CA",Msa,CA,232396.191359,233686.447555,236815.086754,239610.094383,241949.322804,245149.867192,247346.914519,249875.937214,252096.204194,253501.971824,255704.865492,257158.039391,257943.502427,259984.655983,263130.783439,266372.466589,268839.626505,271818.044130,274423.165631,277097.335478,279721.783746,282018.193836,283627.420307,285445.679595,287150.847960,289363.454108,294164.245903,298731.596355,303210.906997,308685.567437,315934.725250,320848.995331,325749.523670,330471.789965,335061.786020,338237.323590,340957.520630,343885.849430,350359.405742,355503.521604,363291.492396,366143.801515,375473.396316,383964.712428,389735.072522,393683.828898,401292.830814,405157.396276,412933.121328,421686.173415,431292.401346,444238.791853,461650.194186,470393.401006,478603.135467,489978.975133,498201.582406,504028.108166,504927.089519,511448.948996,516155.893455,523119.277314,534499.948989,541738.805236,550346.342477,559915.675028,570731.600562,580541.359008,589981.503927,598679.372367,596119.658408,603344.338972,609481.055726,606646.987024,617135.320805,623211.794721,627187.619900,632800.018136,629821.297881,633960.434469,628265.954008,629328.760733,625553.268881,621273.995516,623253.685384,618350.421282,617236.491126,619466.652706,613679.878013,612360.687493,604985.086137,596872.273152,588807.809323,581138.717054,575497.367032,561087.237857,556010.427588,540800.385732,528966.993447,515510.545776,502862.746794,493332.359987,482859.923180,474664.077041,473431.999377,461188.603461,447632.110991,436035.726178,434295.104754,432168.883470,427990.545159,427332.039258,427741.188413,420102.824910,422542.299517,425965.396405,423463.083047,425931.946467,432837.618626,433618.136801,427518.570402,427084.337382,434334.813691,438047.685320,442808.554467,433449.043016,431053.797479,429515.253420,422519.506945,418759.680782,415587.230476,414579.954091,413168.541279,413638.053858,409563.620138,409818.249825,402897.699948,407851.534171,407068.024889,397452.223073,395125.750769,394395.391912,394070.585205,392930.674585,390233.507782,390095.374081,392143.043718,394720.322497,397665.465145,399856.512888,403651.608453,404122.230297,406834.074686,414292.740743,415150.721980,423826.506685,430833.178162,441533.337346,452321.108739,463708.503517,469806.618503,480021.007919,486345.259723,492854.810484,498117.234272,500186.591856,507518.531012,510504.620187,514655.114702,512632.293383,514018.439790,515166.395798,516447.973520,516482.914696,517531.178463,510588.062354,512842.916544,517227.250487,519778.980336,523908.327590
3,394463,3,"Chicago, IL",Msa,IL,170433.983952,171100.852948,171996.923898,173435.045686,174590.577335,176030.936857,177748.379568,179093.001754,180391.676806,181793.915146,183138.330692,183941.127182,184732.449931,185113.922901,186473.140722,187896.452196,189532.602346,191132.415731,192533.549739,193976.184275,195336.898097,196805.081145,197796.726846,198320.392437,198840.580882,199763.191998,201210.993725,201775.766106,203669.572270,205370.408863,207157.222251,208882.801970,210100.888364,211250.345030,211953.217048,213329.620589,213802.181860,214760.994616,215954.187778,217718.528039,218639.407027,220079.044644,221708.864144,223359.070683,225006.074842,226054.744778,227266.652233,227996.828390,229247.391648,229753.665220,230832.641131,233420.658737,234997.319167,237494.443519,239549.460008,241066.700681,242338.236231,244275.835811,245817.980669,247223.603877,248143.667849,249426.627516,251021.292811,253496.063707,255732.351887,258159.556973,260353.830846,262105.441197,264468.817308,266114.363691,267061.331856,268663.411091,269430.747759,269638.679879,271704.816843,272811.010687,274324.608328,275273.617896,276344.573473,277014.290484,277102.662028,277028.307834,277177.422202,277168.387133,277344.006106,276860.727353,276691.389481,276454.132758,276110.749443,276147.329193,275670.006828,275010.325189,273106.391777,272271.498299,271607.039794,268668.904423,267441.278057,NaN,NaN,NaN,NaN,257708.869430,257662.595514,252201.315499,251827.506894,246238.956859,242706.504220,238829.007614,231686.819397,232004.112526,228745.011726,228101.216385,226400.567078,225522.280921,224498.803199,222713.212066,218325.536579,217734.740087,215778.046888,215777.445459,213197.388404,213939.734311,210854.422393,215802.122985,212761.948329,214397.956473,208892.111664,209100.840373,205837.875170,203089.196818,199077.216241,197300.838795,194969.012741,193009.420013,193844.431212,191346.120241,192501.315536,190949.093897,191045.587443,188915.950461,187239.828140,182698.228677,183490.573827,179167.402324,178295.473422,176091.954917,179105.177011,178704.854553,179518.414790,180427.047278,177212.277331,177424.198023,177009.372713,177415.987211,177511.342567,176660.575404,178519.002745,179821.585615,180172.662949,184022.988568,185833.360108,188414.373576,190059.772279,192429.380999,192410.238691,195519.336714,193565.716748,194541.668219,196010.138722,196895.608418,197299.422028,198964.035228,201377.931120,202838.564553,202621.216766,202209.725471,202711.927591,202116.512430,201655.260408,202369.846373
4,394514,4,"Dallas-Fort Worth, TX",Msa,TX,130688.973958,130831.150235,130925.038302,131224.978253,131515.677352,131518.963086,131931.486592,132384.742208,132549.442034,133219.837949,133798.601927,134230.061866,134062.931261,132880.968264,133346.118963,133562.398369,133609.437240,133548.727697,133858.999991,134357.001780,133961.905127,134238.766591,134484.137453,134705.539302,134959.174596,135526.489437,135882.722820,136581.612824,137172.085024,138073.916530,138553.182774,138989.641971,139099.878003,139479.947877,140031.145586,140378.600927,140437.935621,140431.570277,140860.736716,140928.740293,141077.543737,141555.959118,141216.001607,141512.954790,141771.716410,141801.548422,142083.906680,141994.583623,NaN,146782.843769,149560.271951,150165.550732,150039.800504,150591.920308,150487.265984,150999.871916,151172.519552,151236.280946,151471.074106,151732.186413,153691.132968,152624.626644,153183.180020,154199.089295,154184.856483,154701.171987,154957.737673,155005.113742,155253.539811,154480.764323,155021.019010,154691.768700,154863.621393,155943.120793,156129.019167,156977.581315,158271.278116,158243.006926,157875.841992,158408.498624,158420.817772,159729.002082,159507.124569,159705.182630,158652.808393,158058.270468,158633.716245,159776.863151,160091.624842,160325.309556,160858.155277,161196.841171,161655.128069,161604.699956,161534.496131,161949.025283,158320.277985,157131.461209,157048.337798,156791.187853,156407.802961,156590.957610,156400.682467,154739.360241,153636.157839,152781.359755,151944.956401,151979.728981,151512.744604,151970.028955,152653.613021,153045.277868,153307.978574,152984.945841,153239.694603,152466.970880,152465.214880,152482.866195,153739.919851,153469.877343,152140.135361,152736.131053,152960.743211,153975.331123,153902.576528,153634.674232,152123.070244,150989.759071,149718.534314,148733.535705,147772.400296,147984.342387,147257.019189,146016.985864,146733.659063,145975.250791,145779.633242,145570.823800,145793.494573,145041.012760,145248.183548,144809.968337,144178.404918,143824.824972,143755.855868,145361.682102,146100.516232,146908.178618,147852.415095,148493.760972,149192.925515,148702.331070,148875.984536,149325.593697,150221.039726,150557.293208,151279.987458,151950.266346,153656.908483,155304.619176,156550.935871,157955.214153,159238.136674,158918.308221,160367.859296,161848.668721,162718.202141,163799.415197,164020.531972,165455.310347,166831.590566,168137.731082,169547.918208,171131.381297,170738.423001,171113.186852,171743.207854,172878.947550,174708.870957,176089.882997
5,394974,5,"Philadelphia, PA",Msa,PA,130650.510192,131357.750169,131534.457125,132207.362000,132898.297609,133416.990944,133871.009656,134531.472222,135277.796147,135898.475982,136495.234019,137119.432044,137761.306743,138376.998627,139059.883275,139784.708500,140554.881545,141500.482619,142531.479739,143453.936038,144630.503373,145400.035834,146625.696775,147076.529740,148009.545261,148742.627867,149713.284979,151038.581268,152190.057528,153791.049922,155284.879551,157529.327960,159464.713921,160903.094057,162225.286326,164163.206627,165199.489269,166158.923926,167575.911551,169371.808220,171298.758119,173475.157346,175726.447134,177929.685956,180228.294332,181725.545917,183453.651179,184687.533565,186040.996205,187161.828028,188912.814869,191130.413614,194102.766854,197260.099262,200543.272185,204175.357578,206202.558596,207761.629283,209975.098237,212534.702950,214634.437564,215189.346055,217167.135992,219839.874851,223356.514158,226978.675927,230311.031919,233447.607117,236053.196181,238779.502836,240349.017036,242255.513950,242902.433820,243719.502316,245276.206613,247356.302354,249233.989717,251179.096260,252542.454831,253050.444437,253382.483922,253470.398354,252574.169304,252118.702296,251545.354980,250964.759442,252172.290544,252487.771298,254003.925248,254446.681214,254556.946613,253686.799269,253283.811538,253376.753579,252030.373435,250917.242292,249183.474598,249314.495892,249087.783224,249025.272788,247698.238819,246541.603662,245065.047100,243404.545212,241403.818291,239672.238851,237941.968851,235974.823562,234169.720441,233604.222624,233759.494204,233458.795553,232982.730796,232589.811407,231352.846850,230998.831977,230164.510467,230325.627532,230412.113614,229514.193990,229463.463395,228870.733717,229000.622286,230076.175933,230975.559760,230886.406519,229908.562105,228313.147175,225844.645296,223910.157495,221684.777948,220272.839239,219139.242833,218243.238016,217615.962697,216470.520773,215376.925823,214271.292446,213395.584494,212680.510870,210785.523733,209799.397530,208825.717870,207645.000980,206253.891581,205519.633277,206428.028246,206841.460856,206904.101287,206524.852138,205958.376964,205547.882418,205119.163527,204480.121750,204332.504907,203980.895218,204217.525527,204283.212996,205535.899356,206939.879301,208754.246010,209912.815606,210636.412609,210697.921904,211208.452804,211199.883483,211325.151183,211108.131111,211617.334742,212064.085453,212351.701159,212239.766851,213967.133459,214398.564347,213983.491823,213492.533899,213040.121382,212830.451015,213028.766548,213084.006805

In [ ]:
data_2.shape

(911, 185)

In [ ]:
new = data_2["RegionName"].str.split(", ", n = 1, expand = True)
 
# making separate first name column from new data frame
data_2["City "]= new[0]
 
# making separate last name column from new data frame
data_2["State"]= new[1]
 
# Dropping old Name columns
data_2.drop(columns =["RegionName"], inplace = True)

data_2.head()

,RegionID,SizeRank,RegionType,StateName,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,2000-06-30,2000-07-31,2000-08-31,2000-09-30,2000-10-31,2000-11-30,2000-12-31,2001-01-31,2001-02-28,2001-03-31,2001-04-30,2001-05-31,2001-06-30,2001-07-31,2001-08-31,2001-09-30,2001-10-31,2001-11-30,2001-12-31,2002-01-31,2002-02-28,2002-03-31,2002-04-30,2002-05-31,2002-06-30,2002-07-31,2002-08-31,2002-09-30,2002-10-31,2002-11-30,2002-12-31,2003-01-31,2003-02-28,2003-03-31,2003-04-30,2003-05-31,2003-06-30,2003-07-31,2003-08-31,2003-09-30,2003-10-31,2003-11-30,2003-12-31,2004-01-31,2004-02-29,2004-03-31,2004-04-30,2004-05-31,2004-06-30,2004-07-31,2004-08-31,2004-09-30,2004-10-31,2004-11-30,2004-12-31,2005-01-31,2005-02-28,2005-03-31,2005-04-30,2005-05-31,2005-06-30,2005-07-31,2005-08-31,2005-09-30,2005-10-31,2005-11-30,2005-12-31,2006-01-31,2006-02-28,2006-03-31,2006-04-30,2006-05-31,2006-06-30,2006-07-31,2006-08-31,2006-09-30,2006-10-31,2006-11-30,2006-12-31,2007-01-31,2007-02-28,2007-03-31,2007-04-30,2007-05-31,2007-06-30,2007-07-31,2007-08-31,2007-09-30,2007-10-31,2007-11-30,2007-12-31,2008-01-31,2008-02-29,2008-03-31,2008-04-30,2008-05-31,2008-06-30,2008-07-31,2008-08-31,2008-09-30,2008-10-31,2008-11-30,2008-12-31,2009-01-31,2009-02-28,2009-03-31,2009-04-30,2009-05-31,2009-06-30,2009-07-31,2009-08-31,2009-09-30,2009-10-31,2009-11-30,2009-12-31,2010-01-31,2010-02-28,2010-03-31,2010-04-30,2010-05-31,2010-06-30,2010-07-31,2010-08-31,2010-09-30,2010-10-31,2010-11-30,2010-12-31,2011-01-31,2011-02-28,2011-03-31,2011-04-30,2011-05-31,2011-06-30,2011-07-31,2011-08-31,2011-09-30,2011-10-31,2011-11-30,2011-12-31,2012-01-31,2012-02-29,2012-03-31,2012-04-30,2012-05-31,2012-06-30,2012-07-31,2012-08-31,2012-09-30,2012-10-31,2012-11-30,2012-12-31,2013-01-31,2013-02-28,2013-03-31,2013-04-30,2013-05-31,2013-06-30,2013-07-31,2013-08-31,2013-09-30,2013-10-31,2013-11-30,2013-12-31,2014-01-31,2014-02-28,2014-03-31,2014-04-30,2014-05-31,2014-06-30,2014-07-31,2014-08-31,2014-09-30,2014-10-31,2014-11-30,2014-12-31,City,State
1,394913,1,Msa,NY,226193.393088,228720.659112,230973.443302,233065.708337,235431.880865,238174.521162,240997.892657,243300.384998,246004.635744,248252.611815,250734.224699,252989.690028,254712.446877,257409.003775,259411.706957,261819.103936,264436.862156,267192.475488,269785.933402,272773.970797,275579.784290,278589.373265,281232.103867,283678.220978,286440.413042,288338.326616,290446.582177,293317.326124,296037.703624,299542.673180,303595.828848,308568.377542,312556.816193,316041.165384,319747.717122,323743.754932,326873.685109,330264.645632,334961.726141,337492.768228,341553.239519,346082.848492,349921.314952,353553.061691,356938.198475,359443.064656,362567.566207,365634.731207,368944.900169,371396.855152,375163.091250,378347.399848,383486.696783,388493.685309,393928.507727,398965.268062,404313.853455,408773.624801,412917.566031,416758.363958,420083.040892,423332.525394,427585.017478,433744.140708,438859.639849,443545.824885,449426.544625,454556.669016,459278.038119,464539.484967,467543.265618,471610.707323,474150.574492,476967.133966,478327.292717,480953.702807,483561.945623,485682.659018,486802.290095,486216.152829,485068.856350,482616.952379,480424.611998,478417.733860,475949.099176,475258.737799,477169.234887,474708.120653,474945.476413,473238.220264,471088.142427,471052.604372,468379.758092,467341.497997,465901.919724,462891.799659,461560.168505,459554.281220,455253.037694,453988.801501,449444.236248,446778.353365,445217.802639,442181.701941,438256.601045,434871.191266,430476.300262,426992.679121,422388.672943,418592.065546,415851.672992,412119.563213,411100.640199,408354.754986,406152.142261,404362.892871,403471.668551,402160.588498,401515.428669,401293.335391,400924.140688,401356.652062,399807.325103,400272.981528,400795.620811,402495.581580,403026.777882,402367.631716,400976.373125,398320.983500,395729.433417,393320.335110,392953.438953,391417.163979,391175.015369,389124.370142,388229.253952,386599.858970,385676.118368,384343.236586,382335.750565,380387.489986,377790.792231,376417.812537,374940.603418,373130.433040,372938.407394,373047.346783,373479.568126,374377.916739,374328.306472,373924.374487,374003.664529,373274.597659,373388.298403,374100.980021,374055.114274,375303.419869,377102.253337,379596.406346,382393.891141,384227.699743,386261.523496,387743.875608,389119.645034,390761.454868,391730.505987,392374.914648,395098.644846,396094.516082,398143.875961,400640.640111,402376.289657,403777.887419,404607.469094,404889.911270,405171.403280,405017.237024,404491.017121,405573.267451,New York,NY
2,753899,2,Msa,CA,232396.191359,233686.447555,236815.086754,239610.094383,241949.322804,245149.867192,247346.914519,249875.937214,252096.204194,253501.971824,255704.865492,257158.039391,257943.502427,259984.655983,263130.783439,266372.466589,268839.626505,271818.044130,274423.165631,277097.335478,279721.783746,282018.193836,283627.420307,285445.679595,287150.847960,289363.454108,294164.245903,298731.596355,303210.906997,308685.567437,315934.725250,320848.995331,325749.523670,330471.789965,335061.786020,338237.323590,340957.520630,343885.849430,350359.405742,355503.521604,363291.492396,366143.801515,375473.396316,383964.712428,389735.072522,393683.828898,401292.830814,405157.396276,412933.121328,421686.173415,431292.401346,444238.791853,461650.194186,470393.401006,478603.135467,489978.975133,498201.582406,504028.108166,504927.089519,511448.948996,516155.893455,523119.277314,534499.948989,541738.805236,550346.342477,559915.675028,570731.600562,580541.359008,589981.503927,598679.372367,596119.658408,603344.338972,609481.055726,606646.987024,617135.320805,623211.794721,627187.619900,632800.018136,629821.297881,633960.434469,628265.954008,629328.760733,625553.268881,621273.995516,623253.685384,618350.421282,617236.491126,619466.652706,613679.878013,612360.687493,604985.086137,596872.273152,588807.809323,581138.717054,575497.367032,561087.237857,556010.427588,540800.385732,528966.993447,515510.545776,502862.746794,493332.359987,482859.923180,474664.077041,473431.999377,461188.603461,447632.110991,436035.726178,434295.104754,432168.883470,427990.545159,427332.039258,427741.188413,420102.824910,422542.299517,425965.396405,423463.083047,425931.946467,432837.618626,433618.136801,427518.570402,427084.337382,434334.813691,438047.685320,442808.554467,433449.043016,431053.797479,429515.253420,422519.506945,418759.680782,415587.230476,414579.954091,413168.541279,413638.053858,409563.620138,409818.249825,402897.699948,407851.534171,407068.024889,397452.223073,395125.750769,394395.391912,394070.585205,392930.674585,390233.507782,390095.374081,392143.043718,394720.322497,397665.465145,399856.512888,403651.608453,404122.230297,406834.074686,414292.740743,415150.721980,423826.506685,430833.178162,441533.337346,452321.108739,463708.503517,469806.618503,480021.007919,486345.259723,492854.810484,498117.234272,500186.591856,507518.531012,510504.620187,514655.114702,512632.293383,514018.439790,515166.395798,516447.973520,516482.914696,517531.178463,510588.062354,512842.916544,517227.250487,519778.980336,523908.327590,Los Angeles-Long Beach-Anaheim,CA
3,394463,3,Msa,IL,170433.983952,171100.852948,171996.923898,173435.045686,174590.577335,176030.936857,177748.379568,179093.001754,180391.676806,181793.915146,183138.330692,183941.127182,184732.449931,185113.922901,186473.140722,187896.452196,189532.602346,191132.415731,192533.549739,193976.184275,195336.898097,196805.081145,197796.726846,198320.392437,198840.580882,199763.191998,201210.993725,201775.766106,203669.572270,205370.408863,207157.222251,208882.801970,210100.888364,211250.345030,211953.217048,213329.620589,213802.181860,214760.994616,215954.187778,217718.528039,218639.407027,220079.044644,221708.864144,223359.070683,225006.074842,226054.744778,227266.652233,227996.828390,229247.391648,229753.665220,230832.641131,233420.658737,234997.319167,237494.443519,239549.460008,241066.700681,242338.236231,244275.835811,245817.980669,247223.603877,248143.667849,249426.627516,251021.292811,253496.063707,255732.351887,258159.556973,260353.830846,262105.441197,264468.817308,266114.363691,267061.331856,268663.411091,269430.747759,269638.679879,271704.816843,272811.010687,274324.608328,275273.617896,276344.573473,277014.290484,277102.662028,277028.307834,277177.422202,277168.387133,277344.006106,276860.727353,276691.389481,276454.132758,276110.749443,276147.329193,275670.006828,275010.325189,273106.391777,272271.498299,271607.039794,268668.904423,267441.278057,NaN,NaN,NaN,NaN,257708.869430,257662.595514,252201.315499,251827.506894,246238.956859,242706.504220,238829.007614,231686.819397,232004.112526,228745.011726,228101.216385,226400.567078,225522.280921,224498.803199,222713.212066,218325.536579,217734.740087,215778.046888,215777.445459,213197.388404,213939.734311,210854.422393,215802.122985,212761.948329,214397.956473,208892.111664,209100.840373,205837.875170,203089.196818,199077.216241,197300.838795,194969.012741,193009.420013,193844.431212,191346.120241,192501.315536,190949.093897,191045.587443,188915.950461,187239.828140,182698.228677,183490.573827,179167.402324,178295.473422,176091.954917,179105.177011,178704.854553,179518.414790,180427.047278,177212.277331,177424.198023,177009.372713,177415.987211,177511.342567,176660.575404,178519.002745,179821.585615,180172.662949,184022.988568,185833.360108,188414.373576,190059.772279,192429.380999,192410.238691,195519.336714,193565.716748,194541.668219,196010.138722,196895.608418,197299.422028,198964.035228,201377.931120,202838.564553,202621.216766,202209.725471,202711.927591,202116.512430,201655.260408,202369.846373,Chicago,IL
4,394514,4,Msa,TX,130688.973958,130831.150235,130925.038302,131224.978253,131515.677352,131518.963086,131931.486592,132384.742208,132549.442034,133219.837949,133798.601927,134230.061866,134062.931261,132880.968264,133346.118963,133562.398369,133609.437240,133548.727697,133858.999991,134357.001780,133961.905127,134238.766591,134484.137453,134705.539302,134959.174596,135526.489437,135882.722820,136581.612824,137172.085024,138073.916530,138553.182774,138989.641971,139099.878003,139479.947877,140031.145586,140378.600927,140437.935621,140431.570277,140860.736716,140928.740293,141077.543737,141555.959118,141216.001607,141512.954790,141771.716410,141801.548422,142083.906680,141994.583623,NaN,146782.843769,149560.271951,150165.550732,150039.800504,150591.920308,150487.265984,150999.871916,151172.519552,151236.280946,151471.074106,151732.186413,153691.132968,152624.626644,153183.180020,154199.089295,154184.856483,154701.171987,154957.737673,155005.113742,155253.539811,154480.764323,155021.019010,154691.768700,154863.621393,155943.120793,156129.019167,156977.581315,158271.278116,158243.006926,157875.841992,158408.498624,158420.817772,159729.002082,159507.124569,159705.182630,158652.808393,158058.270468,158633.716245,159776.863151,160091.624842,160325.309556,160858.155277,161196.841171,161655.128069,161604.699956,161534.496131,161949.025283,158320.277985,157131.461209,157048.337798,156791.187853,156407.802961,156590.957610,156400.682467,154739.360241,153636.157839,152781.359755,151944.956401,151979.728981,151512.744604,151970.028955,152653.613021,153045.277868,153307.978574,152984.945841,153239.694603,152466.970880,152465.214880,152482.866195,153739.919851,153469.877343,152140.135361,152736.131053,152960.743211,153975.331123,153902.576528,153634.674232,152123.070244,150989.759071,149718.534314,148733.535705,147772.400296,147984.342387,147257.019189,146016.985864,146733.659063,145975.250791,145779.633242,145570.823800,145793.494573,145041.012760,145248.183548,144809.968337,144178.404918,143824.824972,143755.855868,145361.682102,146100.516232,146908.178618,147852.415095,148493.760972,149192.925515,148702.331070,148875.984536,149325.593697,150221.039726,150557.293208,151279.987458,151950.266346,153656.908483,155304.619176,156550.935871,157955.214153,159238.136674,158918.308221,160367.859296,161848.668721,162718.202141,163799.415197,164020.531972,165455.310347,166831.590566,168137.731082,169547.918208,171131.381297,170738.423001,171113.186852,171743.207854,172878.947550,174708.870957,176089.882997,Dallas-Fort Worth,TX
5,394974,5,Msa,PA,130650.510192,131357.750169,131534.457125,132207.362000,132898.297609,133416.990944,133871.009656,134531.472222,135277.796147,135898.475982,136495.234019,137119.432044,137761.306743,138376.998627,139059.883275,139784.708500,140554.881545,141500.482619,142531.479739,143453.936038,144630.503373,145400.035834,146625.696775,147076.529740,148009.545261,148742.627867,149713.284979,151038.581268,152190.057528,153791.049922,155284.879551,157529.327960,159464.713921,160903.094057,162225.286326,164163.206627,165199.489269,166158.923926,167575.911551,169371.808220,171298.758119,173475.157346,175726.447134,177929.685956,180228.294332,181725.545917,183453.651179,184687.533565,186040.996205,187161.828028,188912.814869,191130.413614,194102.766854,197260.099262,200543.272185,204175.357578,206202.558596,207761.629283,209975.098237,212534.702950,214634.437564,215189.346055,217167.135992,219839.874851,223356.514158,226978.675927,230311.031919,233447.607117,236053.196181,238779.502836,240349.017036,242255.513950,242902.433820,243719.502316,245276.206613,247356.302354,249233.989717,251179.096260,252542.454831,253050.444437,253382.483922,253470.398354,252574.169304,252118.702296,251545.354980,250964.759442,252172.290544,252487.771298,254003.925248,254446.681214,254556.946613,253686.799269,253283.811538,253376.753579,252030.373435,250917.242292,249183.474598,249314.495892,249087.783224,249025.272788,247698.238819,246541.603662,245065.047100,243404.545212,241403.818291,239672.238851,237941.968851,235974.823562,234169.720441,233604.222624,233759.494204,233458.795553,232982.730796,232589.811407,231352.846850,230998.831977,230164.510467,230325.627532,230412.113614,229514.193990,229463.463395,228870.733717,229000.622286,230076.175933,230975.559760,230886.406519,229908.562105,228313.147175,225844.645296,223910.157495,221684.777948,220272.839239,219139.242833,218243.238016,217615.962697,216470.520773,215376.925823,214271.292446,213395.584494,212680.510870,210785.523733,209799.397530,208825.717870,207645.000980,206253.891581,205519.633277,206428.028246,206841.460856,206904.101287,206524.852138,205958.376964,205547.882418,205119.163527,204480.121750,204332.504907,203980.895218,204217.525527,204283.212996,205535.899356,206939.879301,208754.246010,209912.815606,210636.412609,210697.921904,211208.452804,211199.883483,211325.151183,211108.131111,211617.334742,212064.085453,212351.701159,212239.766851,213967.133459,214398.564347,213983.491823,213492.533899,213040.121382,212830.451015,213028.766548,213084.006805,Philadelphia,PA

In [ ]:
data_2['house_type']='Condo'
data_2['cost_percentile_range']='mid' #mid is between 33% and 65 percentile
data_2.head()

,RegionID,SizeRank,RegionType,StateName,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,2000-06-30,2000-07-31,2000-08-31,2000-09-30,2000-10-31,2000-11-30,2000-12-31,2001-01-31,2001-02-28,2001-03-31,2001-04-30,2001-05-31,2001-06-30,2001-07-31,2001-08-31,2001-09-30,2001-10-31,2001-11-30,2001-12-31,2002-01-31,2002-02-28,2002-03-31,2002-04-30,2002-05-31,2002-06-30,2002-07-31,2002-08-31,2002-09-30,2002-10-31,2002-11-30,2002-12-31,2003-01-31,2003-02-28,2003-03-31,2003-04-30,2003-05-31,2003-06-30,2003-07-31,2003-08-31,2003-09-30,2003-10-31,2003-11-30,2003-12-31,2004-01-31,2004-02-29,2004-03-31,2004-04-30,2004-05-31,2004-06-30,2004-07-31,2004-08-31,2004-09-30,2004-10-31,2004-11-30,2004-12-31,2005-01-31,2005-02-28,2005-03-31,2005-04-30,2005-05-31,2005-06-30,2005-07-31,2005-08-31,2005-09-30,2005-10-31,2005-11-30,2005-12-31,2006-01-31,2006-02-28,2006-03-31,2006-04-30,2006-05-31,2006-06-30,2006-07-31,2006-08-31,2006-09-30,2006-10-31,2006-11-30,2006-12-31,2007-01-31,2007-02-28,2007-03-31,2007-04-30,2007-05-31,2007-06-30,2007-07-31,2007-08-31,2007-09-30,2007-10-31,2007-11-30,2007-12-31,2008-01-31,2008-02-29,2008-03-31,2008-04-30,2008-05-31,2008-06-30,2008-07-31,2008-08-31,2008-09-30,2008-10-31,2008-11-30,2008-12-31,2009-01-31,2009-02-28,2009-03-31,2009-04-30,2009-05-31,2009-06-30,2009-07-31,2009-08-31,2009-09-30,2009-10-31,2009-11-30,2009-12-31,2010-01-31,2010-02-28,2010-03-31,2010-04-30,2010-05-31,2010-06-30,2010-07-31,2010-08-31,2010-09-30,2010-10-31,2010-11-30,2010-12-31,2011-01-31,2011-02-28,2011-03-31,2011-04-30,2011-05-31,2011-06-30,2011-07-31,2011-08-31,2011-09-30,2011-10-31,2011-11-30,2011-12-31,2012-01-31,2012-02-29,2012-03-31,2012-04-30,2012-05-31,2012-06-30,2012-07-31,2012-08-31,2012-09-30,2012-10-31,2012-11-30,2012-12-31,2013-01-31,2013-02-28,2013-03-31,2013-04-30,2013-05-31,2013-06-30,2013-07-31,2013-08-31,2013-09-30,2013-10-31,2013-11-30,2013-12-31,2014-01-31,2014-02-28,2014-03-31,2014-04-30,2014-05-31,2014-06-30,2014-07-31,2014-08-31,2014-09-30,2014-10-31,2014-11-30,2014-12-31,City,State,house_type,cost_percentile_range
1,394913,1,Msa,NY,226193.393088,228720.659112,230973.443302,233065.708337,235431.880865,238174.521162,240997.892657,243300.384998,246004.635744,248252.611815,250734.224699,252989.690028,254712.446877,257409.003775,259411.706957,261819.103936,264436.862156,267192.475488,269785.933402,272773.970797,275579.784290,278589.373265,281232.103867,283678.220978,286440.413042,288338.326616,290446.582177,293317.326124,296037.703624,299542.673180,303595.828848,308568.377542,312556.816193,316041.165384,319747.717122,323743.754932,326873.685109,330264.645632,334961.726141,337492.768228,341553.239519,346082.848492,349921.314952,353553.061691,356938.198475,359443.064656,362567.566207,365634.731207,368944.900169,371396.855152,375163.091250,378347.399848,383486.696783,388493.685309,393928.507727,398965.268062,404313.853455,408773.624801,412917.566031,416758.363958,420083.040892,423332.525394,427585.017478,433744.140708,438859.639849,443545.824885,449426.544625,454556.669016,459278.038119,464539.484967,467543.265618,471610.707323,474150.574492,476967.133966,478327.292717,480953.702807,483561.945623,485682.659018,486802.290095,486216.152829,485068.856350,482616.952379,480424.611998,478417.733860,475949.099176,475258.737799,477169.234887,474708.120653,474945.476413,473238.220264,471088.142427,471052.604372,468379.758092,467341.497997,465901.919724,462891.799659,461560.168505,459554.281220,455253.037694,453988.801501,449444.236248,446778.353365,445217.802639,442181.701941,438256.601045,434871.191266,430476.300262,426992.679121,422388.672943,418592.065546,415851.672992,412119.563213,411100.640199,408354.754986,406152.142261,404362.892871,403471.668551,402160.588498,401515.428669,401293.335391,400924.140688,401356.652062,399807.325103,400272.981528,400795.620811,402495.581580,403026.777882,402367.631716,400976.373125,398320.983500,395729.433417,393320.335110,392953.438953,391417.163979,391175.015369,389124.370142,388229.253952,386599.858970,385676.118368,384343.236586,382335.750565,380387.489986,377790.792231,376417.812537,374940.603418,373130.433040,372938.407394,373047.346783,373479.568126,374377.916739,374328.306472,373924.374487,374003.664529,373274.597659,373388.298403,374100.980021,374055.114274,375303.419869,377102.253337,379596.406346,382393.891141,384227.699743,386261.523496,387743.875608,389119.645034,390761.454868,391730.505987,392374.914648,395098.644846,396094.516082,398143.875961,400640.640111,402376.289657,403777.887419,404607.469094,404889.911270,405171.403280,405017.237024,404491.017121,405573.267451,New York,NY,Condo,mid
2,753899,2,Msa,CA,232396.191359,233686.447555,236815.086754,239610.094383,241949.322804,245149.867192,247346.914519,249875.937214,252096.204194,253501.971824,255704.865492,257158.039391,257943.502427,259984.655983,263130.783439,266372.466589,268839.626505,271818.044130,274423.165631,277097.335478,279721.783746,282018.193836,283627.420307,285445.679595,287150.847960,289363.454108,294164.245903,298731.596355,303210.906997,308685.567437,315934.725250,320848.995331,325749.523670,330471.789965,335061.786020,338237.323590,340957.520630,343885.849430,350359.405742,355503.521604,363291.492396,366143.801515,375473.396316,383964.712428,389735.072522,393683.828898,401292.830814,405157.396276,412933.121328,421686.173415,431292.401346,444238.791853,461650.194186,470393.401006,478603.135467,489978.975133,498201.582406,504028.108166,504927.089519,511448.948996,516155.893455,523119.277314,534499.948989,541738.805236,550346.342477,559915.675028,570731.600562,580541.359008,589981.503927,598679.372367,596119.658408,603344.338972,609481.055726,606646.987024,617135.320805,623211.794721,627187.619900,632800.018136,629821.297881,633960.434469,628265.954008,629328.760733,625553.268881,621273.995516,623253.685384,618350.421282,617236.491126,619466.652706,613679.878013,612360.687493,604985.086137,596872.273152,588807.809323,581138.717054,575497.367032,561087.237857,556010.427588,540800.385732,528966.993447,515510.545776,502862.746794,493332.359987,482859.923180,474664.077041,473431.999377,461188.603461,447632.110991,436035.726178,434295.104754,432168.883470,427990.545159,427332.039258,427741.188413,420102.824910,422542.299517,425965.396405,423463.083047,425931.946467,432837.618626,433618.136801,427518.570402,427084.337382,434334.813691,438047.685320,442808.554467,433449.043016,431053.797479,429515.253420,422519.506945,418759.680782,415587.230476,414579.954091,413168.541279,413638.053858,409563.620138,409818.249825,402897.699948,407851.534171,407068.024889,397452.223073,395125.750769,394395.391912,394070.585205,392930.674585,390233.507782,390095.374081,392143.043718,394720.322497,397665.465145,399856.512888,403651.608453,404122.230297,406834.074686,414292.740743,415150.721980,423826.506685,430833.178162,441533.337346,452321.108739,463708.503517,469806.618503,480021.007919,486345.259723,492854.810484,498117.234272,500186.591856,507518.531012,510504.620187,514655.114702,512632.293383,514018.439790,515166.395798,516447.973520,516482.914696,517531.178463,510588.062354,512842.916544,517227.250487,519778.980336,523908.327590,Los Angeles-Long Beach-Anaheim,CA,Condo,mid
3,394463,3,Msa,IL,170433.983952,171100.852948,171996.923898,173435.045686,174590.577335,176030.936857,177748.379568,179093.001754,180391.676806,181793.915146,183138.330692,183941.127182,184732.449931,185113.922901,186473.140722,187896.452196,189532.602346,191132.415731,192533.549739,193976.184275,195336.898097,196805.081145,197796.726846,198320.392437,198840.580882,199763.191998,201210.993725,201775.766106,203669.572270,205370.408863,207157.222251,208882.801970,210100.888364,211250.345030,211953.217048,213329.620589,213802.181860,214760.994616,215954.187778,217718.528039,218639.407027,220079.044644,221708.864144,223359.070683,225006.074842,226054.744778,227266.652233,227996.828390,229247.391648,229753.665220,230832.641131,233420.658737,234997.319167,237494.443519,239549.460008,241066.700681,242338.236231,244275.835811,245817.980669,247223.603877,248143.667849,249426.627516,251021.292811,253496.063707,255732.351887,258159.556973,260353.830846,262105.441197,264468.817308,266114.363691,267061.331856,268663.411091,269430.747759,269638.679879,271704.816843,272811.010687,274324.608328,275273.617896,276344.573473,277014.290484,277102.662028,277028.307834,277177.422202,277168.387133,277344.006106,276860.727353,276691.389481,276454.132758,276110.749443,276147.329193,275670.006828,275010.325189,273106.391777,272271.498299,271607.039794,268668.904423,267441.278057,NaN,NaN,NaN,NaN,257708.869430,257662.595514,252201.315499,251827.506894,246238.956859,242706.504220,238829.007614,231686.819397,232004.112526,228745.011726,228101.216385,226400.567078,225522.280921,224498.803199,222713.212066,218325.536579,217734.740087,215778.046888,215777.445459,213197.388404,213939.734311,210854.422393,215802.122985,212761.948329,214397.956473,208892.111664,209100.840373,205837.875170,203089.196818,199077.216241,197300.838795,194969.012741,193009.420013,193844.431212,191346.120241,192501.315536,190949.093897,191045.587443,188915.950461,187239.828140,182698.228677,183490.573827,179167.402324,178295.473422,176091.954917,179105.177011,178704.854553,179518.414790,180427.047278,177212.277331,177424.198023,177009.372713,177415.987211,177511.342567,176660.575404,178519.002745,179821.585615,180172.662949,184022.988568,185833.360108,188414.373576,190059.772279,192429.380999,192410.238691,195519.336714,193565.716748,194541.668219,196010.138722,196895.608418,197299.422028,198964.035228,201377.931120,202838.564553,202621.216766,202209.725471,202711.927591,202116.512430,201655.260408,202369.846373,Chicago,IL,Condo,mid
4,394514,4,Msa,TX,130688.973958,130831.150235,130925.038302,131224.978253,131515.677352,131518.963086,131931.486592,132384.742208,132549.442034,133219.837949,133798.601927,134230.061866,134062.931261,132880.968264,133346.118963,133562.398369,133609.437240,133548.727697,133858.999991,134357.001780,133961.905127,134238.766591,134484.137453,134705.539302,134959.174596,135526.489437,135882.722820,136581.612824,137172.085024,138073.916530,138553.182774,138989.641971,139099.878003,139479.947877,140031.145586,140378.600927,140437.935621,140431.570277,140860.736716,140928.740293,141077.543737,141555.959118,141216.001607,141512.954790,141771.716410,141801.548422,142083.906680,141994.583623,NaN,146782.843769,149560.271951,150165.550732,150039.800504,150591.920308,150487.265984,150999.871916,151172.519552,151236.280946,151471.074106,151732.186413,153691.132968,152624.626644,153183.180020,154199.089295,154184.856483,154701.171987,154957.737673,155005.113742,155253.539811,154480.764323,155021.019010,154691.768700,154863.621393,155943.120793,156129.019167,156977.581315,158271.278116,158243.006926,157875.841992,158408.498624,158420.817772,159729.002082,159507.124569,159705.182630,158652.808393,158058.270468,158633.716245,159776.863151,160091.624842,160325.309556,160858.155277,161196.841171,161655.128069,161604.699956,161534.496131,161949.025283,158320.277985,157131.461209,157048.337798,156791.187853,156407.802961,156590.957610,156400.682467,154739.360241,153636.157839,152781.359755,151944.956401,151979.728981,151512.744604,151970.028955,152653.613021,153045.277868,153307.978574,152984.945841,153239.694603,152466.970880,152465.214880,152482.866195,153739.919851,153469.877343,152140.135361,152736.131053,152960.743211,153975.331123,153902.576528,153634.674232,152123.070244,150989.759071,149718.534314,148733.535705,147772.400296,147984.342387,147257.019189,146016.985864,146733.659063,145975.250791,145779.633242,145570.823800,145793.494573,145041.012760,145248.183548,144809.968337,144178.404918,143824.824972,143755.855868,145361.682102,146100.516232,146908.178618,147852.415095,148493.760972,149192.925515,148702.331070,148875.984536,149325.593697,150221.039726,150557.293208,151279.987458,151950.266346,153656.908483,155304.619176,156550.935871,157955.214153,159238.136674,158918.308221,160367.859296,161848.668721,162718.202141,163799.415197,164020.531972,165455.310347,166831.590566,168137.731082,169547.918208,171131.381297,170738.423001,171113.186852,171743.207854,172878.947550,174708.870957,176089.882997,Dallas-Fort Worth,TX,Condo,mid
5,394974,5,Msa,PA,130650.510192,131357.750169,131534.457125,132207.362000,132898.297609,133416.990944,133871.009656,134531.472222,135277.796147,135898.475982,136495.234019,137119.432044,137761.306743,138376.998627,139059.883275,139784.708500,140554.881545,141500.482619,142531.479739,143453.936038,144630.503373,145400.035834,146625.696775,147076.529740,148009.545261,148742.627867,149713.284979,151038.581268,152190.057528,153791.049922,155284.879551,157529.327960,159464.713921,160903.094057,162225.286326,164163.206627,165199.489269,166158.923926,167575.911551,169371.808220,171298.758119,173475.157346,175726.447134,177929.685956,180228.294332,181725.545917,183453.651179,184687.533565,186040.996205,187161.828028,188912.814869,191130.413614,194102.766854,197260.099262,200543.272185,204175.357578,206202.558596,207761.629283,209975.098237,212534.702950,214634.437564,215189.346055,217167.135992,219839.874851,223356.514158,226978.675927,230311.031919,233447.607117,236053.196181,238779.502836,240349.017036,242255.513950,242902.433820,243719.502316,245276.206613,247356.302354,249233.989717,251179.096260,252542.454831,253050.444437,253382.483922,253470.398354,252574.169304,252118.702296,251545.354980,250964.759442,252172.290544,252487.771298,254003.925248,254446.681214,254556.946613,253686.799269,253283.811538,253376.753579,252030.373435,250917.242292,249183.474598,249314.495892,249087.783224,249025.272788,247698.238819,246541.603662,245065.047100,243404.545212,241403.818291,239672.238851,237941.968851,235974.823562,234169.720441,233604.222624,233759.494204,233458.795553,232982.730796,232589.811407,231352.846850,230998.831977,230164.510467,230325.627532,230412.113614,229514.193990,229463.463395,228870.733717,229000.622286,230076.175933,230975.559760,230886.406519,229908.562105,228313.147175,225844.645296,223910.157495,221684.777948,220272.839239,219139.242833,218243.238016,217615.962697,216470.520773,215376.925823,214271.292446,213395.584494,212680.510870,210785.523733,209799.397530,208825.717870,207645.000980,206253.891581,205519.633277,206428.028246,206841.460856,206904.101287,206524.852138,205958.376964,205547.882418,205119.163527,204480.121750,204332.504907,203980.895218,204217.525527,204283.212996,205535.899356,206939.879301,208754.246010,209912.815606,210636.412609,210697.921904,211208.452804,211199.883483,211325.151183,211108.131111,211617.334742,212064.085453,212351.701159,212239.766851,213967.133459,214398.564347,213983.491823,213492.533899,213040.121382,212830.451015,213028.766548,213084.006805,Philadelphia,PA,Condo,mid

In [ ]:
csv_file_3 = "/content/gdrive/My Drive/WWCode Python Workshop/Metro_zhvi_uc_sfrcondo_tier_0.67_1.0_sm_sa_month.csv"
data_3 = pd.read_csv(csv_file_3, sep="," )
data_3.head(10)

,RegionID,SizeRank,RegionName,RegionType,StateName,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,2000-06-30,2000-07-31,2000-08-31,2000-09-30,2000-10-31,2000-11-30,2000-12-31,2001-01-31,2001-02-28,2001-03-31,2001-04-30,2001-05-31,2001-06-30,2001-07-31,2001-08-31,2001-09-30,2001-10-31,2001-11-30,2001-12-31,2002-01-31,2002-02-28,2002-03-31,2002-04-30,2002-05-31,2002-06-30,2002-07-31,2002-08-31,2002-09-30,2002-10-31,2002-11-30,2002-12-31,2003-01-31,2003-02-28,2003-03-31,2003-04-30,2003-05-31,2003-06-30,2003-07-31,2003-08-31,2003-09-30,2003-10-31,2003-11-30,2003-12-31,2004-01-31,2004-02-29,2004-03-31,2004-04-30,2004-05-31,2004-06-30,2004-07-31,2004-08-31,2004-09-30,2004-10-31,2004-11-30,2004-12-31,2005-01-31,2005-02-28,2005-03-31,2005-04-30,2005-05-31,2005-06-30,2005-07-31,2005-08-31,2005-09-30,2005-10-31,2005-11-30,2005-12-31,2006-01-31,2006-02-28,2006-03-31,2006-04-30,2006-05-31,2006-06-30,2006-07-31,2006-08-31,2006-09-30,2006-10-31,2006-11-30,2006-12-31,2007-01-31,2007-02-28,2007-03-31,2007-04-30,2007-05-31,2007-06-30,2007-07-31,2007-08-31,2007-09-30,2007-10-31,2007-11-30,2007-12-31,2008-01-31,2008-02-29,2008-03-31,2008-04-30,2008-05-31,2008-06-30,2008-07-31,2008-08-31,2008-09-30,2008-10-31,2008-11-30,2008-12-31,2009-01-31,2009-02-28,2009-03-31,2009-04-30,2009-05-31,2009-06-30,2009-07-31,2009-08-31,2009-09-30,2009-10-31,2009-11-30,2009-12-31,2010-01-31,2010-02-28,2010-03-31,2010-04-30,2010-05-31,2010-06-30,2010-07-31,2010-08-31,2010-09-30,2010-10-31,2010-11-30,2010-12-31,2011-01-31,2011-02-28,2011-03-31,2011-04-30,2011-05-31,2011-06-30,2011-07-31,2011-08-31,2011-09-30,2011-10-31,2011-11-30,2011-12-31,2012-01-31,2012-02-29,2012-03-31,2012-04-30,2012-05-31,2012-06-30,2012-07-31,2012-08-31,2012-09-30,2012-10-31,2012-11-30,2012-12-31,2013-01-31,2013-02-28,2013-03-31,2013-04-30,2013-05-31,2013-06-30,2013-07-31,2013-08-31,2013-09-30,2013-10-31,2013-11-30,2013-12-31,2014-01-31,2014-02-28,2014-03-31,2014-04-30,2014-05-31,2014-06-30,2014-07-31,2014-08-31,2014-09-30,2014-10-31,2014-11-30,2014-12-31,2015-01-31,2015-02-28,2015-03-31,2015-04-30,2015-05-31,2015-06-30,2015-07-31,2015-08-31,2015-09-30,2015-10-31,2015-11-30,2015-12-31,2016-01-31,2016-02-29,2016-03-31,2016-04-30,2016-05-31,2016-06-30,2016-07-31,2016-08-31,2016-09-30,2016-10-31,2016-11-30,2016-12-31,2017-01-31,2017-02-28,2017-03-31,2017-04-30,2017-05-31,2017-06-30,2017-07-31,2017-08-31,2017-09-30,2017-10-31,2017-11-30,2017-12-31,2018-01-31,2018-02-28,2018-03-31,2018-04-30,2018-05-31,2018-06-30,2018-07-31,2018-08-31,2018-09-30,2018-10-31,2018-11-30,2018-12-31,2019-01-31,2019-02-28,2019-03-31,2019-04-30,2019-05-31,2019-06-30,2019-07-31,2019-08-31,2019-09-30,2019-10-31,2019-11-30,2019-12-31,2020-01-31,2020-02-29,2020-03-31,2020-04-30,2020-05-31,2020-06-30,2020-07-31,2020-08-31,2020-09-30,2020-10-31,2020-11-30,2020-12-31,2021-01-31,2021-02-28,2021-03-31,2021-04-30,2021-05-31,2021-06-30,2021-07-31,2021-08-31,2021-09-30,2021-10-31,2021-11-30,2021-12-31,2022-01-31,2022-02-28,2022-03-31,2022-04-30,2022-05-31,2022-06-30
0,102001,0,United States,Country,NaN,245543.0,246335.0,247180.0,248909.0,250663.0,252428.0,254251.0,256184.0,258166.0,260132.0,262093.0,264066.0,265863.0,267580.0,269365.0,271308.0,273230.0,275035.0,276829.0,278699.0,280585.0,282461.0,284174.0,285766.0,287220.0,288755.0,290438.0,292275.0,294249.0,296350.0,298681.0,301159.0,303655.0,306120.0,308477.0,310790.0,312905.0,315045.0,317312.0,319747.0,322309.0,324720.0,327259.0,329937.0,332857.0,335723.0,338398.0,340949.0,343593.0,346557.0,349872.0,353546.0,357691.0,362148.0,366781.0,371308.0,375776.0,380015.0,383867.0,387710.0,391409.0,395398.0,399484.0,404226.0,409055.0,413959.0,418748.0,423583.0,428334.0,432762.0,436467.0,439773.0,442541.0,445226.0,447988.0,450823.0,453479.0,455477.0,456636.0,457285.0,457167.0,456888.0,456351.0,455845.0,455342.0,454939.0,454572.0,454136.0,453153.0,451660.0,449556.0,447432.0,445000.0,442480.0,439640.0,436730.0,433608.0,430042.0,426050.0,421711.0,417349.0,413012.0,408521.0,403782.0,399211.0,394924.0,390661.0,386486.0,382442.0,379330.0,376343.0,373504.0,370720.0,368254.0,366157.0,364075.0,362175.0,360775.0,360372.0,360485.0,360664.0,360579.0,360704.0,361172.0,361439.0,360985.0,359476.0,357496.0,355216.0,353002.0,350794.0,348944.0,347299.0,345871.0,344388.0,342805.0,340967.0,339389.0,338049.0,336801.0,335500.0,334179.0,333281.0,332509.0,332080.0,331821.0,332168.0,332832.0,333859.0,334833.0,335825.0,336707.0,337690.0,339043.0,340792.0,342884.0,345318.0,348032.0,351019.0,354016.0,357107.0,360165.0,363164.0,365910.0,368555.0,371063.0,373515.0,375884.0,378341.0,380714.0,382468.0,383676.0,384633.0,385659.0,386525.0,387013.0,387575.0,388466.0,389817.0,391370.0,392989.0,394744.0,396580.0,398249.0,399895.0,401206.0,402325.0,403441.0,404788.0,406370.0,407933.0,409852.0,411924.0,414021.0,415697.0,417493.0,419188.0,420846.0,422165.0,423485.0,424954.0,426717.0,428716.0,430782.0,432971.0,435161.0,437368.0,439537.0,441625.0,443623.0,445306.0,446991.0,448949.0,451230.0,453690.0,456219.0,458850.0,461700.0,464421.0,466875.0,468962.0,470806.0,472442.0,473964.0,475477.0,477048.0,478592.0,479991.0,481354.0,482532.0,483544.0,484445.0,485243.0,485952.0,486516.0,487234.0,488208.0,489383.0,490545.0,491974.0,493834.0,496083.0,498619.0,500856.0,502015.0,502815.0,504678.0,508613.0,513832.0,519629.0,525576.0,531432.0,537382.0,543730.0,550718.0,558517.0,568280.0,579920.0,592124.0,602802.0,611490.0,618885.0,626063.0,634157.0,643231.0,653377.0,664120.0,675377.0,685292.0,692443.0
1,394913,1,"New York, NY",Msa,NY,398637.0,401008.0,403144.0,407365.0,411308.0,415498.0,419870.0,424405.0,428919.0,433338.0,437544.0,441545.0,445444.0,449749.0,453887.0,458186.0,462296.0,466700.0,470949.0,475346.0,479729.0,484594.0,489089.0,493465.0,497963.0,502250.0,506409.0,510284.0,514505.0,519261.0,524339.0,530603.0,537346.0,544092.0,550138.0,556186.0,562332.0,568621.0,575169.0,580995.0,586847.0,592688.0,598897.0,604732.0,609761.0,614518.0,619097.0,623631.0,628906.0,634297.0,640111.0,645628.0,652165.0,659157.0,667097.0,675067.0,683531.0,691780.0,699555.0,706512.0,713176.0,719769.0,726809.0,735123.0,743968.0,752635.0,760509.0,768425.0,776315.0,784581.0,791832.0,799102.0,805296.0,811712.0,816665.0,821132.0,825079.0,828764.0,830919.0,831111.0,829718.0,826952.0,823581.0,819988.0,816684.0,814445.0,814341.0,814101.0,813758.0,810757.0,807353.0,803894.0,800621.0,798570.0,796234.0,794045.0,792045.0,789877.0,786919.0,783513.0,778284.0,773392.0,767998.0,763498.0,758801.0,753548.0,748004.0,742474.0,736607.0,730892.0,725813.0,720393.0,715884.0,710620.0,706012.0,700797.0,696708.0,693211.0,690835.0,689148.0,688566.0,688793.0,688140.0,687982.0,687473.0,688594.0,689386.0,689690.0,688703.0,686606.0,683711.0,680555.0,678531.0,677021.0,676750.0,675337.0,673974.0,671435.0,669305.0,667345.0,665505.0,663442.0,660929.0,658747.0,656686.0,654771.0,653024.0,651992.0,651464.0,651539.0,651150.0,650777.0,650233.0,650065.0,650477.0,651512.0,653036.0,655029.0,657169.0,659918.0,663400.0,667161.0,670653.0,673608.0,676554.0,679760.0,683228.0,686312.0,690217.0,693799.0,697984.0,701807.0,705421.0,708277.0,710112.0,711695.0,713187.0,714560.0,715725.0,717146.0,718376.0,720100.0,721315.0,723712.0,725725.0,728227.0,729467.0,730178.0,730725.0,731538.0,733749.0,735402.0,736548.0,737449.0,739131.0,741893.0,744273.0,746057.0,747348.0,748367.0,749566.0,751121.0,753095.0,755385.0,758360.0,760729.0,763793.0,766191.0,770066.0,773214.0,776535.0,778990.0,781544.0,783992.0,786289.0,788570.0,791239.0,795075.0,799159.0,803377.0,806277.0,808106.0,808666.0,809144.0,810389.0,812164.0,814542.0,816422.0,817540.0,818181.0,819027.0,819521.0,819780.0,819037.0,818147.0,816372.0,814323.0,812560.0,811477.0,811904.0,812977.0,814650.0,815981.0,817715.0,818164.0,818467.0,819802.0,823634.0,830126.0,837844.0,846048.0,854046.0,860503.0,867032.0,873051.0,879953.0,888195.0,899149.0,911240.0,922791.0,931797.0,938953.0,944437.0,949446.0,955627.0,963209.0,973763.0,985228.0,997405.0,1007429.0
2,753899,2,"Los Angeles-Long Beach-Anaheim, CA",Msa,CA,418030.0,419565.0,421719.0,425833.0,430146.0,434247.0,438441.0,442769.0,446883.0,450683.0,454265.0,458076.0,460997.0,464229.0,467609.0,472288.0,476740.0,480718.0,484799.0,489016.0,493412.0,497701.0,501410.0,505409.0,508653.0,512582.0,517217.0,523170.0,529958.0,536946.0,545829.0,554975.0,564208.0,572437.0,580691.0,588904.0,595773.0,602147.0,609175.0,617076.0,626906.0,634641.0,644802.0,655424.0,668083.0,678479.0,688573.0,698395.0,710052.0,723082.0,738199.0,755499.0,776754.0,797704.0,816032.0,830536.0,844363.0,858056.0,866701.0,876224.0,884887.0,896841.0,909628.0,922450.0,935018.0,946296.0,959876.0,974362.0,989344.0,1004393.0,1014253.0,1024676.0,1033264.0,1041726.0,1049152.0,1055479.0,1063675.0,1069969.0,1071696.0,1073918.0,1070814.0,1071093.0,1068815.0,1068539.0,1068501.0,1067779.0,1065783.0,1062307.0,1056463.0,1051180.0,1041389.0,1030764.0,1017776.0,1005564.0,996616.0,985140.0,974926.0,959636.0,943574.0,922178.0,900852.0,882108.0,866074.0,852473.0,843445.0,832555.0,819979.0,802066.0,789787.0,783122.0,778434.0,773906.0,769425.0,762755.0,757893.0,753958.0,754125.0,755216.0,760227.0,768354.0,771451.0,770568.0,770995.0,776187.0,782511.0,781279.0,776674.0,768474.0,760671.0,753218.0,746545.0,744596.0,743400.0,744285.0,741691.0,739280.0,731446.0,729773.0,728158.0,724500.0,716860.0,709799.0,709657.0,710665.0,709929.0,708900.0,707860.0,709035.0,711289.0,714619.0,719376.0,721851.0,725100.0,730824.0,739097.0,750704.0,761986.0,778001.0,793569.0,810380.0,824137.0,838264.0,850163.0,862686.0,873289.0,881841.0,891645.0,900498.0,910334.0,914339.0,915488.0,913855.0,913678.0,913788.0,915080.0,910439.0,907786.0,907175.0,913443.0,920632.0,929279.0,938276.0,945425.0,948101.0,951475.0,954880.0,955603.0,957305.0,960068.0,968403.0,974731.0,985233.0,992081.0,999327.0,1002263.0,1007466.0,1012454.0,1017027.0,1016652.0,1018335.0,1020770.0,1028802.0,1035149.0,1040404.0,1048457.0,1053745.0,1059361.0,1061673.0,1066927.0,1073255.0,1073905.0,1075585.0,1078355.0,1087524.0,1098020.0,1107006.0,1115458.0,1124334.0,1132936.0,1140661.0,1144844.0,1149553.0,1148383.0,1148884.0,1148654.0,1155131.0,1158306.0,1157419.0,1155450.0,1151862.0,1149429.0,1148383.0,1149626.0,1151098.0,1148690.0,1149763.0,1154139.0,1161775.0,1164477.0,1166805.0,1170969.0,1181005.0,1192326.0,1200461.0,1196208.0,1190512.0,1194092.0,1211175.0,1230406.0,1246745.0,1257682.0,1266774.0,1274251.0,1286092.0,1298695.0,1316645.0,1342793.0,1376069.0,1412813.0,1437986.0,1455843.0,1465340.0,1478065.0,1494391.0,1513668.0,1535803.0,1567369.0,1602289.0,1633180.0,1637952.0
3,394463,3,"Chicago, IL",Msa,IL,297296.0,298057.0,299026.0,300913.0,302873.0,304796.0,306999.0,309569.0,312258.0,314851.0,317159.0,319343.0,321392.0,323164.0,325182.0,327201.0,329647.0,331913.0,334261.0,336730.0,339251.0,341792.0,343903.0,345743.0,347287.0,349038.0,351228.0,353084.0,355093.0,356888.0,359348.0,361916.0,364383.0,366557.0,368087.0,369956.0,371804.0,374061.0,376110.0,378537.0,380565.0,382321.0,383841.0,385947.0,388400.0,390641.0,392594.0,394320.0,396612.0,398726.0,400924.0,403419.0,406166.0,409370.0,412246.0,415304.0,417911.0,420607.0,423292.0,426254.0,429006.0,431869.0,434741.0,438002.0,441376.0,444815.0,448066.0,451236.0,454658.0,457889.0,460635.0,463251.0,465820.0,468312.0,470877.0,473090.0,475520.0,476757.0,477812.0,478490.0,479039.0,479155.0,479123.0,479430.0,480328.0,481223.0,481765.0,481536.0,480816.0,479748.0,478403.0,476996.0,474958.0,473093.0,471370.0,469248.0,467047.0,NaN,NaN,455539.0,NaN,449468.0,448033.0,442706.0,439512.0,433546.0,428676.0,422181.0,414559.0,409196.0,403665.0,401795.0,398299.0,396103.0,393712.0,391520.0,387749.0,384097.0,380436.0,379130.0,377094.0,376507.0,373824.0,374907.0,373487.0,374938.0,370664.0,368433.0,363772.0,361039.0,356145.0,352004.0,347997.0,345150.0,343544.0,341363.0,340749.0,338783.0,338581.0,336551.0,334696.0,330573.0,328379.0,324660.0,322928.0,319335.0,319438.0,319277.0,320492.0,320601.0,319431.0,318203.0,316703.0,317526.0,318338.0,318982.0,320492.0,322688.0,324784.0,327387.0,329861.0,333511.0,336115.0,339224.0,341635.0,345146.0,346498.0,348621.0,349902.0,352647.0,353969.0,354464.0,355326.0,356919.0,358103.0,357897.0,357942.0,358000.0,358614.0,359489.0,360307.0,361428.0,362969.0,365013.0,366311.0,365834.0,365236.0,364453.0,364067.0,363631.0,363636.0,364766.0,366443.0,369456.0,371481.0,372760.0,372937.0,373050.0,373506.0,373705.0,373879.0,374152.0,375363.0,377476.0,380375.0,382894.0,385583.0,387274.0,388337.0,387882.0,387285.0,386937.0,387521.0,388572.0,390172.0,392258.0,394732.0,396659.0,397612.0,397892.0,398078.0,398169.0,398237.0,398163.0,398735.0,399037.0,399890.0,400448.0,400861.0,401589.0,401894.0,402367.0,402085.0,401620.0,401175.0,400749.0,400485.0,400157.0,400040.0,400189.0,400721.0,401338.0,401829.0,401627.0,400975.0,400572.0,401916.0,404395.0,NaN,413103.0,416982.0,419867.0,421649.0,424896.0,427967.0,432576.0,436707.0,442517.0,448926.0,455359.0,460079.0,464125.0,468258.0,472308.0,476080.0,479699.0,484779.0,490458.0,497034.0,502000.0
4,394514,4,"Dallas-Fort Worth, TX",Msa,TX,234357.0,234434.0,234530.0,234782.0,235061.0,235201.0,235371.0,235834.0,236491.0,237204.0,237862.0,238541.0,238794.0,238222.0,237650.0,237357.0,237539.0,237528.0,237536.0,237871.0,238158.0,238343.0,238298.0,238334.0,238374.0,238689.0,239110.0,239833.0,240433.0,241425.0,242310.0,243309.0,243952.0,244488.0,244938.0,245343.0,245608.0,245704.0,245907.0,246166.0,246354.0,246590.0,246632.0,246914.0,247169.0,247539.0,247785.0,247735.0,248835.0,251158.0,NaN,258155.0,259959.0,260631.0,260957.0,261649.0,262359.0,263065.0,263433.0,263700.0,264852.0,265550.0,266329.0,266713.0,267654.0,268620.0,269334.0,270091.0,270820.0,271012.0,271368.0,271326.0,271436.0,271876.0,272507.0,273655.0,274860.0,275923.0,276530.0,276842.0,277362.0,278699.0,279510.0,280353.0,279736.0,278934.0,278140.0,278536.0,279349.0,280078.0,280648.0,281289.0,282163.0,282645.0,282949.0,283230.0,281564.0,279499.0,277077.0,276459.0,276059.0,275735.0,275656.0,274749.0,273361.0,271560.0,270333.0,269552.0,268816.0,268814.0,269067.0,269647.0,269993.0,269863.0,269952.0,269285.0,268921.0,268320.0,269137.0,269740.0,269677.0,269198.0,268843.0,269484.0,269732.0,269788.0,268908.0,267478.0,265706.0,264193.0,262746.0,262024.0,261462.0,260930.0,260355.0,259479.0,259087.0,258480.0,258645.0,258374.0,258376.0,258053.0,257901.0,257309.0,256887.0,257613.0,258820.0,260253.0,261193.0,262095.0,263082.0,263603.0,264130.0,264589.0,265769.0,267038.0,268633.0,270044.0,271869.0,273614.0,275518.0,277473.0,279582.0,281177.0,282885.0,284795.0,287242.0,289484.0,291306.0,293347.0,295194.0,297043.0,298646.0,300683.0,302084.0,303503.0,304500.0,306276.0,308420.0,310826.0,313667.0,316539.0,319756.0,322696.0,325666.0,328529.0,331197.0,332767.0,334090.0,335718.0,338139.0,341087.0,343655.0,346492.0,348830.0,351471.0,354112.0,356528.0,358975.0,360596.0,362363.0,364376.0,367012.0,369841.0,372291.0,374713.0,376421.0,378454.0,380375.0,382525.0,383976.0,385411.0,387366.0,389634.0,391817.0,393721.0,395880.0,398465.0,401094.0,403028.0,404250.0,405203.0,406067.0,407589.0,408889.0,410386.0,411619.0,413252.0,415540.0,416866.0,417389.0,417001.0,416930.0,416789.0,416754.0,417798.0,419692.0,420510.0,420644.0,420011.0,421351.0,422517.0,424289.0,424915.0,425461.0,426358.0,428102.0,431964.0,436260.0,441404.0,445238.0,449334.0,452777.0,458134.0,464586.0,473623.0,484209.0,496526.0,509893.0,523100.0,534921.0,544842.0,554125.0,564138.0,576694.0,590521.0,603449.0,619272.0,634075.0,647002.0
5,394974,5,"Philadelphia, PA",Msa,PA,226122.0,226965.0,227465.0,228725.0,229810.0,231072.0,232262.0,233420.0,234633.0,235828.0,236981.0,238034.0,239139.0,240387.0,241835.0,243296.0,244705.0,246121.0,247806.0,249630.0,251613.0,253369.0,255212.0,256603.0,258071.0,259471.0,261305.0,263417.0,265599.0,268013.0,270474.0,273619.0,276919.0,280267.0,283019.0,285775.0,288305.0,290800.0,293225.0,295909.0,298979.0,302259.0,305817.0,309380.0,312930.0,316123.0,319234.0,321806.0,324336.0,326670.0,329463.0,332649.0,336562.0,340894.0,345608.0,350441.0,354683.0,358087.0,360884.0,364078.0,367731.0,370862.0,373673.0,376692.0,380861.0,385676.0,390541.0,395053.0,399133.0,403252.0,406769.0,410080.0,412453.0,414875.0,417371.0,420245.0,423021.0,425459.0,427371.0,428510.0,428841.0,428949.0,428637.0,428100.0,427231.0,426911.0,427500.0,428208.0,429379.0,429737.0,429913.0,428854.0,427629.0,426669.0,425879.0,424841.0,423056.0,422210.0,421901.0,422059.0,420772.0,418612.0,415621.0,412681.0,409455.0,406321.0,403447.0,400837.0,398552.0,397031.0,396448.0,396119.0,395162.0,393574.0,391352.0,389245.0,387209.0,386205.0,385913.0,385925.0,386051.0,385984.0,386025.0,386258.0,386716.0,386945.0,386208.0,384374.0,381827.0,378875.0,375810.0,373442.0,371759.0,370914.0,370043.0,368693.0,366744.0,364489.0,362511.0,360892.0,359211.0,357619.0,356156.0,355098.0,354042.0,353118.0,352797.0,352893.0,352855.0,352204.0,351243.0,350393.0,349868.0,349482.0,349398.0,349426.0,350115.0,350949.0,352089.0,353315.0,354997.0,356787.0,358499.0,359527.0,360790.0,361713.0,362911.0,363658.0,364829.0,366013.0,366717.0,366593.0,366689.0,367180.0,367773.0,367710.0,367476.0,367305.0,367528.0,367956.0,368351.0,368586.0,368978.0,369634.0,370099.0,370224.0,370263.0,370420.0,370515.0,370483.0,370492.0,370588.0,370998.0,371581.0,372003.0,372420.0,372789.0,373705.0,374365.0,375129.0,375672.0,376544.0,377236.0,378389.0,379913.0,381367.0,382520.0,383467.0,384500.0,385245.0,385670.0,386206.0,386963.0,388269.0,389740.0,391492.0,393070.0,394889.0,397165.0,399345.0,400812.0,401375.0,401709.0,402256.0,403194.0,404194.0,405713.0,407183.0,408634.0,409653.0,410880.0,411767.0,412369.0,412331.0,412680.0,413272.0,413886.0,414455.0,415196.0,416443.0,417802.0,419150.0,419670.0,421015.0,422130.0,424012.0,426176.0,429739.0,434361.0,439943.0,445428.0,451212.0,456235.0,461122.0,466290.0,471956.0,479431.0,487519.0,494980.0,500840.0,505376.0,509380.0,513261.0,517013.0,521223.0,525862.0,531756.0,538417.0,545781.0,551288.0

In [ ]:
data_3=data_3.drop(data_3.index[0])

In [ ]:
data_3.shape

(907, 275)

In [ ]:
data_3.dtypes

RegionID        int64
SizeRank        int64
RegionName     object
RegionType     object
StateName      object
               ...
2022-02-28    float64
2022-03-31    float64
2022-04-30    float64
2022-05-31    float64
2022-06-30    float64
Length: 275, dtype: object

In [ ]:
data_2.columns

Index(['RegionID', 'SizeRank', 'RegionType', 'StateName', '2000-01-31',
       '2000-02-29', '2000-03-31', '2000-04-30', '2000-05-31', '2000-06-30',
       ...
       '2014-07-31', '2014-08-31', '2014-09-30', '2014-10-31', '2014-11-30',
       '2014-12-31', 'City ', 'State', 'house_type', 'cost_percentile_range'],
      dtype='object', length=188)

In [ ]:
data_3 = data_3.drop(data_3.columns[data_3.columns.str.contains(pat = '2022')], axis='columns')

In [ ]:
data_3.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,2000-06-30,2000-07-31,2000-08-31,2000-09-30,2000-10-31,2000-11-30,2000-12-31,2001-01-31,2001-02-28,2001-03-31,2001-04-30,2001-05-31,2001-06-30,2001-07-31,2001-08-31,2001-09-30,2001-10-31,2001-11-30,2001-12-31,2002-01-31,2002-02-28,2002-03-31,2002-04-30,2002-05-31,2002-06-30,2002-07-31,2002-08-31,2002-09-30,2002-10-31,2002-11-30,2002-12-31,2003-01-31,2003-02-28,2003-03-31,2003-04-30,2003-05-31,2003-06-30,2003-07-31,2003-08-31,2003-09-30,2003-10-31,2003-11-30,2003-12-31,2004-01-31,2004-02-29,2004-03-31,2004-04-30,2004-05-31,2004-06-30,2004-07-31,2004-08-31,2004-09-30,2004-10-31,2004-11-30,2004-12-31,2005-01-31,2005-02-28,2005-03-31,2005-04-30,2005-05-31,2005-06-30,2005-07-31,2005-08-31,2005-09-30,2005-10-31,2005-11-30,2005-12-31,2006-01-31,2006-02-28,2006-03-31,2006-04-30,2006-05-31,2006-06-30,2006-07-31,2006-08-31,2006-09-30,2006-10-31,2006-11-30,2006-12-31,2007-01-31,2007-02-28,2007-03-31,2007-04-30,2007-05-31,2007-06-30,2007-07-31,2007-08-31,2007-09-30,2007-10-31,2007-11-30,2007-12-31,2008-01-31,2008-02-29,2008-03-31,2008-04-30,2008-05-31,2008-06-30,2008-07-31,2008-08-31,2008-09-30,2008-10-31,2008-11-30,2008-12-31,2009-01-31,2009-02-28,2009-03-31,2009-04-30,2009-05-31,2009-06-30,2009-07-31,2009-08-31,2009-09-30,2009-10-31,2009-11-30,2009-12-31,2010-01-31,2010-02-28,2010-03-31,2010-04-30,2010-05-31,2010-06-30,2010-07-31,2010-08-31,2010-09-30,2010-10-31,2010-11-30,2010-12-31,2011-01-31,2011-02-28,2011-03-31,2011-04-30,2011-05-31,2011-06-30,2011-07-31,2011-08-31,2011-09-30,2011-10-31,2011-11-30,2011-12-31,2012-01-31,2012-02-29,2012-03-31,2012-04-30,2012-05-31,2012-06-30,2012-07-31,2012-08-31,2012-09-30,2012-10-31,2012-11-30,2012-12-31,2013-01-31,2013-02-28,2013-03-31,2013-04-30,2013-05-31,2013-06-30,2013-07-31,2013-08-31,2013-09-30,2013-10-31,2013-11-30,2013-12-31,2014-01-31,2014-02-28,2014-03-31,2014-04-30,2014-05-31,2014-06-30,2014-07-31,2014-08-31,2014-09-30,2014-10-31,2014-11-30,2014-12-31
1,394913,1,"New York, NY",Msa,NY,398637.0,401008.0,403144.0,407365.0,411308.0,415498.0,419870.0,424405.0,428919.0,433338.0,437544.0,441545.0,445444.0,449749.0,453887.0,458186.0,462296.0,466700.0,470949.0,475346.0,479729.0,484594.0,489089.0,493465.0,497963.0,502250.0,506409.0,510284.0,514505.0,519261.0,524339.0,530603.0,537346.0,544092.0,550138.0,556186.0,562332.0,568621.0,575169.0,580995.0,586847.0,592688.0,598897.0,604732.0,609761.0,614518.0,619097.0,623631.0,628906.0,634297.0,640111.0,645628.0,652165.0,659157.0,667097.0,675067.0,683531.0,691780.0,699555.0,706512.0,713176.0,719769.0,726809.0,735123.0,743968.0,752635.0,760509.0,768425.0,776315.0,784581.0,791832.0,799102.0,805296.0,811712.0,816665.0,821132.0,825079.0,828764.0,830919.0,831111.0,829718.0,826952.0,823581.0,819988.0,816684.0,814445.0,814341.0,814101.0,813758.0,810757.0,807353.0,803894.0,800621.0,798570.0,796234.0,794045.0,792045.0,789877.0,786919.0,783513.0,778284.0,773392.0,767998.0,763498.0,758801.0,753548.0,748004.0,742474.0,736607.0,730892.0,725813.0,720393.0,715884.0,710620.0,706012.0,700797.0,696708.0,693211.0,690835.0,689148.0,688566.0,688793.0,688140.0,687982.0,687473.0,688594.0,689386.0,689690.0,688703.0,686606.0,683711.0,680555.0,678531.0,677021.0,676750.0,675337.0,673974.0,671435.0,669305.0,667345.0,665505.0,663442.0,660929.0,658747.0,656686.0,654771.0,653024.0,651992.0,651464.0,651539.0,651150.0,650777.0,650233.0,650065.0,650477.0,651512.0,653036.0,655029.0,657169.0,659918.0,663400.0,667161.0,670653.0,673608.0,676554.0,679760.0,683228.0,686312.0,690217.0,693799.0,697984.0,701807.0,705421.0,708277.0,710112.0,711695.0,713187.0,714560.0,715725.0,717146.0
2,753899,2,"Los Angeles-Long Beach-Anaheim, CA",Msa,CA,418030.0,419565.0,421719.0,425833.0,430146.0,434247.0,438441.0,442769.0,446883.0,450683.0,454265.0,458076.0,460997.0,464229.0,467609.0,472288.0,476740.0,480718.0,484799.0,489016.0,493412.0,497701.0,501410.0,505409.0,508653.0,512582.0,517217.0,523170.0,529958.0,536946.0,545829.0,554975.0,564208.0,572437.0,580691.0,588904.0,595773.0,602147.0,609175.0,617076.0,626906.0,634641.0,644802.0,655424.0,668083.0,678479.0,688573.0,698395.0,710052.0,723082.0,738199.0,755499.0,776754.0,797704.0,816032.0,830536.0,844363.0,858056.0,866701.0,876224.0,884887.0,896841.0,909628.0,922450.0,935018.0,946296.0,959876.0,974362.0,989344.0,1004393.0,1014253.0,1024676.0,1033264.0,1041726.0,1049152.0,1055479.0,1063675.0,1069969.0,1071696.0,1073918.0,1070814.0,1071093.0,1068815.0,1068539.0,1068501.0,1067779.0,1065783.0,1062307.0,1056463.0,1051180.0,1041389.0,1030764.0,1017776.0,1005564.0,996616.0,985140.0,974926.0,959636.0,943574.0,922178.0,900852.0,882108.0,866074.0,852473.0,843445.0,832555.0,819979.0,802066.0,789787.0,783122.0,778434.0,773906.0,769425.0,762755.0,757893.0,753958.0,754125.0,755216.0,760227.0,768354.0,771451.0,770568.0,770995.0,776187.0,782511.0,781279.0,776674.0,768474.0,760671.0,753218.0,746545.0,744596.0,743400.0,744285.0,741691.0,739280.0,731446.0,729773.0,728158.0,724500.0,716860.0,709799.0,709657.0,710665.0,709929.0,708900.0,707860.0,709035.0,711289.0,714619.0,719376.0,721851.0,725100.0,730824.0,739097.0,750704.0,761986.0,778001.0,793569.0,810380.0,824137.0,838264.0,850163.0,862686.0,873289.0,881841.0,891645.0,900498.0,910334.0,914339.0,915488.0,913855.0,913678.0,913788.0,915080.0,910439.0,907786.0,907175.0,913443.0,920632.0
3,394463,3,"Chicago, IL",Msa,IL,297296.0,298057.0,299026.0,300913.0,302873.0,304796.0,306999.0,309569.0,312258.0,314851.0,317159.0,319343.0,321392.0,323164.0,325182.0,327201.0,329647.0,331913.0,334261.0,336730.0,339251.0,341792.0,343903.0,345743.0,347287.0,349038.0,351228.0,353084.0,355093.0,356888.0,359348.0,361916.0,364383.0,366557.0,368087.0,369956.0,371804.0,374061.0,376110.0,378537.0,380565.0,382321.0,383841.0,385947.0,388400.0,390641.0,392594.0,394320.0,396612.0,398726.0,400924.0,403419.0,406166.0,409370.0,412246.0,415304.0,417911.0,420607.0,423292.0,426254.0,429006.0,431869.0,434741.0,438002.0,441376.0,444815.0,448066.0,451236.0,454658.0,457889.0,460635.0,463251.0,465820.0,468312.0,470877.0,473090.0,475520.0,476757.0,477812.0,478490.0,479039.0,479155.0,479123.0,479430.0,480328.0,481223.0,481765.0,481536.0,480816.0,479748.0,478403.0,476996.0,474958.0,473093.0,471370.0,469248.0,467047.0,NaN,NaN,455539.0,NaN,449468.0,448033.0,442706.0,439512.0,433546.0,428676.0,422181.0,414559.0,409196.0,403665.0,401795.0,398299.0,396103.0,393712.0,391520.0,387749.0,384097.0,380436.0,379130.0,377094.0,376507.0,373824.0,374907.0,373487.0,374938.0,370664.0,368433.0,363772.0,361039.0,356145.0,352004.0,347997.0,345150.0,343544.0,341363.0,340749.0,338783.0,338581.0,336551.0,334696.0,330573.0,328379.0,324660.0,322928.0,319335.0,319438.0,319277.0,320492.0,320601.0,319431.0,318203.0,316703.0,317526.0,318338.0,318982.0,320492.0,322688.0,324784.0,327387.0,329861.0,333511.0,336115.0,339224.0,341635.0,345146.0,346498.0,348621.0,349902.0,352647.0,353969.0,354464.0,355326.0,356919.0,358103.0,357897.0,357942.0,358000.0,358614.0,359489.0
4,394514,4,"Dallas-Fort Worth, TX",Msa,TX,234357.0,234434.0,234530.0,234782.0,235061.0,235201.0,235371.0,235834.0,236491.0,237204.0,237862.0,238541.0,238794.0,238222.0,237650.0,237357.0,237539.0,237528.0,237536.0,237871.0,238158.0,238343.0,238298.0,238334.0,238374.0,238689.0,239110.0,239833.0,240433.0,241425.0,242310.0,243309.0,243952.0,244488.0,244938.0,245343.0,245608.0,245704.0,245907.0,246166.0,246354.0,246590.0,246632.0,246914.0,247169.0,247539.0,247785.0,247735.0,248835.0,251158.0,NaN,258155.0,259959.0,260631.0,260957.0,261649.0,262359.0,263065.0,263433.0,263700.0,264852.0,265550.0,266329.0,266713.0,267654.0,268620.0,269334.0,270091.0,270820.0,271012.0,271368.0,271326.0,271436.0,271876.0,272507.0,273655.0,274860.0,275923.0,276530.0,276842.0,277362.0,278699.0,279510.0,280353.0,279736.0,278934.0,278140.0,278536.0,279349.0,280078.0,280648.0,281289.0,282163.0,282645.0,282949.0,283230.0,281564.0,279499.0,277077.0,276459.0,276059.0,275735.0,275656.0,274749.0,273361.0,271560.0,270333.0,269552.0,268816.0,268814.0,269067.0,269647.0,269993.0,269863.0,269952.0,269285.0,268921.0,268320.0,269137.0,269740.0,269677.0,269198.0,268843.0,269484.0,269732.0,269788.0,268908.0,267478.0,265706.0,264193.0,262746.0,262024.0,261462.0,260930.0,260355.0,259479.0,259087.0,258480.0,258645.0,258374.0,258376.0,258053.0,257901.0,257309.0,256887.0,257613.0,258820.0,260253.0,261193.0,262095.0,263082.0,263603.0,264130.0,264589.0,265769.0,267038.0,268633.0,270044.0,271869.0,273614.0,275518.0,277473.0,279582.0,281177.0,282885.0,284795.0,287242.0,289484.0,291306.0,293347.0,295194.0,297043.0,298646.0,300683.0,302084.0,303503.0,304500.0,306276.0,308420.0,310826.0
5,394974,5,"Philadelphia, PA",Msa,PA,226122.0,226965.0,227465.0,228725.0,229810.0,231072.0,232262.0,233420.0,234633.0,235828.0,236981.0,238034.0,239139.0,240387.0,241835.0,243296.0,244705.0,246121.0,247806.0,249630.0,251613.0,253369.0,255212.0,256603.0,258071.0,259471.0,261305.0,263417.0,265599.0,268013.0,270474.0,273619.0,276919.0,280267.0,283019.0,285775.0,288305.0,290800.0,293225.0,295909.0,298979.0,302259.0,305817.0,309380.0,312930.0,316123.0,319234.0,321806.0,324336.0,326670.0,329463.0,332649.0,336562.0,340894.0,345608.0,350441.0,354683.0,358087.0,360884.0,364078.0,367731.0,370862.0,373673.0,376692.0,380861.0,385676.0,390541.0,395053.0,399133.0,403252.0,406769.0,410080.0,412453.0,414875.0,417371.0,420245.0,423021.0,425459.0,427371.0,428510.0,428841.0,428949.0,428637.0,428100.0,427231.0,426911.0,427500.0,428208.0,429379.0,429737.0,429913.0,428854.0,427629.0,426669.0,425879.0,424841.0,423056.0,422210.0,421901.0,422059.0,420772.0,418612.0,415621.0,412681.0,409455.0,406321.0,403447.0,400837.0,398552.0,397031.0,396448.0,396119.0,395162.0,393574.0,391352.0,389245.0,387209.0,386205.0,385913.0,385925.0,386051.0,385984.0,386025.0,386258.0,386716.0,386945.0,386208.0,384374.0,381827.0,378875.0,375810.0,373442.0,371759.0,370914.0,370043.0,368693.0,366744.0,364489.0,362511.0,360892.0,359211.0,357619.0,356156.0,355098.0,354042.0,353118.0,352797.0,352893.0,352855.0,352204.0,351243.0,350393.0,349868.0,349482.0,349398.0,349426.0,350115.0,350949.0,352089.0,353315.0,354997.0,356787.0,358499.0,359527.0,360790.0,361713.0,362911.0,363658.0,364829.0,366013.0,366717.0,366593.0,366689.0,367180.0,367773.0,367710.0,367476.0,367305.0,367528.0,367956.0

In [ ]:
data_3.shape

(907, 185)

In [ ]:
new = data_3["RegionName"].str.split(", ", n = 1, expand = True)
 
# making separate first name column from new data frame
data_3["City "]= new[0]
 
# making separate last name column from new data frame
data_3["State"]= new[1]
 
# Dropping old Name columns
data_3.drop(columns =["RegionName"], inplace = True)

data_3.head()

,RegionID,SizeRank,RegionType,StateName,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,2000-06-30,2000-07-31,2000-08-31,2000-09-30,2000-10-31,2000-11-30,2000-12-31,2001-01-31,2001-02-28,2001-03-31,2001-04-30,2001-05-31,2001-06-30,2001-07-31,2001-08-31,2001-09-30,2001-10-31,2001-11-30,2001-12-31,2002-01-31,2002-02-28,2002-03-31,2002-04-30,2002-05-31,2002-06-30,2002-07-31,2002-08-31,2002-09-30,2002-10-31,2002-11-30,2002-12-31,2003-01-31,2003-02-28,2003-03-31,2003-04-30,2003-05-31,2003-06-30,2003-07-31,2003-08-31,2003-09-30,2003-10-31,2003-11-30,2003-12-31,2004-01-31,2004-02-29,2004-03-31,2004-04-30,2004-05-31,2004-06-30,2004-07-31,2004-08-31,2004-09-30,2004-10-31,2004-11-30,2004-12-31,2005-01-31,2005-02-28,2005-03-31,2005-04-30,2005-05-31,2005-06-30,2005-07-31,2005-08-31,2005-09-30,2005-10-31,2005-11-30,2005-12-31,2006-01-31,2006-02-28,2006-03-31,2006-04-30,2006-05-31,2006-06-30,2006-07-31,2006-08-31,2006-09-30,2006-10-31,2006-11-30,2006-12-31,2007-01-31,2007-02-28,2007-03-31,2007-04-30,2007-05-31,2007-06-30,2007-07-31,2007-08-31,2007-09-30,2007-10-31,2007-11-30,2007-12-31,2008-01-31,2008-02-29,2008-03-31,2008-04-30,2008-05-31,2008-06-30,2008-07-31,2008-08-31,2008-09-30,2008-10-31,2008-11-30,2008-12-31,2009-01-31,2009-02-28,2009-03-31,2009-04-30,2009-05-31,2009-06-30,2009-07-31,2009-08-31,2009-09-30,2009-10-31,2009-11-30,2009-12-31,2010-01-31,2010-02-28,2010-03-31,2010-04-30,2010-05-31,2010-06-30,2010-07-31,2010-08-31,2010-09-30,2010-10-31,2010-11-30,2010-12-31,2011-01-31,2011-02-28,2011-03-31,2011-04-30,2011-05-31,2011-06-30,2011-07-31,2011-08-31,2011-09-30,2011-10-31,2011-11-30,2011-12-31,2012-01-31,2012-02-29,2012-03-31,2012-04-30,2012-05-31,2012-06-30,2012-07-31,2012-08-31,2012-09-30,2012-10-31,2012-11-30,2012-12-31,2013-01-31,2013-02-28,2013-03-31,2013-04-30,2013-05-31,2013-06-30,2013-07-31,2013-08-31,2013-09-30,2013-10-31,2013-11-30,2013-12-31,2014-01-31,2014-02-28,2014-03-31,2014-04-30,2014-05-31,2014-06-30,2014-07-31,2014-08-31,2014-09-30,2014-10-31,2014-11-30,2014-12-31,City,State
1,394913,1,Msa,NY,398637.0,401008.0,403144.0,407365.0,411308.0,415498.0,419870.0,424405.0,428919.0,433338.0,437544.0,441545.0,445444.0,449749.0,453887.0,458186.0,462296.0,466700.0,470949.0,475346.0,479729.0,484594.0,489089.0,493465.0,497963.0,502250.0,506409.0,510284.0,514505.0,519261.0,524339.0,530603.0,537346.0,544092.0,550138.0,556186.0,562332.0,568621.0,575169.0,580995.0,586847.0,592688.0,598897.0,604732.0,609761.0,614518.0,619097.0,623631.0,628906.0,634297.0,640111.0,645628.0,652165.0,659157.0,667097.0,675067.0,683531.0,691780.0,699555.0,706512.0,713176.0,719769.0,726809.0,735123.0,743968.0,752635.0,760509.0,768425.0,776315.0,784581.0,791832.0,799102.0,805296.0,811712.0,816665.0,821132.0,825079.0,828764.0,830919.0,831111.0,829718.0,826952.0,823581.0,819988.0,816684.0,814445.0,814341.0,814101.0,813758.0,810757.0,807353.0,803894.0,800621.0,798570.0,796234.0,794045.0,792045.0,789877.0,786919.0,783513.0,778284.0,773392.0,767998.0,763498.0,758801.0,753548.0,748004.0,742474.0,736607.0,730892.0,725813.0,720393.0,715884.0,710620.0,706012.0,700797.0,696708.0,693211.0,690835.0,689148.0,688566.0,688793.0,688140.0,687982.0,687473.0,688594.0,689386.0,689690.0,688703.0,686606.0,683711.0,680555.0,678531.0,677021.0,676750.0,675337.0,673974.0,671435.0,669305.0,667345.0,665505.0,663442.0,660929.0,658747.0,656686.0,654771.0,653024.0,651992.0,651464.0,651539.0,651150.0,650777.0,650233.0,650065.0,650477.0,651512.0,653036.0,655029.0,657169.0,659918.0,663400.0,667161.0,670653.0,673608.0,676554.0,679760.0,683228.0,686312.0,690217.0,693799.0,697984.0,701807.0,705421.0,708277.0,710112.0,711695.0,713187.0,714560.0,715725.0,717146.0,New York,NY
2,753899,2,Msa,CA,418030.0,419565.0,421719.0,425833.0,430146.0,434247.0,438441.0,442769.0,446883.0,450683.0,454265.0,458076.0,460997.0,464229.0,467609.0,472288.0,476740.0,480718.0,484799.0,489016.0,493412.0,497701.0,501410.0,505409.0,508653.0,512582.0,517217.0,523170.0,529958.0,536946.0,545829.0,554975.0,564208.0,572437.0,580691.0,588904.0,595773.0,602147.0,609175.0,617076.0,626906.0,634641.0,644802.0,655424.0,668083.0,678479.0,688573.0,698395.0,710052.0,723082.0,738199.0,755499.0,776754.0,797704.0,816032.0,830536.0,844363.0,858056.0,866701.0,876224.0,884887.0,896841.0,909628.0,922450.0,935018.0,946296.0,959876.0,974362.0,989344.0,1004393.0,1014253.0,1024676.0,1033264.0,1041726.0,1049152.0,1055479.0,1063675.0,1069969.0,1071696.0,1073918.0,1070814.0,1071093.0,1068815.0,1068539.0,1068501.0,1067779.0,1065783.0,1062307.0,1056463.0,1051180.0,1041389.0,1030764.0,1017776.0,1005564.0,996616.0,985140.0,974926.0,959636.0,943574.0,922178.0,900852.0,882108.0,866074.0,852473.0,843445.0,832555.0,819979.0,802066.0,789787.0,783122.0,778434.0,773906.0,769425.0,762755.0,757893.0,753958.0,754125.0,755216.0,760227.0,768354.0,771451.0,770568.0,770995.0,776187.0,782511.0,781279.0,776674.0,768474.0,760671.0,753218.0,746545.0,744596.0,743400.0,744285.0,741691.0,739280.0,731446.0,729773.0,728158.0,724500.0,716860.0,709799.0,709657.0,710665.0,709929.0,708900.0,707860.0,709035.0,711289.0,714619.0,719376.0,721851.0,725100.0,730824.0,739097.0,750704.0,761986.0,778001.0,793569.0,810380.0,824137.0,838264.0,850163.0,862686.0,873289.0,881841.0,891645.0,900498.0,910334.0,914339.0,915488.0,913855.0,913678.0,913788.0,915080.0,910439.0,907786.0,907175.0,913443.0,920632.0,Los Angeles-Long Beach-Anaheim,CA
3,394463,3,Msa,IL,297296.0,298057.0,299026.0,300913.0,302873.0,304796.0,306999.0,309569.0,312258.0,314851.0,317159.0,319343.0,321392.0,323164.0,325182.0,327201.0,329647.0,331913.0,334261.0,336730.0,339251.0,341792.0,343903.0,345743.0,347287.0,349038.0,351228.0,353084.0,355093.0,356888.0,359348.0,361916.0,364383.0,366557.0,368087.0,369956.0,371804.0,374061.0,376110.0,378537.0,380565.0,382321.0,383841.0,385947.0,388400.0,390641.0,392594.0,394320.0,396612.0,398726.0,400924.0,403419.0,406166.0,409370.0,412246.0,415304.0,417911.0,420607.0,423292.0,426254.0,429006.0,431869.0,434741.0,438002.0,441376.0,444815.0,448066.0,451236.0,454658.0,457889.0,460635.0,463251.0,465820.0,468312.0,470877.0,473090.0,475520.0,476757.0,477812.0,478490.0,479039.0,479155.0,479123.0,479430.0,480328.0,481223.0,481765.0,481536.0,480816.0,479748.0,478403.0,476996.0,474958.0,473093.0,471370.0,469248.0,467047.0,NaN,NaN,455539.0,NaN,449468.0,448033.0,442706.0,439512.0,433546.0,428676.0,422181.0,414559.0,409196.0,403665.0,401795.0,398299.0,396103.0,393712.0,391520.0,387749.0,384097.0,380436.0,379130.0,377094.0,376507.0,373824.0,374907.0,373487.0,374938.0,370664.0,368433.0,363772.0,361039.0,356145.0,352004.0,347997.0,345150.0,343544.0,341363.0,340749.0,338783.0,338581.0,336551.0,334696.0,330573.0,328379.0,324660.0,322928.0,319335.0,319438.0,319277.0,320492.0,320601.0,319431.0,318203.0,316703.0,317526.0,318338.0,318982.0,320492.0,322688.0,324784.0,327387.0,329861.0,333511.0,336115.0,339224.0,341635.0,345146.0,346498.0,348621.0,349902.0,352647.0,353969.0,354464.0,355326.0,356919.0,358103.0,357897.0,357942.0,358000.0,358614.0,359489.0,Chicago,IL
4,394514,4,Msa,TX,234357.0,234434.0,234530.0,234782.0,235061.0,235201.0,235371.0,235834.0,236491.0,237204.0,237862.0,238541.0,238794.0,238222.0,237650.0,237357.0,237539.0,237528.0,237536.0,237871.0,238158.0,238343.0,238298.0,238334.0,238374.0,238689.0,239110.0,239833.0,240433.0,241425.0,242310.0,243309.0,243952.0,244488.0,244938.0,245343.0,245608.0,245704.0,245907.0,246166.0,246354.0,246590.0,246632.0,246914.0,247169.0,247539.0,247785.0,247735.0,248835.0,251158.0,NaN,258155.0,259959.0,260631.0,260957.0,261649.0,262359.0,263065.0,263433.0,263700.0,264852.0,265550.0,266329.0,266713.0,267654.0,268620.0,269334.0,270091.0,270820.0,271012.0,271368.0,271326.0,271436.0,271876.0,272507.0,273655.0,274860.0,275923.0,276530.0,276842.0,277362.0,278699.0,279510.0,280353.0,279736.0,278934.0,278140.0,278536.0,279349.0,280078.0,280648.0,281289.0,282163.0,282645.0,282949.0,283230.0,281564.0,279499.0,277077.0,276459.0,276059.0,275735.0,275656.0,274749.0,273361.0,271560.0,270333.0,269552.0,268816.0,268814.0,269067.0,269647.0,269993.0,269863.0,269952.0,269285.0,268921.0,268320.0,269137.0,269740.0,269677.0,269198.0,268843.0,269484.0,269732.0,269788.0,268908.0,267478.0,265706.0,264193.0,262746.0,262024.0,261462.0,260930.0,260355.0,259479.0,259087.0,258480.0,258645.0,258374.0,258376.0,258053.0,257901.0,257309.0,256887.0,257613.0,258820.0,260253.0,261193.0,262095.0,263082.0,263603.0,264130.0,264589.0,265769.0,267038.0,268633.0,270044.0,271869.0,273614.0,275518.0,277473.0,279582.0,281177.0,282885.0,284795.0,287242.0,289484.0,291306.0,293347.0,295194.0,297043.0,298646.0,300683.0,302084.0,303503.0,304500.0,306276.0,308420.0,310826.0,Dallas-Fort Worth,TX
5,394974,5,Msa,PA,226122.0,226965.0,227465.0,228725.0,229810.0,231072.0,232262.0,233420.0,234633.0,235828.0,236981.0,238034.0,239139.0,240387.0,241835.0,243296.0,244705.0,246121.0,247806.0,249630.0,251613.0,253369.0,255212.0,256603.0,258071.0,259471.0,261305.0,263417.0,265599.0,268013.0,270474.0,273619.0,276919.0,280267.0,283019.0,285775.0,288305.0,290800.0,293225.0,295909.0,298979.0,302259.0,305817.0,309380.0,312930.0,316123.0,319234.0,321806.0,324336.0,326670.0,329463.0,332649.0,336562.0,340894.0,345608.0,350441.0,354683.0,358087.0,360884.0,364078.0,367731.0,370862.0,373673.0,376692.0,380861.0,385676.0,390541.0,395053.0,399133.0,403252.0,406769.0,410080.0,412453.0,414875.0,417371.0,420245.0,423021.0,425459.0,427371.0,428510.0,428841.0,428949.0,428637.0,428100.0,427231.0,426911.0,427500.0,428208.0,429379.0,429737.0,429913.0,428854.0,427629.0,426669.0,425879.0,424841.0,423056.0,422210.0,421901.0,422059.0,420772.0,418612.0,415621.0,412681.0,409455.0,406321.0,403447.0,400837.0,398552.0,397031.0,396448.0,396119.0,395162.0,393574.0,391352.0,389245.0,387209.0,386205.0,385913.0,385925.0,386051.0,385984.0,386025.0,386258.0,386716.0,386945.0,386208.0,384374.0,381827.0,378875.0,375810.0,373442.0,371759.0,370914.0,370043.0,368693.0,366744.0,364489.0,362511.0,360892.0,359211.0,357619.0,356156.0,355098.0,354042.0,353118.0,352797.0,352893.0,352855.0,352204.0,351243.0,350393.0,349868.0,349482.0,349398.0,349426.0,350115.0,350949.0,352089.0,353315.0,354997.0,356787.0,358499.0,359527.0,360790.0,361713.0,362911.0,363658.0,364829.0,366013.0,366717.0,366593.0,366689.0,367180.0,367773.0,367710.0,367476.0,367305.0,367528.0,367956.0,Philadelphia,PA

In [ ]:
data_3['house_type']='Condo'
data_3['cost_percentile_range']='high' #high is between > 65 percentile
data_3.head()

,RegionID,SizeRank,RegionType,StateName,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,2000-06-30,2000-07-31,2000-08-31,2000-09-30,2000-10-31,2000-11-30,2000-12-31,2001-01-31,2001-02-28,2001-03-31,2001-04-30,2001-05-31,2001-06-30,2001-07-31,2001-08-31,2001-09-30,2001-10-31,2001-11-30,2001-12-31,2002-01-31,2002-02-28,2002-03-31,2002-04-30,2002-05-31,2002-06-30,2002-07-31,2002-08-31,2002-09-30,2002-10-31,2002-11-30,2002-12-31,2003-01-31,2003-02-28,2003-03-31,2003-04-30,2003-05-31,2003-06-30,2003-07-31,2003-08-31,2003-09-30,2003-10-31,2003-11-30,2003-12-31,2004-01-31,2004-02-29,2004-03-31,2004-04-30,2004-05-31,2004-06-30,2004-07-31,2004-08-31,2004-09-30,2004-10-31,2004-11-30,2004-12-31,2005-01-31,2005-02-28,2005-03-31,2005-04-30,2005-05-31,2005-06-30,2005-07-31,2005-08-31,2005-09-30,2005-10-31,2005-11-30,2005-12-31,2006-01-31,2006-02-28,2006-03-31,2006-04-30,2006-05-31,2006-06-30,2006-07-31,2006-08-31,2006-09-30,2006-10-31,2006-11-30,2006-12-31,2007-01-31,2007-02-28,2007-03-31,2007-04-30,2007-05-31,2007-06-30,2007-07-31,2007-08-31,2007-09-30,2007-10-31,2007-11-30,2007-12-31,2008-01-31,2008-02-29,2008-03-31,2008-04-30,2008-05-31,2008-06-30,2008-07-31,2008-08-31,2008-09-30,2008-10-31,2008-11-30,2008-12-31,2009-01-31,2009-02-28,2009-03-31,2009-04-30,2009-05-31,2009-06-30,2009-07-31,2009-08-31,2009-09-30,2009-10-31,2009-11-30,2009-12-31,2010-01-31,2010-02-28,2010-03-31,2010-04-30,2010-05-31,2010-06-30,2010-07-31,2010-08-31,2010-09-30,2010-10-31,2010-11-30,2010-12-31,2011-01-31,2011-02-28,2011-03-31,2011-04-30,2011-05-31,2011-06-30,2011-07-31,2011-08-31,2011-09-30,2011-10-31,2011-11-30,2011-12-31,2012-01-31,2012-02-29,2012-03-31,2012-04-30,2012-05-31,2012-06-30,2012-07-31,2012-08-31,2012-09-30,2012-10-31,2012-11-30,2012-12-31,2013-01-31,2013-02-28,2013-03-31,2013-04-30,2013-05-31,2013-06-30,2013-07-31,2013-08-31,2013-09-30,2013-10-31,2013-11-30,2013-12-31,2014-01-31,2014-02-28,2014-03-31,2014-04-30,2014-05-31,2014-06-30,2014-07-31,2014-08-31,2014-09-30,2014-10-31,2014-11-30,2014-12-31,City,State,house_type,cost_percentile_range
1,394913,1,Msa,NY,398637.0,401008.0,403144.0,407365.0,411308.0,415498.0,419870.0,424405.0,428919.0,433338.0,437544.0,441545.0,445444.0,449749.0,453887.0,458186.0,462296.0,466700.0,470949.0,475346.0,479729.0,484594.0,489089.0,493465.0,497963.0,502250.0,506409.0,510284.0,514505.0,519261.0,524339.0,530603.0,537346.0,544092.0,550138.0,556186.0,562332.0,568621.0,575169.0,580995.0,586847.0,592688.0,598897.0,604732.0,609761.0,614518.0,619097.0,623631.0,628906.0,634297.0,640111.0,645628.0,652165.0,659157.0,667097.0,675067.0,683531.0,691780.0,699555.0,706512.0,713176.0,719769.0,726809.0,735123.0,743968.0,752635.0,760509.0,768425.0,776315.0,784581.0,791832.0,799102.0,805296.0,811712.0,816665.0,821132.0,825079.0,828764.0,830919.0,831111.0,829718.0,826952.0,823581.0,819988.0,816684.0,814445.0,814341.0,814101.0,813758.0,810757.0,807353.0,803894.0,800621.0,798570.0,796234.0,794045.0,792045.0,789877.0,786919.0,783513.0,778284.0,773392.0,767998.0,763498.0,758801.0,753548.0,748004.0,742474.0,736607.0,730892.0,725813.0,720393.0,715884.0,710620.0,706012.0,700797.0,696708.0,693211.0,690835.0,689148.0,688566.0,688793.0,688140.0,687982.0,687473.0,688594.0,689386.0,689690.0,688703.0,686606.0,683711.0,680555.0,678531.0,677021.0,676750.0,675337.0,673974.0,671435.0,669305.0,667345.0,665505.0,663442.0,660929.0,658747.0,656686.0,654771.0,653024.0,651992.0,651464.0,651539.0,651150.0,650777.0,650233.0,650065.0,650477.0,651512.0,653036.0,655029.0,657169.0,659918.0,663400.0,667161.0,670653.0,673608.0,676554.0,679760.0,683228.0,686312.0,690217.0,693799.0,697984.0,701807.0,705421.0,708277.0,710112.0,711695.0,713187.0,714560.0,715725.0,717146.0,New York,NY,Condo,high
2,753899,2,Msa,CA,418030.0,419565.0,421719.0,425833.0,430146.0,434247.0,438441.0,442769.0,446883.0,450683.0,454265.0,458076.0,460997.0,464229.0,467609.0,472288.0,476740.0,480718.0,484799.0,489016.0,493412.0,497701.0,501410.0,505409.0,508653.0,512582.0,517217.0,523170.0,529958.0,536946.0,545829.0,554975.0,564208.0,572437.0,580691.0,588904.0,595773.0,602147.0,609175.0,617076.0,626906.0,634641.0,644802.0,655424.0,668083.0,678479.0,688573.0,698395.0,710052.0,723082.0,738199.0,755499.0,776754.0,797704.0,816032.0,830536.0,844363.0,858056.0,866701.0,876224.0,884887.0,896841.0,909628.0,922450.0,935018.0,946296.0,959876.0,974362.0,989344.0,1004393.0,1014253.0,1024676.0,1033264.0,1041726.0,1049152.0,1055479.0,1063675.0,1069969.0,1071696.0,1073918.0,1070814.0,1071093.0,1068815.0,1068539.0,1068501.0,1067779.0,1065783.0,1062307.0,1056463.0,1051180.0,1041389.0,1030764.0,1017776.0,1005564.0,996616.0,985140.0,974926.0,959636.0,943574.0,922178.0,900852.0,882108.0,866074.0,852473.0,843445.0,832555.0,819979.0,802066.0,789787.0,783122.0,778434.0,773906.0,769425.0,762755.0,757893.0,753958.0,754125.0,755216.0,760227.0,768354.0,771451.0,770568.0,770995.0,776187.0,782511.0,781279.0,776674.0,768474.0,760671.0,753218.0,746545.0,744596.0,743400.0,744285.0,741691.0,739280.0,731446.0,729773.0,728158.0,724500.0,716860.0,709799.0,709657.0,710665.0,709929.0,708900.0,707860.0,709035.0,711289.0,714619.0,719376.0,721851.0,725100.0,730824.0,739097.0,750704.0,761986.0,778001.0,793569.0,810380.0,824137.0,838264.0,850163.0,862686.0,873289.0,881841.0,891645.0,900498.0,910334.0,914339.0,915488.0,913855.0,913678.0,913788.0,915080.0,910439.0,907786.0,907175.0,913443.0,920632.0,Los Angeles-Long Beach-Anaheim,CA,Condo,high
3,394463,3,Msa,IL,297296.0,298057.0,299026.0,300913.0,302873.0,304796.0,306999.0,309569.0,312258.0,314851.0,317159.0,319343.0,321392.0,323164.0,325182.0,327201.0,329647.0,331913.0,334261.0,336730.0,339251.0,341792.0,343903.0,345743.0,347287.0,349038.0,351228.0,353084.0,355093.0,356888.0,359348.0,361916.0,364383.0,366557.0,368087.0,369956.0,371804.0,374061.0,376110.0,378537.0,380565.0,382321.0,383841.0,385947.0,388400.0,390641.0,392594.0,394320.0,396612.0,398726.0,400924.0,403419.0,406166.0,409370.0,412246.0,415304.0,417911.0,420607.0,423292.0,426254.0,429006.0,431869.0,434741.0,438002.0,441376.0,444815.0,448066.0,451236.0,454658.0,457889.0,460635.0,463251.0,465820.0,468312.0,470877.0,473090.0,475520.0,476757.0,477812.0,478490.0,479039.0,479155.0,479123.0,479430.0,480328.0,481223.0,481765.0,481536.0,480816.0,479748.0,478403.0,476996.0,474958.0,473093.0,471370.0,469248.0,467047.0,NaN,NaN,455539.0,NaN,449468.0,448033.0,442706.0,439512.0,433546.0,428676.0,422181.0,414559.0,409196.0,403665.0,401795.0,398299.0,396103.0,393712.0,391520.0,387749.0,384097.0,380436.0,379130.0,377094.0,376507.0,373824.0,374907.0,373487.0,374938.0,370664.0,368433.0,363772.0,361039.0,356145.0,352004.0,347997.0,345150.0,343544.0,341363.0,340749.0,338783.0,338581.0,336551.0,334696.0,330573.0,328379.0,324660.0,322928.0,319335.0,319438.0,319277.0,320492.0,320601.0,319431.0,318203.0,316703.0,317526.0,318338.0,318982.0,320492.0,322688.0,324784.0,327387.0,329861.0,333511.0,336115.0,339224.0,341635.0,345146.0,346498.0,348621.0,349902.0,352647.0,353969.0,354464.0,355326.0,356919.0,358103.0,357897.0,357942.0,358000.0,358614.0,359489.0,Chicago,IL,Condo,high
4,394514,4,Msa,TX,234357.0,234434.0,234530.0,234782.0,235061.0,235201.0,235371.0,235834.0,236491.0,237204.0,237862.0,238541.0,238794.0,238222.0,237650.0,237357.0,237539.0,237528.0,237536.0,237871.0,238158.0,238343.0,238298.0,238334.0,238374.0,238689.0,239110.0,239833.0,240433.0,241425.0,242310.0,243309.0,243952.0,244488.0,244938.0,245343.0,245608.0,245704.0,245907.0,246166.0,246354.0,246590.0,246632.0,246914.0,247169.0,247539.0,247785.0,247735.0,248835.0,251158.0,NaN,258155.0,259959.0,260631.0,260957.0,261649.0,262359.0,263065.0,263433.0,263700.0,264852.0,265550.0,266329.0,266713.0,267654.0,268620.0,269334.0,270091.0,270820.0,271012.0,271368.0,271326.0,271436.0,271876.0,272507.0,273655.0,274860.0,275923.0,276530.0,276842.0,277362.0,278699.0,279510.0,280353.0,279736.0,278934.0,278140.0,278536.0,279349.0,280078.0,280648.0,281289.0,282163.0,282645.0,282949.0,283230.0,281564.0,279499.0,277077.0,276459.0,276059.0,275735.0,275656.0,274749.0,273361.0,271560.0,270333.0,269552.0,268816.0,268814.0,269067.0,269647.0,269993.0,269863.0,269952.0,269285.0,268921.0,268320.0,269137.0,269740.0,269677.0,269198.0,268843.0,269484.0,269732.0,269788.0,268908.0,267478.0,265706.0,264193.0,262746.0,262024.0,261462.0,260930.0,260355.0,259479.0,259087.0,258480.0,258645.0,258374.0,258376.0,258053.0,257901.0,257309.0,256887.0,257613.0,258820.0,260253.0,261193.0,262095.0,263082.0,263603.0,264130.0,264589.0,265769.0,267038.0,268633.0,270044.0,271869.0,273614.0,275518.0,277473.0,279582.0,281177.0,282885.0,284795.0,287242.0,289484.0,291306.0,293347.0,295194.0,297043.0,298646.0,300683.0,302084.0,303503.0,304500.0,306276.0,308420.0,310826.0,Dallas-Fort Worth,TX,Condo,high
5,394974,5,Msa,PA,226122.0,226965.0,227465.0,228725.0,229810.0,231072.0,232262.0,233420.0,234633.0,235828.0,236981.0,238034.0,239139.0,240387.0,241835.0,243296.0,244705.0,246121.0,247806.0,249630.0,251613.0,253369.0,255212.0,256603.0,258071.0,259471.0,261305.0,263417.0,265599.0,268013.0,270474.0,273619.0,276919.0,280267.0,283019.0,285775.0,288305.0,290800.0,293225.0,295909.0,298979.0,302259.0,305817.0,309380.0,312930.0,316123.0,319234.0,321806.0,324336.0,326670.0,329463.0,332649.0,336562.0,340894.0,345608.0,350441.0,354683.0,358087.0,360884.0,364078.0,367731.0,370862.0,373673.0,376692.0,380861.0,385676.0,390541.0,395053.0,399133.0,403252.0,406769.0,410080.0,412453.0,414875.0,417371.0,420245.0,423021.0,425459.0,427371.0,428510.0,428841.0,428949.0,428637.0,428100.0,427231.0,426911.0,427500.0,428208.0,429379.0,429737.0,429913.0,428854.0,427629.0,426669.0,425879.0,424841.0,423056.0,422210.0,421901.0,422059.0,420772.0,418612.0,415621.0,412681.0,409455.0,406321.0,403447.0,400837.0,398552.0,397031.0,396448.0,396119.0,395162.0,393574.0,391352.0,389245.0,387209.0,386205.0,385913.0,385925.0,386051.0,385984.0,386025.0,386258.0,386716.0,386945.0,386208.0,384374.0,381827.0,378875.0,375810.0,373442.0,371759.0,370914.0,370043.0,368693.0,366744.0,364489.0,362511.0,360892.0,359211.0,357619.0,356156.0,355098.0,354042.0,353118.0,352797.0,352893.0,352855.0,352204.0,351243.0,350393.0,349868.0,349482.0,349398.0,349426.0,350115.0,350949.0,352089.0,353315.0,354997.0,356787.0,358499.0,359527.0,360790.0,361713.0,362911.0,363658.0,364829.0,366013.0,366717.0,366593.0,366689.0,367180.0,367773.0,367710.0,367476.0,367305.0,367528.0,367956.0,Philadelphia,PA,Condo,high

In [ ]:
data_housing = pd.concat([data_1, data_2, data_3], axis=0)
data_housing.tail()

,RegionID,SizeRank,RegionType,StateName,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,2000-06-30,2000-07-31,2000-08-31,2000-09-30,2000-10-31,2000-11-30,2000-12-31,2001-01-31,2001-02-28,2001-03-31,2001-04-30,2001-05-31,2001-06-30,2001-07-31,2001-08-31,2001-09-30,2001-10-31,2001-11-30,2001-12-31,2002-01-31,2002-02-28,2002-03-31,2002-04-30,2002-05-31,2002-06-30,2002-07-31,2002-08-31,2002-09-30,2002-10-31,2002-11-30,2002-12-31,2003-01-31,2003-02-28,2003-03-31,2003-04-30,2003-05-31,2003-06-30,2003-07-31,2003-08-31,2003-09-30,2003-10-31,2003-11-30,2003-12-31,2004-01-31,2004-02-29,2004-03-31,2004-04-30,2004-05-31,2004-06-30,2004-07-31,2004-08-31,2004-09-30,2004-10-31,2004-11-30,2004-12-31,2005-01-31,2005-02-28,2005-03-31,2005-04-30,2005-05-31,2005-06-30,2005-07-31,2005-08-31,2005-09-30,2005-10-31,2005-11-30,2005-12-31,2006-01-31,2006-02-28,2006-03-31,2006-04-30,2006-05-31,2006-06-30,2006-07-31,2006-08-31,2006-09-30,2006-10-31,2006-11-30,2006-12-31,2007-01-31,2007-02-28,2007-03-31,2007-04-30,2007-05-31,2007-06-30,2007-07-31,2007-08-31,2007-09-30,2007-10-31,2007-11-30,2007-12-31,2008-01-31,2008-02-29,2008-03-31,2008-04-30,2008-05-31,2008-06-30,2008-07-31,2008-08-31,2008-09-30,2008-10-31,2008-11-30,2008-12-31,2009-01-31,2009-02-28,2009-03-31,2009-04-30,2009-05-31,2009-06-30,2009-07-31,2009-08-31,2009-09-30,2009-10-31,2009-11-30,2009-12-31,2010-01-31,2010-02-28,2010-03-31,2010-04-30,2010-05-31,2010-06-30,2010-07-31,2010-08-31,2010-09-30,2010-10-31,2010-11-30,2010-12-31,2011-01-31,2011-02-28,2011-03-31,2011-04-30,2011-05-31,2011-06-30,2011-07-31,2011-08-31,2011-09-30,2011-10-31,2011-11-30,2011-12-31,2012-01-31,2012-02-29,2012-03-31,2012-04-30,2012-05-31,2012-06-30,2012-07-31,2012-08-31,2012-09-30,2012-10-31,2012-11-30,2012-12-31,2013-01-31,2013-02-28,2013-03-31,2013-04-30,2013-05-31,2013-06-30,2013-07-31,2013-08-31,2013-09-30,2013-10-31,2013-11-30,2013-12-31,2014-01-31,2014-02-28,2014-03-31,2014-04-30,2014-05-31,2014-06-30,2014-07-31,2014-08-31,2014-09-30,2014-10-31,2014-11-30,2014-12-31,City,State,house_type,cost_percentile_range
903,394767,929,Msa,TX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,81695.0,81789.0,81754.0,81700.0,81811.0,82161.0,82906.0,83540.0,84003.0,84170.0,84105.0,83890.0,83594.0,83859.0,84385.0,85036.0,85523.0,86084.0,86720.0,87124.0,87452.0,88041.0,88790.0,89548.0,89878.0,89915.0,90043.0,90439.0,91229.0,92151.0,93065.0,93922.0,94688.0,95630.0,96609.0,97200.0,97483.0,97591.0,98042.0,98582.0,99316.0,100155.0,100945.0,101521.0,102038.0,Lamesa,TX,Condo,high
904,753874,930,Msa,CO,158967.0,159393.0,159850.0,160254.0,160607.0,160892.0,162219.0,163380.0,163828.0,163510.0,164111.0,165322.0,166840.0,167683.0,168897.0,170139.0,171212.0,171540.0,171773.0,172060.0,172160.0,172050.0,172388.0,173097.0,173796.0,174492.0,175160.0,176216.0,177002.0,178203.0,179310.0,180065.0,180603.0,180822.0,180907.0,180971.0,180655.0,180468.0,180109.0,180177.0,180481.0,180925.0,181452.0,182192.0,182980.0,183662.0,183887.0,184056.0,184401.0,184898.0,185333.0,185837.0,186855.0,187992.0,189157.0,189900.0,190938.0,191584.0,192332.0,193052.0,194089.0,195194.0,196647.0,198293.0,199913.0,201543.0,203347.0,204954.0,206205.0,206918.0,207687.0,208123.0,208752.0,209321.0,209974.0,210656.0,211520.0,212482.0,213302.0,214192.0,215322.0,216664.0,217726.0,218747.0,219325.0,220009.0,220333.0,221100.0,221949.0,222821.0,223521.0,224244.0,225165.0,226072.0,226719.0,227182.0,227587.0,227976.0,228156.0,228201.0,228311.0,228453.0,228442.0,228306.0,228329.0,228281.0,228250.0,228168.0,228161.0,227972.0,227481.0,226983.0,226737.0,226291.0,225769.0,224821.0,224173.0,223683.0,223184.0,223192.0,223265.0,223384.0,223163.0,222841.0,222895.0,222709.0,222341.0,221612.0,221014.0,220821.0,220683.0,220344.0,219692.0,218901.0,218223.0,217752.0,217611.0,217400.0,217261.0,217264.0,217558.0,217687.0,217887.0,218693.0,219662.0,220553.0,221028.0,221363.0,221825.0,222241.0,222691.0,223170.0,223588.0,224392.0,225165.0,226179.0,227146.0,228345.0,229548.0,230997.0,232279.0,233673.0,234728.0,235884.0,236989.0,238159.0,239456.0,240746.0,242161.0,243483.0,245085.0,246631.0,248330.0,249915.0,251899.0,253316.0,254609.0,255884.0,257843.0,259699.0,Craig,CO,Condo,high
905,394968,931,Msa,TX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pecos,TX,Condo,high
906,395188,932,Msa,TX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99753.0,99783.0,99640.0,99230.0,98839.0,98474.0,98409.0,98308.0,98206.0,98088.0,97961.0,98022.0,97950.0,97916.0,97800.0,97707.0,97559.0,97337.0,97166.0,96766.0,96402.0,96199.0,96253.0,96336.0,96306.0,96332.0,96309.0,96469.0,96639.0,96847.0,96969.0,97065.0,97138.0,97198.0,97303.0,97589.0,97847.0,98115.0,98389.0,98617.0,99046.0,99405.0,99904.0,100264.0,100678.0,101086.0,101580.0,102069.0,102502.0,102821.0,103312.0,103867.0,104572.0,105169.0,105885.0,106523.0,107177.0,107792.0,108349.0,108830.0,109305.0,109746.0,110337.0,110854.0,111498.0,111949.0,112563.0,Vernon,TX,Condo,high
907,394743,933,Msa,AK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,337283.0,338892.0,340190.0,343464.0,346721.0,350173.0,352861.0,355515.0,358005.0,360498.0,362653.0,364751.0,366642.0,368314.0,369707.0,370710.0,371621.0,372091.0,373503.0,375436.0,378105.0,379532.0,380665.0,381322.0,381375.0,380680.0,379332.0,379430.0,379210.0,379178.0,379075.0,379298.0,379611.0,378877.0,378023.0,377053.0,376475.0,375958.0,375540.0,375611.0,376104.0,376881.0,377111.0,377357.0,377522.0,377485.0,377390.0,376658.0,376069.0,375074.0,374265.0,373242.0,372340.0,371744.0,371431.0,371322.0,371287.0,371419.0,371703.0,371940.0,372544.0,373064.0,373613.0,374073.0,373993.0,374065.0,374879.0,376082.0,377295.0,376962.0,376650.0,376087.0,375803.0,375329.0,374910.0,374697.0,374628.0,374462.0,374660.0,374880.0,375510.0,375656.0,375856.0,375536.0,375540.0,376222.0,377197.0,378927.0,380288.0,381948.0,383109.0,384185.0,385615.0,386651.0,387815.0,388475.0,389530.0,390189.0,390822.0,391050.0,391399.0,391762.0,392493.0,392705.0,392921.0,392992.0,394055.0,395629.0,397063.0,398365.0,399223.0,400387.0,401514.0,402690.0,403598.0,404440.0,Ketchikan,AK,Condo,high

In [ ]:
data_housing.shape

(2725, 188)

In [ ]:
data_housing.columns

Index(['RegionID', 'SizeRank', 'RegionType', 'StateName', '2000-01-31',
       '2000-02-29', '2000-03-31', '2000-04-30', '2000-05-31', '2000-06-30',
       ...
       '2014-07-31', '2014-08-31', '2014-09-30', '2014-10-31', '2014-11-30',
       '2014-12-31', 'City ', 'State', 'house_type', 'cost_percentile_range'],
      dtype='object', length=188)

In [ ]:
data_housing=data_housing.drop('StateName', axis=1)

In [ ]:
data_housing.head()

,RegionID,SizeRank,RegionType,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,2000-06-30,2000-07-31,2000-08-31,2000-09-30,2000-10-31,2000-11-30,2000-12-31,2001-01-31,2001-02-28,2001-03-31,2001-04-30,2001-05-31,2001-06-30,2001-07-31,2001-08-31,2001-09-30,2001-10-31,2001-11-30,2001-12-31,2002-01-31,2002-02-28,2002-03-31,2002-04-30,2002-05-31,2002-06-30,2002-07-31,2002-08-31,2002-09-30,2002-10-31,2002-11-30,2002-12-31,2003-01-31,2003-02-28,2003-03-31,2003-04-30,2003-05-31,2003-06-30,2003-07-31,2003-08-31,2003-09-30,2003-10-31,2003-11-30,2003-12-31,2004-01-31,2004-02-29,2004-03-31,2004-04-30,2004-05-31,2004-06-30,2004-07-31,2004-08-31,2004-09-30,2004-10-31,2004-11-30,2004-12-31,2005-01-31,2005-02-28,2005-03-31,2005-04-30,2005-05-31,2005-06-30,2005-07-31,2005-08-31,2005-09-30,2005-10-31,2005-11-30,2005-12-31,2006-01-31,2006-02-28,2006-03-31,2006-04-30,2006-05-31,2006-06-30,2006-07-31,2006-08-31,2006-09-30,2006-10-31,2006-11-30,2006-12-31,2007-01-31,2007-02-28,2007-03-31,2007-04-30,2007-05-31,2007-06-30,2007-07-31,2007-08-31,2007-09-30,2007-10-31,2007-11-30,2007-12-31,2008-01-31,2008-02-29,2008-03-31,2008-04-30,2008-05-31,2008-06-30,2008-07-31,2008-08-31,2008-09-30,2008-10-31,2008-11-30,2008-12-31,2009-01-31,2009-02-28,2009-03-31,2009-04-30,2009-05-31,2009-06-30,2009-07-31,2009-08-31,2009-09-30,2009-10-31,2009-11-30,2009-12-31,2010-01-31,2010-02-28,2010-03-31,2010-04-30,2010-05-31,2010-06-30,2010-07-31,2010-08-31,2010-09-30,2010-10-31,2010-11-30,2010-12-31,2011-01-31,2011-02-28,2011-03-31,2011-04-30,2011-05-31,2011-06-30,2011-07-31,2011-08-31,2011-09-30,2011-10-31,2011-11-30,2011-12-31,2012-01-31,2012-02-29,2012-03-31,2012-04-30,2012-05-31,2012-06-30,2012-07-31,2012-08-31,2012-09-30,2012-10-31,2012-11-30,2012-12-31,2013-01-31,2013-02-28,2013-03-31,2013-04-30,2013-05-31,2013-06-30,2013-07-31,2013-08-31,2013-09-30,2013-10-31,2013-11-30,2013-12-31,2014-01-31,2014-02-28,2014-03-31,2014-04-30,2014-05-31,2014-06-30,2014-07-31,2014-08-31,2014-09-30,2014-10-31,2014-11-30,2014-12-31,City,State,house_type,cost_percentile_range
1,394913,1,Msa,140565.0,141355.0,142038.0,143419.0,144711.0,146087.0,147558.0,149094.0,150695.0,152250.0,153735.0,155134.0,156492.0,158013.0,159501.0,161071.0,162557.0,164188.0,165808.0,167563.0,169338.0,171268.0,172999.0,174667.0,176375.0,178152.0,179936.0,181665.0,183458.0,185434.0,187566.0,190197.0,192994.0,195830.0,198326.0,200715.0,203081.0,205559.0,208296.0,210887.0,213493.0,216013.0,218730.0,221432.0,223877.0,226111.0,228123.0,230100.0,232260.0,234450.0,236812.0,239221.0,242049.0,245078.0,248305.0,251487.0,254848.0,258163.0,261372.0,264294.0,267136.0,269863.0,272757.0,276178.0,279876.0,283517.0,286903.0,290296.0,293632.0,296998.0,300043.0,303040.0,305548.0,308116.0,310256.0,312414.0,314276.0,316088.0,317223.0,317726.0,317585.0,316979.0,316121.0,315083.0,314079.0,313416.0,313399.0,313486.0,313407.0,312516.0,311255.0,309965.0,308679.0,307774.0,306755.0,305740.0,304966.0,304257.0,303204.0,301711.0,299431.0,297262.0,295004.0,292929.0,290714.0,288234.0,285756.0,283547.0,281340.0,279182.0,276980.0,274747.0,272861.0,270948.0,269177.0,267364.0,265955.0,264875.0,264140.0,263745.0,263667.0,263874.0,263746.0,263638.0,263409.0,263524.0,263514.0,263167.0,262388.0,261172.0,259777.0,258353.0,257383.0,256582.0,256022.0,255106.0,254168.0,252880.0,251590.0,250365.0,249200.0,248110.0,246850.0,245730.0,244745.0,243824.0,243077.0,242389.0,242071.0,241872.0,241618.0,241246.0,240910.0,240691.0,240776.0,241061.0,241576.0,242246.0,242943.0,243850.0,244876.0,246095.0,247325.0,248455.0,249489.0,250657.0,251913.0,253021.0,254211.0,255153.0,256429.0,257583.0,258802.0,259674.0,260168.0,260548.0,260863.0,261213.0,261389.0,261752.0,New York,NY,Condo,lower
2,753899,2,Msa,150920.0,151319.0,152080.0,153511.0,155108.0,156605.0,158164.0,159847.0,161438.0,162836.0,164145.0,165494.0,166475.0,167478.0,168613.0,170297.0,171974.0,173593.0,175279.0,177087.0,178842.0,180608.0,182151.0,183834.0,185173.0,186730.0,188583.0,190975.0,193649.0,196322.0,199730.0,203310.0,207056.0,210411.0,213755.0,216996.0,219636.0,222044.0,224814.0,227864.0,231717.0,234771.0,238957.0,243309.0,248336.0,252331.0,256219.0,260257.0,265016.0,270074.0,275589.0,282138.0,290301.0,298337.0,305552.0,311807.0,318709.0,325497.0,330193.0,334628.0,338381.0,343825.0,349283.0,355067.0,360298.0,365678.0,371820.0,378407.0,385020.0,392012.0,396868.0,401643.0,405696.0,409534.0,413257.0,416338.0,420559.0,423902.0,425718.0,427340.0,426680.0,427145.0,427026.0,427975.0,428568.0,428672.0,428078.0,427424.0,425549.0,423674.0,419889.0,415782.0,410823.0,405741.0,401730.0,396907.0,392906.0,386901.0,379560.0,369575.0,358983.0,349295.0,339892.0,331251.0,324589.0,318326.0,311855.0,303553.0,297519.0,293759.0,291081.0,288025.0,284985.0,281403.0,278748.0,277029.0,276377.0,276126.0,277230.0,280015.0,281075.0,280622.0,280856.0,282790.0,285548.0,285100.0,283631.0,280601.0,278174.0,275837.0,273680.0,273052.0,272686.0,273154.0,272087.0,271149.0,268032.0,267477.0,266712.0,265629.0,262882.0,260321.0,260016.0,260089.0,259790.0,259388.0,259037.0,259422.0,260208.0,261476.0,263213.0,264571.0,266093.0,268691.0,271650.0,276172.0,280271.0,286429.0,292436.0,299264.0,304917.0,310947.0,316455.0,322443.0,327403.0,331322.0,335374.0,338933.0,343157.0,345159.0,346471.0,346336.0,346964.0,347417.0,348356.0,347823.0,347893.0,348699.0,351000.0,353667.0,Los Angeles-Long Beach-Anaheim,CA,Condo,lower
3,394463,3,Msa,106839.0,107099.0,107422.0,108061.0,108714.0,109349.0,110033.0,110844.0,111711.0,112603.0,113395.0,114149.0,114839.0,115449.0,116144.0,116857.0,117708.0,118480.0,119223.0,120012.0,120814.0,121678.0,122358.0,122963.0,123473.0,124099.0,124845.0,125464.0,126156.0,126779.0,127626.0,128500.0,129379.0,130210.0,130783.0,131458.0,132075.0,132855.0,133558.0,134374.0,135082.0,135716.0,136278.0,137001.0,137867.0,138713.0,139431.0,140067.0,140863.0,141650.0,142439.0,143292.0,144230.0,145326.0,146330.0,147362.0,148239.0,149169.0,150083.0,151084.0,152030.0,153070.0,154120.0,155288.0,156454.0,157652.0,158752.0,159823.0,160949.0,162034.0,162967.0,163856.0,164710.0,165568.0,166425.0,167182.0,168013.0,168534.0,169014.0,169386.0,169723.0,169921.0,170081.0,170341.0,170773.0,171177.0,171467.0,171551.0,171485.0,171307.0,171016.0,170743.0,170240.0,169779.0,169298.0,168708.0,168061.0,NaN,NaN,164779.0,NaN,163207.0,162668.0,160627.0,159397.0,157199.0,155492.0,153147.0,150508.0,148631.0,146696.0,145866.0,144398.0,143369.0,142250.0,141201.0,139514.0,138017.0,136653.0,136228.0,135528.0,135290.0,134386.0,134782.0,134376.0,134842.0,133286.0,132374.0,130651.0,129513.0,127566.0,125853.0,124239.0,123000.0,122178.0,121095.0,120521.0,119500.0,119146.0,118233.0,117419.0,115771.0,114770.0,113265.0,112502.0,111089.0,110844.0,110460.0,110540.0,110294.0,109677.0,109052.0,108383.0,108517.0,108678.0,108755.0,109103.0,109671.0,110207.0,110940.0,111669.0,112923.0,113930.0,115153.0,116082.0,117400.0,117975.0,118788.0,119166.0,119994.0,120454.0,120795.0,121319.0,122122.0,122839.0,123156.0,123520.0,123766.0,124127.0,124530.0,Chicago,IL,Condo,lower
4,394514,4,Msa,83372.0,83445.0,83482.0,83617.0,83773.0,83922.0,84093.0,84357.0,84662.0,84988.0,85299.0,85663.0,85835.0,85626.0,85465.0,85442.0,85651.0,85721.0,85800.0,86041.0,86234.0,86384.0,86432.0,86524.0,86604.0,86804.0,87061.0,87437.0,87779.0,88286.0,88730.0,89196.0,89526.0,89845.0,90137.0,90408.0,90641.0,90800.0,91004.0,91177.0,91316.0,91458.0,91542.0,91710.0,91878.0,92108.0,92293.0,92309.0,92861.0,93882.0,NaN,96880.0,97644.0,97946.0,98092.0,98416.0,98693.0,98962.0,99140.0,99283.0,99869.0,100172.0,100503.0,100639.0,101014.0,101386.0,101599.0,101829.0,102072.0,102066.0,102140.0,102044.0,102097.0,102308.0,102578.0,103008.0,103453.0,103862.0,104073.0,104130.0,104306.0,104875.0,105237.0,105617.0,105407.0,105150.0,104869.0,105080.0,105458.0,105782.0,106030.0,106307.0,106719.0,106933.0,107053.0,107139.0,106461.0,105582.0,104518.0,104122.0,103791.0,103523.0,103363.0,102875.0,102141.0,101231.0,100497.0,100048.0,99635.0,99656.0,99702.0,99950.0,100087.0,100054.0,100056.0,99801.0,99698.0,99568.0,99904.0,100145.0,100067.0,99846.0,99624.0,99828.0,99912.0,99985.0,99611.0,98985.0,98154.0,97483.0,96882.0,96580.0,96248.0,95817.0,95403.0,94896.0,94574.0,94128.0,94010.0,93812.0,93796.0,93665.0,93592.0,93304.0,93035.0,93202.0,93490.0,93838.0,94092.0,94450.0,95004.0,95293.0,95536.0,95723.0,96154.0,96566.0,96969.0,97292.0,97815.0,98484.0,99248.0,100063.0,100899.0,101598.0,102389.0,103264.0,104268.0,105138.0,105671.0,106259.0,106813.0,107510.0,108239.0,109105.0,109616.0,110158.0,110598.0,111454.0,112459.0,113519.0,Dallas-Fort Worth,TX,Condo,lower
5,394974,5,Msa,75530.0,75779.0,75940.0,76326.0,76676.0,77033.0,77376.0,77688.0,78051.0,78400.0,78742.0,79054.0,79378.0,79746.0,80167.0,80613.0,81018.0,81436.0,81903.0,82421.0,82964.0,83459.0,83981.0,84402.0,84832.0,85256.0,85787.0,86373.0,86957.0,87616.0,88342.0,89231.0,90178.0,91114.0,91917.0,92726.0,93495.0,94304.0,95050.0,95918.0,96860.0,97921.0,99088.0,100325.0,101582.0,102686.0,103718.0,104610.0,105496.0,106387.0,107329.0,108367.0,109623.0,111144.0,112925.0,114854.0,116540.0,117892.0,119027.0,120330.0,121815.0,123058.0,124267.0,125506.0,127175.0,129034.0,131049.0,133002.0,134807.0,136514.0,138022.0,139442.0,140501.0,141506.0,142440.0,143614.0,144835.0,146092.0,147165.0,147912.0,148358.0,148612.0,148747.0,148857.0,148964.0,149178.0,149633.0,150043.0,150675.0,151067.0,151401.0,151286.0,150982.0,150832.0,150704.0,150567.0,150074.0,150000.0,149885.0,149929.0,149417.0,148720.0,147690.0,146636.0,145572.0,144682.0,143820.0,142924.0,141922.0,141189.0,140857.0,140734.0,140437.0,139926.0,139281.0,138737.0,138253.0,138033.0,138024.0,138018.0,138170.0,138227.0,138397.0,138547.0,138752.0,138865.0,138579.0,137822.0,136574.0,135264.0,134046.0,133096.0,132361.0,131876.0,131601.0,131018.0,130165.0,129002.0,127967.0,127068.0,126380.0,125799.0,125289.0,124821.0,124324.0,123821.0,123589.0,123492.0,123373.0,122982.0,122519.0,122067.0,121779.0,121509.0,121370.0,121246.0,121294.0,121356.0,121575.0,121883.0,122416.0,122968.0,123422.0,123673.0,123880.0,124102.0,124430.0,124686.0,125030.0,125325.0,125536.0,125455.0,125445.0,125483.0,125642.0,125619.0,125583.0,125556.0,125647.0,125837.0,Philadelphia,PA,Condo,lower

In [ ]:
housing_data_csv = "/content/gdrive/My Drive/WWCode Python Workshop/housing_data.csv"
data_housing.to_csv(housing_data_csv)